### ISSUE TITLE
Consider moving auto-configuration codes to `azure-autoconfigure`

### ISSUE THREAD

**Issue by snicoll** [Microsoft/azure-spring-boot#158]
Looking at the project, most modules bring a few classes and there are also some common concepts in `azure-spring-common`. 

Given the surface area and the size of the project, it would be doable to move all the auto-configuration code to a single module (with optional dependencies). The starters would remain the same (and the solution 100% backward compatible).

I also think having them together should improve testing of the "platform"

If you do that, starters cloud move to `azure-spring-boot-starters`. See also #159

**Comment by ZhijunZhao** [comment]
@snicoll Just to make sure we're on the same page before I proceed to make code changes. :)

So, your suggestion is :

1. Add a new module with name "azure-autoconfigure". This module has *optional* dependencies to azure service SDKs.

2. Move all the auto-configure code, currently residing in starter modules or auto-configure modules, to this new module.

3. There would be no code in all the existing 7 starters. Instead, their pom files have the dependency to this new module and corresponding azure service SDK. 

4. No change for the special `azure-cloud-foundry-service` module.

**Comment by snicoll** [comment]
Almost! I'd move the cloudfoundry code as well and get rid of the "common" module. The cloudfoundry support is not a starter and doesn't deserve an isolated module IMO. It's part of what you'd get when working with Spring and Azure.

With that change starters are really what they are supposed to be: an opinionated view of dependencies for a given use case.

Let me know if you have more questions.

**Comment by ZhijunZhao** [comment]
@Snicoll, I see. 

So, move the code of `azure-cloud-foundry-service` module to this new module `azure-autoconfigure`. 

For this `common` module, It would be good to get ride of it too. But besides auto-configure code, it's also used in the `spring-data-azure-documentdb` module. Right now, that common module only includes a function that get hashed mac address. Do you have any suggestion to avoid duplicate code?

@yungez

**Comment by snicoll** [comment]
If you want to be contextually more correct, you could have a `azure-spring` with the code that's related to the Spring integration but that's not strictly speaking related to auto-configuration. And then a `azure-autoconfigure` for only the auto-configuration code. While I think the package structure should reflect that somehow, I am not sure a separate module is warranted at this point. 

If you structure the code separately, you can move to a different module if that happens to be necessary.

As for the hashed mac address function, I'd duplicate it.  I know it sounds weird but that's something that framework development taught me. Your common module must have a semantic besides "sharing code" otherwise it'll end up as a dumping ground. Those concepts (documentDB and spring boot support) must be separate so, given the surface area, I'd duplicate it.

**Comment by yungez** [comment]
#177
