### ISSUE TITLE
Consider moving samples to a shared location

### ISSUE THREAD

**Issue by snicoll** [Microsoft/azure-spring-boot#159]
Relates to #132

There is some noise in each starter currently:

1. Most if not all `properties` (the two maven one can be replaced by `java.version` btw)
2. `licenses`
3. `developers`
4. `scm`
5. `dependencyManagement`
6.  The `checkstyle`, `findbugs` and `spring-boot` plugin (As for the latter, we already discussed that it's a duplication since you inherit from Spring Boot's parent).

You could have a `azure-samples` root directory with all the samples in them. That way they are easier to find and you can move that noise to the parent.

**Comment by ZhijunZhao** [comment]
@snicoll I think I fixed all the items you mentioned here, except the `spring-boot` plugin. I know it's included in the spring boot parent, but I have to specify the repackage goal explicitly. Or else, the generated jar won't run with `java -jar *.jar` command. 

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by snicoll** [comment]
@ZhijunZhao sorry but that does not make any sense to me.  It [already is configured](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-starters/spring-boot-starter-parent/pom.xml#L157) so something else must prevent the sample to run.
