### ISSUE TITLE
Move spring-data-azure-documentdb to a separate GIthub repository

### ISSUE THREAD

**Issue by snicoll** [Microsoft/azure-spring-boot#170]
The Spring Data integration for DocumentDB is not tied to the Spring Boot support and should have a different release cycle. 

Release should match a Spring Data release train so maintenance branches would have a different lifecycle as well. 

I'd argue that the auto-configuration should be kept here, in `azure-autoconfigure` if #158 is accepted

**Comment by yungez** [comment]
@snicoll, thanks for the valuable feedback. spring data documentdb support has its own repo now at https://github.com/Microsoft/spring-data-azure-cosmosdb-documentdb.

**Comment by snicoll** [comment]
@yungez thank you but that link is 404 for me. Perhaps the repo is private?

**Comment by yungez** [comment]
https://github.com/Microsoft/spring-data-azure-cosmosdb-documentdb/invitations

**Comment by qwazer** [comment]
Can you please give me a invite to this repo too? I want to build Spring Boot App with Azure CosmosDB

**Comment by qwazer** [comment]
Thanks, I have access now

**Comment by yungez** [comment]
the repo is public now, enjoy it.
