### ISSUE TITLE
Cloud Foundry sample doc needs to be updated

### ISSUE THREAD

**Issue by mjeffries-pivotal** [Microsoft/azure-spring-boot#217]
Need to update the cloud foundry doc to remove the optional JSON configuration string.  To use the configuration option, the user must be able to specify the azure resource group name used when installing the Azure service broker.  Better to just remove reference to the configuration string since the broker now works with no configuration options specified

**Comment by ZhijunZhao** [comment]
@mjeffries-pivotal Could you help to update the doc? It took me one whole day to set up the CF environment. But I forget the steps to run the sample. It would be good that the doc is reworked. I can help to double-test it.

**Comment by Incarnation-p-lee** [comment]
I may close this issue for now as inactive. If you still meet similar issue, please feel free to reopen.
