### ISSUE TITLE
Cloud Foundry service bus example needs to be removed

### ISSUE THREAD

**Issue by mjeffries-pivotal** [Microsoft/azure-spring-boot#218]
Please remove the sample.cloudfoundry.servicebus.ServiceBusRestController class and package.  It uses an injected resource that requires a topic and queue to exist in order for the app to start successfully.  Again, the user would need access to the service bus configuration controlled by the azure service broker in order to create the queue and topic.

**Comment by ZhijunZhao** [comment]
@mjeffries-pivotal I need more context here. It would be great if you can give a hand on this too.

**Comment by Incarnation-p-lee** [comment]
@isatishp
I may close this issue for now as inactive. If you still meet similar issue, please feel free to reopen.
