### ISSUE TITLE
Spring Boot 2 support

### ISSUE THREAD

**Issue by snicoll** [Microsoft/azure-spring-boot#223]
Spring Boot 2 is still in milestone phase but it would be nice if the Azure Spring Boot integration had a milestone or at least a compatibility build against it. 

It is a new major feature so my recommendation is to have two separate branches (current `master` on `1.5.x` and the new `master` with a version bump on `2.x`). There are also some major changes that might have to be reflected here (the Spring Security comes to mind, cc @rwinch

**Comment by sshogunn** [comment]
Greetings,

Any ideas, will Azure be supported by Spring Boot 2 or not?

**Comment by Matthew-Dong** [comment]
Hi all, 

Scheduled this in Milestone V0.2.2 targeting Feb. 28.

**Comment by snicoll** [comment]
@Matthew-Dong May I suggest to change the version more obviously for this? I assume you won't support Spring Boot 1.x and Spring Boot 2 at the same time so this is not a bug fix release at all. And you may want to offer additional `0.2` for Spring Boot 1 maintenance support.

A `0.3` or even `0.5` feels more appropriate for me. Thoughts?

**Comment by Matthew-Dong** [comment]
@snicoll good suggestion. 

After discussion, we will use `2.x.x` for Spring Boot 2, while `0.x.x` for Spring Boot 1 maintenance. Sounds good? 

And we're testing against the recent RC of SB2. Would consider having a RC against that.

**Comment by snicoll** [comment]
@Matthew-Dong `0.x.x` to `2.x.x` sounds quite a leap to me. But whatever clearly differentiates supported generation works for me. Thanks!

if you have snapshots we can also open up SB 2 snapshot with your integration.

**Comment by Matthew-Dong** [comment]
@snicoll my thought is to map `2.x.x` in this repo with Spring Boot `2.x.x`. 

Sure, would let you know if we get the snapshot ready. Thanks!

**Comment by yungez** [comment]
version 2.0.1 supports SB 2..0.0RELEASE released.
