### ISSUE TITLE
Support for Shared Access Signature

### ISSUE THREAD

**Issue by pomverte** [microsoft/azure-spring-boot#229]
Rather than using the Access keys / CONNECTION STRING, I would like to use a "Shared Access Signature"

**Comment by ZhijunZhao** [comment]
@pomverte Is this requirement for Azure Storage Starter?

**Comment by pomverte** [comment]
@ZhijunZhao : yes it is for the **azure-storage-spring-boot-starter**
Apologies, I wasn't clear in my first message

I've been able to use the _azure.storage.connection-string_, but in my case, we would like to use *Shared Access Signature*

**Comment by Crudelus** [comment]
I would like to push this topic again as we want to regulate what kind of access different services get. It also helps us regarding the gdpr that some services are only allowed to create new files and not read any content as it is possible with sas. As long as they are not supported the spring boot integration is sadly out of scope for us.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
