### ISSUE TITLE
B2C Support & Sample

### ISSUE THREAD

**Issue by ErikGrimes** [Microsoft/azure-spring-boot#230]
As I understand it, B2C is a different than Active Directory classic and requires MSAL.

**Comment by ZhijunZhao** [comment]
@yaweiw

**Comment by Crudelus** [comment]
For our application a B2C support would be very helpful. Are there any news regarding this issue?

**Comment by yaweiw** [comment]
@Crudelus you are checking at exactly the right time. We are discussing internal to add B2C support. Would you like to elaborate your pictured use case in production wrt B2C?
@sophiaso

**Comment by Crudelus** [comment]
We are developing an enterprise spring application which is used by company internal users existing in our Azure AD accounts. These users are allowed to log in and configure the application and configure some end user related features.

As we have to enable our customers to use this application in the future we need a login for our end users to get access to the system and monitor the processed data in the system according to their roles their own data or associated end user data for an agent. As these end users are not present in our AD we want them to be provided to the system by B2C. We would need a way to differentiate if the user logged in through the  AD or B2C as the roles managed internally need to be assigned differently depending on origin. 

Currently we have implemented an own authentication provider as the provided library lacks this feature.

**Comment by yaweiw** [comment]
Thanks @Crudelus we will plan for it.

**Comment by xscript** [comment]
The B2C support work is tracked at #464 . @ErikGrimes @Crudelus please follow up from there.
