### ISSUE TITLE
Autoconfigure vs Starter

### ISSUE THREAD

**Issue by aochsner** [Microsoft/azure-spring-boot#234]
Hello:

It seems there are 2 ways to configure the azure spring boot dependencies:

1. Via [AutoConfigure](https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot)
1. Via [Starters](https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-starters)

What questions would lead me to choosing one vs the other?

**Comment by ZhijunZhao** [comment]
@aochsner I suggest to use the starters directly since you don't need to care about Azure dependencies.
