### ISSUE TITLE
Cosmosdb Saved data cannot be found in portal but from azure-documentdb-spring-boot-starter

### ISSUE THREAD

**Issue by alvindaiyan** [Microsoft/azure-spring-boot#236]
My project is using azure-documentdb-spring-boot-starter:0.2.0 to interact with cosmosdb:

```
@Repository
public interface PingEasyRepo extends DocumentDbRepository<PingEasy, String> {
}


@Document(collection = "test")
public class PingEasy {
    @Id
    private String id;
    private String content;

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}
```
The code runs and can do save and findAll. But when I go to azure portal and cosmosdb data explorer, the data not appeared. When I open browser tools, I see failed requests with "500 Internal Server Error: Object reference not set to an instance of an object." and exceptions:

```
Uncaught TypeError: xhr.getResponseHeader is not a function
    at Object.DocumentClientFactory._shouldForceRetry (DocumentClientFactory.js?v=1.17.110.1:12)
    at HttpRequest.xhr.onreadystatechange (documentdbclient-1.14.0.js?v=1.17.110.1:3287)
    at HttpRequest._onAjaxError (Request.js?v=1.17.110.1:42)
    at i (jquery.min.js:2)
    at Object.fireWith [as rejectWith] (jquery.min.js:2)
    at y (jquery.min.js:4)
    at XMLHttpRequest.c (jquery.min.js:4)
```

**Comment by alvindaiyan** [comment]
Hi, Just update, if I create the cosmosdb with mongo as my query api, it not works, the data explorer broken. But if I'm using sql as query api, the data explorer works again

**Comment by alvindaiyan** [comment]
To answer my question, because of I'm using document db library but save and reading data from mongodb

**Comment by Matthew-Dong** [comment]
Hi, @alvindaiyan. Glad that you found the solution. 

@yungez Please review and close the issue if validated. And we should consider adding more error message in next release. Thanks.
