### ISSUE TITLE
[aad] Parse spring roles from azure ad roles

### ISSUE THREAD

**Issue by kamillus** [microsoft/azure-spring-boot#239]
Currently, the spring library parses user groups out of the graph api and populates the spring roles. The expected behaviour is to parse jwt app roles and use that in the PreAuthorize filter.

**Comment by geoaxis** [comment]
This is a hack but seems to work for me ``` @PreAuthorize("principal.claims['roles'][0] == 'MyApplicationRole'")```

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
