### ISSUE TITLE
com.microsoft.azure.servicebus.primitives.ServiceBusException: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by mcnealjwefx** [Microsoft/azure-spring-boot#243]
Trying to publish to a  topic in Azure service bus.  Using Spring Boot
	compile('com.microsoft.azure:azure-spring-boot')
	compile('com.microsoft.azure:azure-servicebus-spring-boot-starter')
azureVersion = '0.2.1'

application.properties
azure.servicebus.connection-string=Endpoint=sb://XXXX.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=XXXXXXXXX
azure.servicebus.topic-name=applicationlogs

Getting com.microsoft.azure.servicebus.primitives.ServiceBusException: java.lang.IllegalArgumentException, when trying to  autowire the topicClient

@Autowired
	private TopicClient topicClient;

Any suggestions ?  I tried to follow the examples straight from the examples. 

Thanks

**Comment by yungez** [comment]
@mcnealjwefx thanks for reporting the issue. I failed to reproduce the issue with similar configuration. Could you pls retry with latest 0.2.3 release. If the issue still exists, could you pls share code snippets for investigation? thanks in advance.

**Comment by danilina-wsib** [comment]
See: https://issues.apache.org/jira/browse/PROTON-1275
