### ISSUE TITLE
Constants has a reference to a SNAPSHOT dependency

### ISSUE THREAD

**Issue by snicoll** [Microsoft/azure-spring-boot#258]
This [constant in `Constants`](https://github.com/Microsoft/azure-spring-boot/blob/6fac67e7ea1861165b9e2ae2981d5de73e1d91f2/azure-spring-boot/src/main/java/com/microsoft/azure/keyvault/spring/Constants.java#L11) looks highly suspicious.

**Comment by sophiaso** [comment]
Fixed in #265 #263
