### ISSUE TITLE
An access to snapshots repository

### ISSUE THREAD

**Issue by sshogunn** [microsoft/azure-spring-boot#264]
Greetings,

Where can I find a link to the repository used for snapshot versions? I need to have `com.microsoft.azure:azure-spring-boot-bom:0.2.0-SNAPSHOT` used as a transitive dependency of a version build in jitpack.io based on one of the open pull-requests.

Could you please give a link if it is possible

**Comment by sophiaso** [comment]
Hi @sshogunn Thank you for asking. Currently there is no SNAPSHOT link support, could you share the detailed reason why you need a SNAPSHOT version as your transitive dependency? As SNAPSHOT can be very unstable. For the feature you wanted in the open pull requests, we have recently release a `0.2.2` version, could you try a `0.2.2` version first?

**Comment by yungez** [comment]
@sshogunn  another option is try to build from root dir of source code with `mvn install`, then you'll get snapshot version.
