### ISSUE TITLE
AADAuthenticationFilterAutoConfiguration should use dashed notation for `@ConditionalOnProperty`

### ISSUE THREAD

**Issue by snicoll** [Microsoft/azure-spring-boot#281]
As defined by the Javadoc of `@ConditionalOnProperty`, `client-id` and `client-secret`  [should use the dashed notation](https://github.com/spring-projects/spring-boot/blob/1c27a8e6e271a86c8600fcfa2b1f221e9023efe9/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/ConditionalOnProperty.java#L105).

**Comment by Incarnation-p-lee** [comment]
Fixed by #285 .
