### ISSUE TITLE
Please do not add `version` in child pom

### ISSUE THREAD

**Issue by snicoll** [Microsoft/azure-spring-boot#283]
Dependencies version must be in a `dependencyManagement` section. Please move [the version for `org.json`](https://github.com/Microsoft/azure-spring-boot/blob/15fd8fd60efe6256999fce48714f3c5a5537c31b/azure-spring-boot/pom.xml#L36) to `azure-spring-parent`

**Comment by sophiaso** [comment]
@snicoll Resolved in #284
