### ISSUE TITLE
Active Directory Spring Boot Sample

### ISSUE THREAD

**Issue by BradleyLyons** [Microsoft/azure-spring-boot#288]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  
- OS Type: Windows
- Java version: 
  
  - 1.8  

## Summary

When running the Azure Active Directory Spring Boot Sample I receive an authentication exception after logging in. 
`Caused by: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS240002: Input id_token cannot be used as 'urn:ietf:params:oauth:grant-type:jwt-bearer' grant.\r\nTrace ID: ########\r\nCorrelation ID: ######\r\nTimestamp: 2018-03-05 14:41:48Z","error":"invalid_request"}
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:120) ~[adal4j-1.3.0.jar:1.3.0]
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:880) ~[adal4j-1.3.0.jar:1.3.0]
	at com.microsoft.aad.adal4j.AuthenticationContext.access$100(AuthenticationContext.java:68) ~[adal4j-1.3.0.jar:1.3.0]
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:176) ~[adal4j-1.3.0.jar:1.3.0]
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:165) ~[adal4j-1.3.0.jar:1.3.0]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_121]
	... 1 common frames omitted`

## Reproduce steps

Run the sample application and log in.

## Expected Results

Being able to log in and use the sample application

## Actual Results

Sample application did not respond to inputs.

I was having issues trying to setup the Azure AD for a spring boot API application and though running the sample application would help, but I am unable to use the sample application either.  

This is using Spring Boot 2.0 and the master branch of the azure repository.

**Comment by yungez** [comment]
@BradleyLyons  thanks for reporting the issue. We just tested the sample again to make sure it works. From the error code, https://github.com/AzureAD/azure-activedirectory-library-for-java/issues/136 discussion in this thread mentioned that the client used must be a public client not credential client. could you pls share steps how your client was created to help investigation? thanks.

**Comment by BradleyLyons** [comment]
@yungez Thank you for the response.  Reading through that maybe I misunderstood how client registration works.  My app is registered as a Web App /API.  
In order to work with this sample it must be registered as a Native App, if I'm understanding you're linked thread correctly.  
If that's the case then I'll look into converting my app to try it out and I apologize for opening an issue that is unrelated to this code base.  
Thanks again!

**Comment by yungez** [comment]
@BradleyLyons  thanks for sharing the info. You can follow steps `Register the Application in Azure AD` in [this document](https://github.com/Microsoft/azure-spring-boot/blob/master/azure-spring-boot-starters/azure-active-directory-spring-boot-starter/README.md) to register application in Azure AD. Registered it as Web App/API is ok. Then grant necessary permission to the client. 

Please also update the sample 
- application.properties
- app.js

**Comment by BradleyLyons** [comment]
@yungez I have gotten the sample application working now.  Thank you!

**Comment by rmerrill68** [comment]
@BradleyLyons I am running into the same exception and have followed the document to register the application...  I was wondering what steps you took to resolve the exception?

**Comment by riveragluis** [comment]
@BradleyLyons can you provide an overview about solution? 
Perhaps some specific permissions?
I'm running on the same error with the springboot  starter. I'm using spring boot 2.0.1.RELEASE 
Regards

**Comment by jason279** [comment]
@BradleyLyons some to the exception, and I think it's not related to regestied application permissions as I assigned all the permissions to it and still get the exception. By the way, when I click Login on the index.html, it redirect to the azure ad to login and after that it redirect to the todoitem page, but with the exception, and the Login button changed to Logout. No matter which link I click, the server will report the ""error_description":"AADSTS240002: Input id_token cannot be used as 'urn:ietf:params:oauth:grant-type:jwt-bearer' grant..." exception. 
Could you give more information how you run the sample application well?

**Comment by walunjsachin** [comment]
I am facing same error, my all existing application works fine but ones created in last few weeks are giving this error when trying to acquire Oauth-on-behalf of token.
I do not see any difference in manifest file and permission, all application were created using portal only.   
I just see difference in  token values (after login using ADAL.js), like 
1) missing aio claim - This is returned for my older application 
2) additional header in token (alg)    - This is not returned for my older application. 

Not sure if this is causing token to be invalid when trying to acquire token passing it in User assertion.
Also there is literally no documentation to help about AIO claim.

All applications are Web App/ Api.  
Any pointers\suggestion?

**Comment by sophiaso** [comment]
Hi @jason279 and @walunjsachin, thank you reporting issue here, could you please check whether it's related with this issue https://github.com/MicrosoftDocs/azure-docs/issues/8121#issuecomment-386829397 ?

And there is a solution in that issue, please have a try and see if it fixes your problem, thanks.

*"This was a change in AAD behavior that we missed, but will go into a future release. In the meantime, the workaround is to set the field oauth2AllowImplicitFlow in the Application Manifest to true."*

**Comment by walunjsachin** [comment]
It is same error in that issue, but my application registration already have oauth2AllowImplicitFlow true.

**Comment by psieniawski** [comment]
I'm facing the same problem. Permissions granted to the application and _oauth2AllowImplicitFlow_ is set to true.
Any update on the issue?

**Comment by psieniawski** [comment]
Logging out and logging in after changes to _oauth2AllowImplicitFlow_  solved the problem.

**Comment by Fantom0x00F** [comment]
Maybe it'll help someone. I've faced with the same problem. It gone when i removed all wildcards in reply urls for registered in Active Directory application.

**Comment by rama84** [comment]
Hi,

- oauth2AllowImplicitFlow: true
- no wildcards in reply url (http://localhost:8080/login/oauth2/code/azure)
- spring-boot-starter-parent: 2.0.3.RELEASE
- azure-active-directory-spring-boot-starter: 2.0.4

```
2018-11-21 13:58:22.342 ERROR 24068 --- [pool-1-thread-1] c.m.aad.adal4j.AuthenticationContext     : [Correlation ID: ee0f00f6-c593-433e-9c49-5c95aadfeed5] Request to acquire token failed.

com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS240002: Input id_token cannot be used as 'urn:ietf:params:oauth:grant-type:jwt-bearer' grant.\r\nTrace ID: b08981a6-7a83-4ae9-9238-2a0fb34a3700\r\nCorrelation ID: ee0f00f6-c593-433e-9c49-5c95aadfeed5\r\nTimestamp: 2018-11-21 12:58:22Z","error":"invalid_request"}
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:120) ~[adal4j-1.3.0.jar:1.3.0]
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:880) ~[adal4j-1.3.0.jar:1.3.0]
	at com.microsoft.aad.adal4j.AuthenticationContext.access$100(AuthenticationContext.java:68) ~[adal4j-1.3.0.jar:1.3.0]
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:176) [adal4j-1.3.0.jar:1.3.0]
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:165) [adal4j-1.3.0.jar:1.3.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

```

**Comment by nsarangmsft** [comment]
any solution for this issue

**Comment by msaranga** [comment]
I'm also facing same problem any solution ?

**Comment by dhulme** [comment]
It was the wildcards in URL that were causing the issue for me :)

**Comment by Incarnation-p-lee** [comment]
@dhulme 
Thanks, it that related to #559 ?

**Comment by dhulme** [comment]
@Incarnation-p-lee I don't think so, I was getting same as error as these guys but in a React/Node stack

**Comment by Incarnation-p-lee** [comment]
@dhulme 
Could you please share the version of your env ? like this repo version, spring boot version.

**Comment by dhulme** [comment]
@Incarnation-p-lee I'm not using this repository, I was just receiving the same auth error

**Comment by Incarnation-p-lee** [comment]
@dhulme 
That sounds like the issue of AAD sdk, right ?

**Comment by latifkhan** [comment]
Does this https://github.com/Microsoft/azure-spring-boot/issues/559#issuecomment-460351470 solved ?
Im still facing same error:
com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS240002: Input id_token cannot be used as 'urn:ietf:params:oauth:grant-type:jwt-bearer' grant.\r\nTrace ID: 309f822c-e044-4b82-b572-ss152dbd5300\r\nCorrelation ID: 2132d60e-9d02-49c3-3-08f1aadfeed5\r\nTimestamp: 2019-02-22 02:10:00Z","error":"invalid_request"}

**Comment by berndgoetz** [comment]
> 
> 
> @yungez I have gotten the sample application working now. Thank you!

Hi yungez, Hi all, for the records: I've played around with the application registration configuration and I found that setting the "oauth2AllowIdTokenImplicitFlow" attribute to true make the whole difference. If you were wondering how to fix it.

**Comment by KrKandula** [comment]
Hey Guys, If you are getting this error even after setting the 'oauth2AllowIdTokenImplicitFlow' to true, Make sure you clean up the Redirect URLs to NOT have any wildcard character *. If you created your app in the past using the legacy App Registration, it allowed you to create URLs to have wildcards in them. Now, using the new App Registration screen, it won't even allow you to create URLs with wildcards. Good Luck !!

**Comment by hafarey** [comment]
To reconfirm what others have said, I too resolved the issue by setting:

```
    "oauth2AllowIdTokenImplicitFlow": true,
    "oauth2AllowImplicitFlow": true,
```

In case this also matters, I have only one redirect URI:
```
http://localhost:8080/login/oauth2/code/azure
```
and under _Implicit Grant_, both _Access Tokens_ and _ID tokens_ are checked.

**Comment by ankitsalu** [comment]
My reply URL specified in azure is https://Sales/PricingSearch

and i want to load the page from some other application like https://Sales/PricingSearch?price=10

If i am logged in, it validates this reply url i.e. https://Sales/PricingSearch?price=10, and let me use the application.
but in case I am not logged in, then instead of giving an option to login, i get the error reply url invalid.

Also, Azure is recently upgraded and now its not allowing to me to use wildcard in reply URL. 

Please suggest?

**Comment by blacelle** [comment]
To fix this, I had to switch not `oauth2AllowImplicitFlow` but `oauth2AllowIdTokenImplicitFlow` to true

	"oauth2AllowIdTokenImplicitFlow": true,
	"oauth2AllowImplicitFlow": false,

**Comment by mavortius** [comment]
Setting "oauth2AllowIdTokenImplicitFlow": true, and "oauth2AllowImplicitFlow": false, works for me, but after that I have some version conflict issues. To solve that, I downgraded "azure-active-directory-spring-boot-starter" to 2.2.5 and "spring-boot-starter-parent" to 2.2.8.RELEASE. That combination works for me.
