### ISSUE TITLE
Remove compile warnings for building.

### ISSUE THREAD

**Issue by Incarnation-p-lee** [microsoft/azure-spring-boot#293]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  - documentdb spring boot starter
  - key vault spring boot starter
  - media services spring boot starter
  - service bus spring boot starter
  - storage spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  
  - 1.9
  - 1.8
  - 1.7

**Comment by saragluna** [comment]
This issue is resolved after we migrated to azure-sdk-for-java repo since the build will fail on warnings now.
