### ISSUE TITLE
Update AAD Spring Boot Starter documentation

### ISSUE THREAD

**Issue by sophiaso** [microsoft/azure-spring-boot#298]
## Environment
- Spring boot starter:
  - active directory spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  - 1.9
  - 1.8
  - 1.7
  

## Summary
Secondly, the diagram for the on-behalf-of legs is not accurate. The on-behalf-of token request and response should be going to Azure AD and not the AAD Graph API. Please see this article about the On-behalf-of flow which has a diagram illustrating the flow.  

This is a minor doc feedback. The instructions on the blog do not clearly provide instructions to set the ClientID and tenant in the app.js file. Although the sample Readme does.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
