### ISSUE TITLE
Error packaging code after storing Service Bus properties in Azure vault -Consider revisiting the conditions above or defining a bean of type 'com.microsoft.azure.servicebus.QueueClient' in your configuration.

### ISSUE THREAD

**Issue by awsazuser** [microsoft/azure-spring-boot#302]
Getting errors when packaging spring boot app (mvn clean package) after creating secrets for service bus properties and accessing it using "azure.keyvault" spring boot application.properties

azure-servicebus-connection-string=Endpoint=sb://XXXXXXXXXX.servicebus.windows.net;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
azure-servicebus-queue-name=empq
azure-servicebus-queue-receive-mode=peeklock

application.properties:
azure.keyvault.uri=https://webappsxxx.vault.azure.net/
azure.keyvault.client-id=XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX
azure.keyvault.client-key=XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX

***************************
APPLICATION FAILED TO START
***************************

Description:

Field queueClient in com.example.demo.EmpRepositoryController required a bean of type 'com.microsoft.azure.servicebus.QueueClient' that could not be found.
	- Bean method 'queueClient' not loaded because @ConditionalOnProperty (azure.servicebus.connection-string) did not find property 'connection-string'

Action:

Consider revisiting the conditions above or defining a bean of type 'com.microsoft.azure.servicebus.QueueClient' in your configuration.

**Comment by sophiaso** [comment]
@awsazuser According to the description you shared, seems you have defined a `EmpRepositoryController`, have you run the [service bus  sample application](https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-servicebus-spring-boot-sample)?

`Bean method 'queueClient' not loaded because @conditionalonproperty (azure.servicebus.connection-string) did not find property 'connection-string'`
Is the `connection-string` property correctly configured?

**Comment by awsazuser** [comment]
I am getting these errors only when i create entries for the following properties in Azure vault and package the code ( mvn clean package)

If put the following properties in application.properties , I am able to package the code and access the queues in service bus with out any issues.

azure.servicebus.connection-string=Endpoint=sb://XXXXXX.servicebus.windows.net;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
azure.servicebus.queue-name=empq
azure.servicebus.queue-receive-mode=peeklock

**Comment by sophiaso** [comment]
Wonder if you need to inject `com.microsoft.azure.servicebus.QueueClient` in your application, the servicebus configuration must exist. [Refer to source code](https://github.com/Microsoft/azure-spring-boot/blob/master/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/servicebus/ServiceBusAutoConfiguration.java#L35)

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
