### ISSUE TITLE
Use key vault along with cloud config

### ISSUE THREAD

**Issue by sabareeshkkanan** [microsoft/azure-spring-boot#303]
I would like to store all the credentials in the vault and access it through spring cloud config rather accessing it directly . Is this possible now ?

**Comment by sophiaso** [comment]
@sabareeshkkanan Thanks for filing issue. Could you give more detailed explanation about your scenario, e.g., your expected example spring cloud config properties configuration and how you want to access the property from your application.

For a similar scenario, there is an existing [keyvault sample project](https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-keyvault-secrets-spring-boot-sample), you can [get keyvault property secrets as property](https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-keyvault-secrets-spring-boot-sample#get-key-vault-secret-value-as-property) in the application.

**Comment by sabareeshkkanan** [comment]
We are using spring cloud config service which is a standalone service which uses git as a backend, we are looking for other alternatives instead. Spring cloud config can use vault as backend please refer here https://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.1.0.RELEASE/multi/multi__spring_cloud_config_server.html#vault-backend  but not sure it will work with Azure vault ?

**Comment by srempfer** [comment]
Currently I working on a project that maybe fits for your scenario: https://github.com/srempfer/spring-cloud-config-azure-keyvault

**Comment by srempfer** [comment]
I released the first version and it's available on maven central: https://search.maven.org/artifact/io.github.srempfer/spring-cloud-config-azure-keyvault-starter

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
