### ISSUE TITLE
Multiple Topic Name

### ISSUE THREAD

**Issue by tamilselvan-mp** [microsoft/azure-spring-boot#305]
How to create multiple Topic clients in single class.

If I autowire topic client and it takes topic name from application.properties. but how can I use multiple topics & multiple subscriptions

## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  - documentdb spring boot starter
  - key vault spring boot starter
  - media services spring boot starter
  - service bus spring boot starter
  - storage spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  
  - 1.9
  - 1.8
  - 1.7

**Comment by anghour** [comment]
Help please !. I have the same need but with queues

**Comment by GauravWable** [comment]
Help !! I have same requirement where my topic for send message is different and subscription is different.
Send:
Topic to send message: sendTopic
**azure.servicebus.topic-name=sendTopic**

Receive:
Topic to receive message: receiveTopic
**azure.servicebus.topic-name=receiveTopic
azure.servicebus.subscription-name=receiveTopicSubscription**

**Comment by warrenzhu25** [comment]
I suggest you try to our new starter in Spring Cloud Azure. You can follow https://github.com/Microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples/spring-cloud-azure-servicebus-operation-sample. Any questions let me know.
