### ISSUE TITLE
Event Hub Support & Sample 

### ISSUE THREAD

**Issue by vnicers** [Microsoft/azure-spring-boot#311]

**Comment by sophiaso** [comment]
@vnicers @vinceve you can try the event hub support for Spring Cloud in repository [Spring Cloud Azure](https://github.com/Microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples/spring-cloud-azure-eventhub-sample).

**Comment by xscript** [comment]
@vnicers We will close this issue for now as you can find the event hub support in [Spring Cloud Azure](https://github.com/Microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples/spring-cloud-azure-eventhub-sample) repo.
