### ISSUE TITLE
The versions of latest libraries and dependencies are not clear.

### ISSUE THREAD

**Issue by yggd** [Microsoft/azure-spring-boot#320]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  - documentdb spring boot starter
  - key vault spring boot starter
  - media services spring boot starter
  - service bus spring boot starter
  - storage spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  
  - 1.9
  - 1.8

## Summary

Reporting the dependent version in this [wiki page](https://github.com/Microsoft/azure-spring-boot/wiki/Spring-Boot-dependency-version-management) , the latest version and dependencies of azure-spring-boot is unclear.
And current, latest version in Spring Initializr is not consistent with [Releases](https://github.com/Microsoft/azure-spring-boot/releases) and [Maven Central](https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22azure-spring-boot-starter%22).

## Reproduce steps
N/A

## Expected Results

I want to know latest release version, and dependency libraries like [Spring IO Platform](https://docs.spring.io/platform/docs/Brussels-SR5/reference/htmlsingle/#appendix-dependency-versions).

## Actual Results
N/A

**Comment by sophiaso** [comment]
Hi @yggd, thanks for opening issue. We are not managing the detailed dependencies version on wiki, could you refer to the detailed dependency with `mvn dependency:tree` or mvn repository for details [azure-spring-boot-bom/2.0.1](https://mvnrepository.com/artifact/com.microsoft.azure/azure-spring-boot-bom/2.0.1), [azure-spring-boot-starter/2.0.1](https://mvnrepository.com/artifact/com.microsoft.azure/azure-spring-boot-starter/2.0.1), [azure-spring-boot/2.0.1](https://mvnrepository.com/artifact/com.microsoft.azure/azure-spring-boot/2.0.1) etc. for detailed dependency list?

>And current, latest version in Spring Initializr is not consistent with Releases and Maven Central.
Currently not each version released will be updated to Spring Initializr.

**Comment by yggd** [comment]
@sophiaso 

All right. Thank you for your support.
