### ISSUE TITLE
Azure AD implementation not compatible with session sharing due to missing Serializable

### ISSUE THREAD

**Issue by chrisgahlert** [Microsoft/azure-spring-boot#321]
## Environment
- Spring boot starter:
  - active directory spring boot starter
  
## Summary
After validating the Bearer token in `AADAuthenticationFilter`, a new `UserPrincipal` object is created and saved to the session.

As the `UserPrincipal` class is not implementing the `Serializable` interface. It also doesn't support being serialized and deserialized to/from JSON, as the __JSON Web Key__ classes don't support this.

For this reason, it is impossible to enable session sharing between multiple application instances (e.g. via spring-session).

## Solution
Either have the `UserPrincipal` class implement the `Serializable` interface or don't persist this object in the session. Instead one could persist the properties needed (Id, Claims, Groups, ...) to create the `UserPrincipal` inside the `AADAuthenticationFilter`.

**Comment by mapster** [comment]
Can we expect this to be fixed anytime soon?

**Comment by sophiaso** [comment]
A new version [2.0.7](https://github.com/Microsoft/azure-spring-boot/releases/tag/2.0.7) has been released to support serializable UserPrincipal. Close issue.
