### ISSUE TITLE
branch 0.1.x is out of sync to contains latest feature/bug fixing

### ISSUE THREAD

**Issue by yungezz** [Microsoft/azure-spring-boot#327]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  - documentdb spring boot starter
  - key vault spring boot starter
  - media services spring boot starter
  - service bus spring boot starter
  - storage spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  
  - 1.9
  - 1.8
  - 1.7
  

## Summary

when cherrying pick some commit from master branch to 0.1.x branch, found that lots of bug fixing/new features has not been cherry picked to 0.1.x branch. those 2 branches are out of sync. more important is, 0.1.x release is still majority usage because sb 2.0 released just one month ago, and normally framework updating is a long-tail trend.

Please maintain 0.1.x branch as main release point.

**Comment by rajadilipkolli** [comment]
@yungezz  One way to handle is initially committing to 0.1.x branch and then pushing the same to 2.0.x branch so that both will be in sync.
