### ISSUE TITLE
Send logs to table storage with storage spring boot starter

### ISSUE THREAD

**Issue by freedumb** [microsoft/azure-spring-boot#334]
## Environment
- Spring boot starter:
  - storage spring boot starter
  
- OS Type: MacOS
- Java version: 
  - 1.8

## Summary
More of a feature request/inquiry.  Is it possible send application logs to azure table storage with the storage spring boot starter in conjunction with something like log4j, logback, slf4j, with a simple  setting in application.properties and a small update to the logger configuration?  This would be similar to how you can easily send logs to application insights.

**Comment by Incarnation-p-lee** [comment]
@freedumb 
thanks for your issue. You want to send some logs to azure cosmosdb from table API, am I understand that right?

**Comment by freedumb** [comment]
The old table storage, not necessarily cosmos db table API.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
