### ISSUE TITLE
Storage starter thread safety

### ISSUE THREAD

**Issue by matyee** [microsoft/azure-spring-boot#351]
Sorry in advance if this has already been answered. I could not find a definitive answer. I am wondering how I should use the storage starter to be thread safe. I assume the ```CloudStorageAccount``` is thread safe. But can I also create a client, for example a ```CloudBlobClient``` and share that between threads? Or should every thread create its own client for every request?

**Comment by matyee** [comment]
Also, does it use connection pooling? I am using it form App Service where the number of outgoing connections are limited. Can I somehow control how many outgoing connections the application will use?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
