### ISSUE TITLE
Use Microsoft graph API instead of Azure Active Directory Graph

### ISSUE THREAD

**Issue by sophiaso** [microsoft/azure-spring-boot#355]
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-graph-api

*We strongly recommend that you use Microsoft Graph instead of Azure AD Graph API to access Azure Active Directory resources. Our development efforts are now concentrated on Microsoft Graph and no further enhancements are planned for Azure AD Graph API. There are a very limited number of scenarios for which Azure AD Graph API might still be appropriate; for more information, see the Microsoft Graph or the Azure AD Graph blog post in the Office Dev Center.*

## Environment
- Spring boot starter:
  - active directory spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  - 1.9
  - 1.8
  - 1.7
  

## Summary
Azure AD Graph API will no longer be enhanced.

**Comment by ptirador** [comment]
I support this idea. I need Microsoft Graph API to [create an invitation](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/invitation_post), and it's impossible to do it with the older API.

**Comment by ganeshchippada** [comment]
Any plans in near future to change Azure AD Graph API to Microsoft graph?

**Comment by stromvap** [comment]
Whats the overall plan for supporting MS Graph? The current AAD Graph is deprecated and Microsoft is **strongly** recommending developers to use MS Graph.

Here is a blog post (posted February 20 2019) with the strong recommendation: https://developer.microsoft.com/en-us/office/blogs/microsoft-graph-or-azure-ad-graph/

Overriding the ServiceEndpoint properties is a good step on the way but it's still not enough.

**Comment by jakobli** [comment]
Any update on this, AAD graph is getting deprecated so it feels a bit urgent :)

**Comment by sophiaso** [comment]
@jakobli we have a new contributed pull request for this issue. #680

**Comment by saragluna** [comment]
Closing this now.
