### ISSUE TITLE
AAD: Spring does not validate Bearer token after first request.

### ISSUE THREAD

**Issue by kieykouch** [Microsoft/azure-spring-boot#361]
## Environment
- Spring boot starter:
  - active directory spring boot starter version: 2.0.2
- OS Type: MacOS
- Java version: 
  - 1.8  
## Summary

I am trying to configure AAD to my Spring endpoints. I followed all the steps in the single page app sample (https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-active-directory-spring-boot-sample). It works correctly for the first request but not the subsequent requests. 
After an authorized request, any other requests do not validate the bearer token. 

I modified my Azure Web app / API manifest: `oauth2AllowImplicitFlow: true`, then, delegated permissions for `Access the directory as the signed-in user` and `Sign in and read user profile`, then my admin granted permission.

My Java WebSecurityConfig
```java
@Configuration
@EnableGlobalMethodSecurity(securedEnabled = true, prePostEnabled = true)
@EnableWebSecurity
public class WebSecurityConfigAdapter extends WebSecurityConfigurerAdapter {

  private final AADAuthenticationFilter aadAuthFilter;

  @Autowired
  public WebSecurityConfigAdapter(final AADAuthenticationFilter aadAuthFilter) {
    this.aadAuthFilter = aadAuthFilter;
  }

  /**
   * Configures HTTP to use Azure Active Directory for authentication and enable CORS.
   */
  @Override
  protected void configure(HttpSecurity http) throws Exception {
    http
        .addFilterBefore(aadAuthFilter, UsernamePasswordAuthenticationFilter.class)
        .csrf().disable()
        .cors()
        .and()
        .authorizeRequests()
        .anyRequest().authenticated()
        .and()
        .httpBasic();
  }
}
```
Gradle
```text
compile ("com.microsoft.azure:azure-active-directory-spring-boot-starter:2.0.2")
compile ("org.springframework.boot:spring-boot-starter-security:2.0.2.RELEASE")
```

## Reproduce steps

...

## Expected Results

Verify the bearer token for every request.

## Actual Results

Bypass authentication after the authorized request.

**Comment by kieykouch** [comment]
@sophiaso can you help me with this?

**Comment by sophiaso** [comment]
Hi @kieykouch, do you mean the AAD Filter is now verifying the bearer token for every request, and you expect it should not  verify once authenticated?

**Comment by kieykouch** [comment]
I found my mistake. I was using Postman earlier, so on every request, Spring will cache a validate request cookie. I just added this session management.
```java 
http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS);
```

**Comment by ateeqsayed** [comment]
Adding http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS); still caching the token.

**Comment by kieykouch** [comment]
@ateeqsayed Trying verified with curl.

**Comment by ateeqsayed** [comment]
Thank you @kieykouch . I got it fixed by using server.servlet.session.cookie.max-age=0 in tha application.properties file.
