### ISSUE TITLE
Unable to logout from spring boot

### ISSUE THREAD

**Issue by michel404** [Microsoft/azure-spring-boot#364]
## Environment
- Spring boot starter: active directory spring boot starter
- OS Type: Linux
- Java version:  1.8

## Summary
When I run the **azure active directory spring boot sample**, I can use it to log in, but logging out doesn't seem to work. The front end may _say_ it is logged out, but the protected resource from the spring boot backend is still available. I think a proper backend should respect logging out, and respond to subsequent requests to protected data with http status 401 (or 403).

So I believe this to be a bug. If this is intended behavior of this sample, can someone point me to a resource that explains how to properly secure the back end?

## Reproduce steps
- clone the repo
- modify `azure-spring-boot/azure-spring-boot-samples/azure-active-directory-spring-boot-sample/src/main/resources/application.properties`
  - add client id
  - add client secret
- modify `azure-spring-boot/azure-spring-boot-samples/azure-active-directory-spring-boot-sample/src/main/resources/static/App/Scripts/app.js`
  - add tenant
  - add client id
- Go to Azure portal, Azure Active Directory, App registrations, the application, Manifest and set `oauth2AllowImplicitFlow` to `true`, as described in [this issue](https://github.com/MicrosoftDocs/azure-docs/issues/8121#issuecomment-387090099).
- `cd azure-spring-boot-samples/azure-active-directory-spring-boot-sample`
- run `mvn spring-boot:run`
- In a fresh browser:
  - go to `http://localhost:8080/api/todolist` and verify that the protected resource is not available (Access Denied)
  - go to `http://localhost:8080/#/Home` and verify that you are not yet logged in
  - click 'Login' and follow Azure's login procedure
  - once back at `http://localhost:8080/#/Home`, verify that you are logged in
  - go to `http://localhost:8080/api/todolist` and verify that the protected resource is available now
  - click 'Logout' in order to logout
  - go to `http://localhost:8080/api/todolist`

## Expected Results
The protected resource should not be available anymore. It should return Access Denied with http status 401 or 403.

## Actual Results
Even though we are logged out, the protected resource is still available. We receive the json with http status 200.

(Edit: fix typo in maven command in reproduction steps)

**Comment by sophiaso** [comment]
@michel404 Could you please try this sample? https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-active-directory-spring-boot-backend-sample

Authentication is redirected by backend, thanks.

**Comment by michel404** [comment]
@sophiaso I have not tried the sample you linked to. I did figure out what was I missing though :smile:

For anyone wondering and struggling with the same issue, here is what helped me out:

The ability for logging out is not configured in the `WebSecurityConfig` class. As described in [the first part of this stackoverflow answer](https://stackoverflow.com/a/36562183), one should add something like this, in the `configure` method:
```java
http.logout()
    .logoutRequestMatcher(new AntPathRequestMatcher("/logout"))
    .logoutSuccessUrl("/logout.done")
    .deleteCookies("JSESSIONID")
    .invalidateHttpSession(true);
```

You should also instruct Azure to forward to '/logout' after a successful logout, by adding a `postlogoutRedirectUri` item in de adal config object in `app.js`.

Even though I understand now what I was missing, I still regard this as a bug in the sample, and suggest to keep this issue open until it is fixed.

**Comment by sophiaso** [comment]
Hi @michel404, glad you have solved the problem, agree with that the angular sample does not send logout to the backend. Do you have any interest in opening a PR to fix the sample?

**Comment by michel404** [comment]
Sure!

**Comment by sophiaso** [comment]
@michel404 Thank you for your contribution.
