### ISSUE TITLE
UserGroups limited to 100

### ISSUE THREAD

**Issue by martyncrow** [microsoft/azure-spring-boot#388]
## Environment
- Spring boot starter:
  - active directory spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  - 1.8
  

## Summary
When checking the user is a member of a specified UserGroup its limited to 100 groups, if the user belongs to more than 100 groups not all groups are returned

## Reproduce steps
UserPrincipal.userGroups is a maximum on 100 groups.

## Expected Results
UserPrincipal.userGroups is a maximum on 100 groups. I would expect to see all groups

## Actual Results
only 100 have been returned

**Comment by martyncrow** [comment]
Hi, yep it is due to the graph response be My pagination, I’ve found a work around by overriding the service endpoints and adding an extra query param $top=999

**Comment by marto** [comment]
I have come across this bug in our setup.

The issues is in `AzureADGraphClient#loadUserGroups` call. By default the graph API endpoint uses the `azure.service.endpoints.global.aadMembershipRestUri` property that is by default set to `https://graph.windows.net/me/memberOf?api-version=1.6`. The documentation (https://docs.microsoft.com/en-gb/previous-versions/azure/ad/graph/howto/azure-ad-graph-api-supported-queries-filters-and-paging-options) for this call talks about paging and by default it will only return 100 results. If you planning on using access control in Spring that is based on groups via the `@PreAuthorize` annotation and the group returned is not listed in the first 100 results, then you will get an access denied.

The work around is override the property (thanks @martyncrow) and add a `$top=999` query param. i.e:  `https://graph.windows.net/me/memberOf?api-version=1.6&$top=999`.

Paging has a legitimate use case, the code and `AzureADGraphClient#loadUserGroups` should be fixed to support paging or `azure-spring-boot/src/main/resources/serviceEndpoints.properties` amended to increase the limit by default.

It's a frustrating bug to have to come across and usually only happens in production when you have realistic users assigned to many groups.

**Comment by Incarnation-p-lee** [comment]
@marto
Thanks for your issue and contribution, could you please share some information why you may need groups more than 100 ?

**Comment by boukewoudstra** [comment]
I have encountered the same problem. For your application you typically only need a few roles, however a user might be member of a lot of roles in active directory. In my case, a user is member of 179 group memberships. The role detection fails when the required membership is after the first 100 groups.

The workaround updating the setting fixes the issue:
azure.service.endpoints.global.aadMembershipRestUri=https://graph.windows.net/me/memberOf?api-version=1.6&$top=999

Setting it to 179 would be enough for my particular usecase right now, but 999 seems to be high enough to cover most usecases I guess.

Perhaps this should be set to the default?

**Comment by jarekhr** [comment]
We've encountered same problem. Some users in our organization can have more than 300 groups assigned to them. 
We had to use a workaround listed above to deal with this. This needs urgent fixing (changing default page size should be sufficient, 999 is likely enough)

**Comment by zhoufenqin** [comment]
closing the issue, the issue has been solved. see https://github.com/Azure/azure-sdk-for-java/issues/14222
