### ISSUE TITLE
"Access the directory as the signed-in user" in azure-active-directory-spring-boot-starter

### ISSUE THREAD

**Issue by mdekhtiarenko** [microsoft/azure-spring-boot#389]
Could you please explain deeply what for `Access the directory as the signed-in user` permission is used in `azure-active-directory-spring-boot-starter` and if it's possible to make JWT authorization without it?

**Comment by markvr** [comment]
Any news on this from Microsoft?  Having to be an AAD admin to use makes this library of pretty limited use.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
