### ISSUE TITLE
Potential Dependency Hell with Application Insights SDK version Conflict

### ISSUE THREAD

**Issue by dhaval24** [Microsoft/azure-spring-boot#391]
## Summary
Azure-spring-boot-bom uses Application Insights core SDK version 1.0.9 (which is pretty outdated, the latest version is 2.1.2) and causes a dependency hell with user trying to use ApplicationInsights-SpringBoot-Starter (which relies on Application Insights core version 2.1.2). Please update the pom file to include the latest version of Application Insights SDK.

## Reproduce steps
Refer to https://github.com/Microsoft/ApplicationInsights-Java/issues/710

## Expected Results
Application should start normally with SpringBoot-bom and ApplicationInsights-SpringBoot-starter.

## Actual Results
Application crashes because of in-satisfied bean resolution. The bean is not present in the older version of Application Insights

**Comment by Incarnation-p-lee** [comment]
@dhaval24 
Thanks for your remider, we will update AI version soon.

**Comment by dhaval24** [comment]
@Incarnation-p-lee I think it would be also great if you can use https://coderelease.io It automatically helps you notify when a new library is released and hence avoid any manual updates from us.

**Comment by Incarnation-p-lee** [comment]
@dhaval24 
Thanks, it looks awesome! I will take a try right now.

**Comment by dhaval24** [comment]
@Incarnation-p-lee when is the release for this scheduled so that users can get this issue fixed on Application Insights side?

**Comment by dhaval24** [comment]
@Incarnation-p-lee  has the new release been made yet ? What would be a good way to stay in sync. The conflicts in dependency can be very irritating to customers! Have you already subscribed to coderelease.io ?
