### ISSUE TITLE
Feature request/question: MSI support

### ISSUE THREAD

**Issue by nickwalkmsft** [Microsoft/azure-spring-boot#396]
Are there any plans to include automatic detection and usage of Managed Service Identity on Azure VMs and App Service the way that the Microsoft.Azure.Services.AppAuthentication .NET package does, particularly for the Key Vault starter? [This tutorial](https://docs.microsoft.com/en-us/azure/key-vault/tutorial-web-application-keyvault) covers how it works.

MSI makes Key Vault *much* more compelling.

**Comment by nickwalkmsft** [comment]
It looks like usage of MSI credentials is already implemented [here](https://github.com/Azure/autorest-clientruntime-for-java/tree/master/azure-client-authentication/src/main/java/com/microsoft/azure/credentials). This seems like it would be great to integrate into the starter.

**Comment by simholte** [comment]
+1

**Comment by lenisha** [comment]
+1
for KeyVault and DataSource

**Comment by nickwalkmsft** [comment]
Candidate implementation in https://github.com/Microsoft/azure-spring-boot/pull/407.

**Comment by elhoo** [comment]
AFAIK, #407 seems to only include MSI on App services - not VMs? Would be really good to include support for VMs as well!
