### ISSUE TITLE
Can't access Key Vault with service principal having Client-Id and Certificate

### ISSUE THREAD

**Issue by Matthew-Dong** [Microsoft/azure-spring-boot#416]
Requirement: 
1. Store secrets in key vault such as database credentials etc through java application and ARM scripts
2. Read secrets from Key vault into JAVA based spring boot application using microsoft provided library "com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter:0.2.3"
 
Problem:
We are unable to find documentation to access Key Vault with service principal having Client-Id and Certificate.

**Comment by frxd0m** [comment]
Thanks for raising this feature request. I would like to highlight here that this is primarily for ADFS deployment of Azure Stack appliance.

**Comment by sophiaso** [comment]
Access keyvault with client-id and certificate is supported in pull request #474.
