### ISSUE TITLE
Commons Logging conflict

### ISSUE THREAD

**Issue by hc-codersatlas** [Microsoft/azure-spring-boot#423]
Hi, Azure Spring Boot Autoconfigure has a require dependency on commons logging, which has a conflict with other logging frameworks. can slf4j be used or simply to make the logging framework optional? The other libraries are fine except this 1.

Thanks.

**Comment by rburgst** [comment]
Actually its much worse. When adding this dependency to a spring boot 2 project then all normal logging does not work anymore.
I.e. `org.springframework.web` etc. no longer produces the logs.

**Comment by cfroment** [comment]
Hi,
Any idea when the fix will be officialy released (in 2.0.7, I guess) ?

**Comment by Prsna23** [comment]
I would like to work on this issue. Can you elaborate a little more on this?

**Comment by sophiaso** [comment]
@Prsna23 Thanks for offering help, one PR #429 has been merged for this issue, latest master branch should have fixed this issue, though more check is welcomed. Or looking into any other issue in this repo is also welcomed.

@cfroment 2.0.7 will be released within one or two weeks.

**Comment by Prsna23** [comment]
@sophiaso Oh, I thought the issue was still open. :) Then I will look into some other issue in this repo.

**Comment by sophiaso** [comment]
Version `2.0.7` has been released.
