### ISSUE TITLE
can i get the updated secret values as properties with out restarting the spring boot application

### ISSUE THREAD

**Issue by vishnu351** [microsoft/azure-spring-boot#447]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  - documentdb spring boot starter
  - key vault spring boot starter
  - media services spring boot starter
  - service bus spring boot starter
  - storage spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  
  - 1.9
  - 1.8
  - 1.7

**Comment by Incarnation-p-lee** [comment]
oh，no，sorry for typing 447 instead of 477.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
