### ISSUE TITLE
AD B2C - Signed JWT rejected: Another algorithm expected, or no matching key(s) found

### ISSUE THREAD

**Issue by tstaals** [Microsoft/azure-spring-boot#454]
## Environment
- Spring boot starter:
  - active directory spring boot starter

- OS Type: Windows/Linux/
- Java version: 
  - 1.8
  

## Summary
We are trying to  connect to Azure AD b2c with help of the https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-active-directory-spring-boot-sample 

We are getting the following error on calls to de spring boot backend

2018-11-01 10:46:07.704 ERROR 16712 --- [nio-8080-exec-2] c.m.a.s.a.aad.AADAuthenticationFilter    : Failed to initialize UserPrincipal.

com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found

Is Azure AD B2C supported?

**Comment by sophiaso** [comment]
@tstaals The AAD sample does not support Azure AD B2C. And we may support B2C in the future.

**Comment by xscript** [comment]
@tstaals AAD B2C support work is tracked at #464 . You can follow up from there.
Close this issue to avoid duplicate.
