### ISSUE TITLE
QueueClient resource leak

### ISSUE THREAD

**Issue by KevinJCross** [microsoft/azure-spring-boot#455]
## Summary
the Queue client bean in https://github.com/Microsoft/azure-spring-boot/blob/602c7698e13db27fafc25ea76b4ffe3d75c70315/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/servicebus/ServiceBusAutoConfiguration.java#L43
should have the  @Bean(destroyMethod = "close" ) to enable the graceful shutdown.

The bean does not close itself on destroy
Adding the close to the bean definition will prevent memory leaks and gracefull shutdown since finalizers are best effort and should not be relied upon to shut resources.

## Expected Results
Close should close the connection and on application or context shutdown the bean close should be called to close the connection

## Actual Results
Currently the finaliser is used to close the connection this is inappropriate for resources in a JVM

**Comment by sophiaso** [comment]
Hi @KevinJCross, thanks for reporting issue, according to [@Bean Javadoc](https://github.com/spring-projects/spring-framework/blob/v5.0.7.RELEASE/spring-context/src/main/java/org/springframework/context/annotation/Bean.java#L272-L275), by default, a public and no-arg close method will be automatically inferred as destroy method, i.e., if the returned Bean has a `close()` method, `@Bean` is equal to `@Bean(destroyMethod = "close")`, so extra `destroyMethod` declaration is not necessary, could you share what's the memory leak issue you have met?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
