### ISSUE TITLE
Better name for azure-spring-boot-metrics-starter

### ISSUE THREAD

**Issue by xscript** [microsoft/azure-spring-boot#462]
The correct name should be `azure-metrics-spring-boot-starter`. Naming convention is defined at [here](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-auto-configuration.html#boot-features-custom-starter-naming).

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
