### ISSUE TITLE
Integration AAD B2C with spring security

### ISSUE THREAD

**Issue by Incarnation-p-lee** [microsoft/azure-spring-boot#464]
The feature implementation will be merge to one development branch [aad-b2c-integration](https://github.com/Microsoft/azure-spring-boot/tree/aad-b2c-integration).

Feature check list:
* OpenId
  * [x] Sign in/up/out
  * [x] Password reset
  * [x] Profile edit
  * [x] Forgot password (workaround for AAD B2C sign in page)
* Issues
  * [ ] Support both relative and absolute URL from configuration
  * [ ] Investigate the best practice when obtain JWT keyset
  * [x] #481 
* Investigate
  * [x] formLogin
  * [x] openidLogin
  * [ ] session stateless with JWT
     *  Normal way of jQuery or XMLHttpRequest with id_token need cors support, but b2c call it unsupported. [CORS in B2C](https://stackoverflow.com/questions/34200409/cors-issue-when-getting-a-token-in-azure-ad-b2c-implict-flow)
    * Need investigate other way when request to backend.

**Comment by Incarnation-p-lee** [comment]
current aad use fixed algorithm in jwt parser, not sure if may related to #454, may be double check that part.

**Comment by SteefB** [comment]
What is the current state of the integration? When can we expect to use B2C with spring security? Is there anything I can do to speed up the process? Thanks!

**Comment by Incarnation-p-lee** [comment]
@SteefB 
Thanks for reminding. We have [release milestone](https://search.maven.org/search?q=g:com.microsoft.azure%20AND%20a:azure-active-directory-b2c-spring-boot-starter) for this with spring boot 2.1.x.

You can follow the sample [here](https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-active-directory-b2c-oidc-spring-boot-sample).

**Comment by Incarnation-p-lee** [comment]
@SteefB 
Or you can leverage snapshot version.

```
<repositories>
  <repository>
    <id>nexus-snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
    <snapshots>
      <enabled>true</enabled>
      <updatePolicy>always</updatePolicy>
    </snapshots>
  </repository>
</repositories>
```

**Comment by SteefB** [comment]
@Incarnation-p-lee Thanks for the information! We'll check it out asap. 
Do you have estimation on when this will available in an official release? 
Thanks a lot!

**Comment by erviszyka** [comment]
Hello all,
Any ideas when this branch will be merged into master and be available in a official release?

Thanks

**Comment by Incarnation-p-lee** [comment]
we have milestone release [here](https://search.maven.org/artifact/com.microsoft.azure/azure-active-directory-b2c-spring-boot-starter/2.1.6.M2/jar).

**Comment by saragluna** [comment]
We have released 2.1.7, check it [here](https://search.maven.org/search?q=g:com.microsoft.azure%20AND%20a:azure-active-directory-b2c-spring-boot-starter).

**Comment by dan-alford** [comment]
Are there any plans to add the*.b2clogin.com domains to the list of acceptable token issuers?

**Comment by neuqlz** [comment]
@dan-alford Because I am gonna close this issue, could you open a new issue to propose this feature in it? We will add it to our backlog and discuss the priority in our sprint plan meeting.
