### ISSUE TITLE
Update Service Bus SDK to 2.0 and auto-configure ManagementClient

### ISSUE THREAD

**Issue by lekkalraja** [microsoft/azure-spring-boot#486]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  - documentdb spring boot starter
  - key vault spring boot starter
  - media services spring boot starter
  - service bus spring boot starter
  - storage spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  
  - 1.9
  - 1.8
  - 1.7

**Comment by lekkalraja** [comment]
@xscript i want to get the service bus queue metrics like active message count in the queue,  pending queue and etc...  By giving servicebus connection string and queue name...

**Comment by xscript** [comment]
The management functionality is not available in current Service Bus Java SDK (1.2.x). However the Service Bus SDK team is working on it and has released 2.0.x-Preview packages. You can find it at [here](https://github.com/Azure/azure-service-bus-java/releases/tag/2.0.0-PREVIEW-5). We will update our dependency to 2.0 once it has an official release version.

**Comment by bjconlan** [comment]
Just updating that this is still pending (with regards to autoconfiguration)

**Comment by xscript** [comment]
@jialindai the 2.0.0 SDK is already available at [here](https://github.com/Azure/azure-service-bus-java/releases/tag/2.0.0). Need to revisit this work item.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
