### ISSUE TITLE
maven fails to compile when done git clone

### ISSUE THREAD

**Issue by mkdirJava** [Microsoft/azure-spring-boot#491]
## Environment
- Spring boot starter:
   azure-spring-boot ( cannot do mvn clean install )
- OS Type: Linux ( Ubuntu 18 )
- Java version: 
  - 1.8
- Maven Version
- 3.5.2
  

## Summary
Followed the steps to build the project but fails:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project azure-spring-boot: Compilation failure: Compilation failure: 
[ERROR] /home/origin/development/workSpaces/eclipse_Oxygen/SpringBootAzure/azure-spring-boot/Azure2/azure-spring-boot/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/sqlserver/KeyVaultProperties.java:[13,24] cannot find symbol
[ERROR]   symbol:   class PostConstruct
[ERROR]   location: package javax.annotation
[ERROR] /home/origin/development/workSpaces/eclipse_Oxygen/SpringBootAzure/azure-spring-boot/Azure2/azure-spring-boot/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/sqlserver/KeyVaultProperties.java:[27,6] cannot find symbol
[ERROR]   symbol:   class PostConstruct
[ERROR]   location: class com.microsoft.azure.spring.autoconfigure.sqlserver.KeyVaultProperties
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :azure-spring-boot

## Reproduce steps
git clone https://github.com/mkdirJava/azure-spring-boot.git
cd azure-spring-boot
mvn clean install 

## Expected Results
Clean installation of the project

## Actual Results
Error 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project azure-spring-boot: Compilation failure: Compilation failure: 
[ERROR] /home/origin/development/workSpaces/eclipse_Oxygen/SpringBootAzure/azure-spring-boot/Azure2/azure-spring-boot/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/sqlserver/KeyVaultProperties.java:[13,24] cannot find symbol
[ERROR]   symbol:   class PostConstruct
[ERROR]   location: package javax.annotation
[ERROR] /home/origin/development/workSpaces/eclipse_Oxygen/SpringBootAzure/azure-spring-boot/Azure2/azure-spring-boot/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/sqlserver/KeyVaultProperties.java:[27,6] cannot find symbol
[ERROR]   symbol:   class PostConstruct
[ERROR]   location: class com.microsoft.azure.spring.autoconfigure.sqlserver.KeyVaultProperties
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :azure-spring-boot

**Comment by mkdirJava** [comment]
working through this I added a dependancy 
<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
    <version>1.2</version>
</dependency>
on 
<installation>/azure-spring-boot/azure-spring-boot/pom.xml

now it comes up with
[INFO] <<< findbugs-maven-plugin:3.0.5:check (default) < :findbugs @ azure-spring-boot <<<
[INFO] 
[INFO] 
[INFO] --- findbugs-maven-plugin:3.0.5:check (default) @ azure-spring-boot ---
[INFO] BugInstance size is 1
[INFO] Error size is 0
[INFO] Total bugs: 1
[INFO] Redundant nullcheck of inputStream, which is known to be non-null in com.microsoft.azure.keyvault.spring.certificate.PfxCertReader.read(Resource, String) [com.microsoft.azure.keyvault.spring.certificate.PfxCertReader, com.microsoft.azure.keyvault.spring.certificate.PfxCertReader] Redundant null check at PfxCertReader.java:[line 23]Another occurrence at PfxCertReader.java:[line 42] RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE
[INFO] 


To see bug detail using the Findbugs GUI, use the following command "mvn findbugs:gui"

**Comment by Incarnation-p-lee** [comment]
@mkdirJava 
Could you please provide more information about this build issue from master branch ? As we have CI/CD pipeline here, there should be no build issues.

**Comment by mkdirJava** [comment]
@Incarnation-p-lee 
This was a Local issue, was building using the Java 11 Javac and not java 8. corrected the issue. The instructions are good, Just to let others know;

Ubuntu 18.04
when you change JAVA_HOME
Maven looks like it has changed it 
mvn -version
however it is the javac -v that is of interest

had to repoint both to Java 8
