### ISSUE TITLE
Current AADAuthenticationFilter makes the application either stateful or slow

### ISSUE THREAD

**Issue by wlami** [microsoft/azure-spring-boot#494]
## Environment
- Spring boot starter:
  - active directory spring boot starter
  
- OS Type: Windows
- Java version: 
  - 1.8

## Summary
Current implementation of `com.microsoft.azure.spring.autoconfigure.aad.AADAuthenticationFilter` is either stateful or slow

## Reproduce steps
Follow the [AAD Spring Boot Sample](https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-active-directory-spring-boot-sample).

* Implement the AADAuthenticationFilter in your WebSecurityConfig:
```
    @Autowired
    private AADAuthenticationFilter aadAuthFilter;
    
    @Override
    protected void configure(HttpSecurity http) throws Exception {
    [...]
        http.anyRequest().hasRole("my_group_name")
    [...]
        http.addFilterBefore(aadAuthFilter, UsernamePasswordAuthenticationFilter.class);
    }
```
* Set your oauth properties `azure.activedirectory.client-id`, `azure.activedirectory.client-secret`, `azure.activedirectory.ActiveDirectoryGroups`
* Call one of your secured endpoints so that the `AADAuthenticationFilter ` kicks in.

## Expected Results
I would expect that my rest service is stateless as the id_token the SPA _could_ contain all relevant information and the cryptographic signature could be checked on each request without calling any third party systems.

## Actual Results
Short version: `AADAuthenticationFilter` uses the `HttpSession` to store information on the principal. 

Extended version: `AADAuthenticationFilter` tries to get the user principal from the HttpSession. If there is no user principal, the implementation parses the Bearer token which is JWT. It then queries the token endpoint to get an access_token for the graph-API and then calls the graph-API to get the groups the user is assigned. It then filters the assigned groups using the `azure.activedirectory.ActiveDirectoryGroups` property and assign these groups as roles using the `ROLE_` prefix. The resulting principal is then assigned to the HttpSession using the `CURRENT_USER_PRINCIPAL` session attribute.

Using the session is performance-wise a good solution, but it makes the application stateful. If I want to run multiple instances of my server, I either have to use sticky sessions, or some externalise the session using, e.g. Redis. 

If I disable sessions then I have to do the "complete flow" on each request. This complete "get-the-groups-of-the-user" flow takes 800ms-900ms for my tests. 

## Alternative solution
Instead of querying the Graph API I suggest using the `appRoles` feature that AAD provides. To do so, one has to add appRoles to the application registration manifest. 

E.g.:
manifest:
```
  "appRoles": [
    {
      "allowedMemberTypes": [
        "User",
        "Application"
      ],
      "displayName": "Full Access",
      "id": "2fa848d0-8054-4e11-8c73-7af5f1172219",
      "isEnabled": true,
      "description": "Full access - update / delete",
      "value": "FullAccess"
    },
    {
      "allowedMemberTypes": [
        "User"
      ],
      "displayName": "Read Only",
      "id": "f8ed78b5-fabc-488e-968b-baa48a57484b",
      "isEnabled": true,
      "description": "Read-only access to the events",
      "value": "ReadOnly"
    }
  ],
```
Then go to the Enterprise Application in the portal and assign these new roles to your users. If your AAD SKU allows it you can also assign roles to groups. After this assignment your id_token will have a new `roles` claim:
```
  "roles": [
    "ReadOnly",
    "FullAccess"
  ],
```
Instead of querying the graph API it is now possible to read the roles-array and fill the principal with these roles (may be added to the groups).

## Outlook
I'd like to know if the alternative solution is viable from your point of view. If so, are you open for pull requests?

**Comment by Incarnation-p-lee** [comment]
@wlami 
Thanks for your issue. For current implementation, AADFilter is for session scenario, you can prepare the filter support session stateless. Thanks in advance!

For slow response, as JWT token will obtain the key from domain and validate the token, the content of this domain may not immutable. We can focus on session stateless filter first and take care of the token validation in another PR.

**Comment by danipixis** [comment]
Hi,
is this issue closed by PR **https://github.com/microsoft/azure-spring-boot/pull/512**?
Thank you
