### ISSUE TITLE
Use single version for whole project

### ISSUE THREAD

**Issue by Incarnation-p-lee** [Microsoft/azure-spring-boot#500]
Current we have to edit 17 lines for version upgrade, should depend on one and only one version for this repo.

**Comment by Incarnation-p-lee** [comment]
We can leverage [maven revision place holder](https://maven.apache.org/maven-ci-friendly.html) to archive this target.

**Comment by LennartHaggkvistHM** [comment]
Please note that if you use ${revision} then the public advice is to use flatten-maven-plugin - but that one alters the pom files in a lot of ways. More information: https://github.com/mojohaus/flatten-maven-plugin/issues/51

**Comment by Incarnation-p-lee** [comment]
@LennartHaggkvistHM 
Thanks for your information, We decide to clean up this as it is stupid to change the version in about 20 locations for each version upgrading. We may follow the rules from spring boot project and only leverage `${revision}` in this repo. Please correct me if something misleading.

**Comment by LennartHaggkvistHM** [comment]
@Incarnation-p-lee 
My experience is that it can be a problem - so I would suggest that you 
a) check the installed files in your local mvn repo so that they doesn't contain ${revision} - they should contain the actual version.
b) verify with another project using the new versions (ie - some other project using the snapshot version)

**Comment by Incarnation-p-lee** [comment]
@LennartHaggkvistHM 
Yes, that may be a problem, need to investigate the risk before the PR.

**Comment by Incarnation-p-lee** [comment]
close this issue due to abandon revision.

**Comment by LennartHaggkvistHM** [comment]
@Incarnation-p-lee there is now a new version of the flatten-maven-plugin that works better. I suggest that you test it. The example on https://maven.apache.org/maven-ci-friendly.html works better now.

**Comment by Incarnation-p-lee** [comment]
@LennartHaggkvistHM Good to learn this, we will have a try later.
