### ISSUE TITLE
The link for azure-spring-boot-metrics-starter is broken on homepage. 

### ISSUE THREAD

**Issue by Matthew-Dong** [microsoft/azure-spring-boot#513]

**Comment by dhaval24** [comment]
@Matthew-Dong @Incarnation-p-lee the link on the home page on github points me to the correct maven central location. I believe this issue is about it right? or something on msdocs?

**Comment by Matthew-Dong** [comment]
![image](https://user-images.githubusercontent.com/7653539/51576518-8a6f1c80-1ef1-11e9-8a53-88d577cec7c3.png)

**Comment by Incarnation-p-lee** [comment]
@dhaval24 
Could you please help to update the doc link ?
