### ISSUE TITLE
Disabling Telemetry

### ISSUE THREAD

**Issue by rupert654** [Microsoft/azure-spring-boot#520]
In the README for Azure Active Directory, it states that Microsoft collects data on the usage of this starter by default.

Firstly, isn't it a bit wrong to collect this by default? Let people opt in to this, not out of it. I've never seen a Java library do this before.

For future reference, the data that is collected can be determined by looking at `com.microsoft.azure.telemetry.TelemetryData`.

Secondly, the README explains that to disable this telemetry, you must do the following:

> azure.mediaservices.allow-telemetry=false

However, that will end up setting a property in MediaServicesProperties which is only enabled via MediaServicesAutoConfiguration. It doesn't look like this will ever get activated when using Azure Active Directory.

Instead the correct property seems to be:

> azure.activedirectory.allow-telemetry=false

If I've got that right, then this means that some people may have thought they had opted out of this telemetry when they had not in fact done so (including myself).

**Comment by xscript** [comment]
Close this issue because of inactivity over 10 days.

**Comment by anatoliy-balakirev** [comment]
I does actually cause troubles when one deploys it to the cluster with strict network policies. Our application couldn't start without logging anything and only via thread dump we managed to figure out, that it's stuck on that connection at the very beginning of its startup. Having things like that enabled by default is really something unusual / bad I would say.

**Comment by chenrujun** [comment]
Hi, @anatoliy-balakirev ,

`telemetry` can be disabled by configuration.
Which version are you using?

And we moved repo to here:
https://github.com/Azure/azure-sdk-for-java/tree/azure-active-directory-spring-boot-starter_2.3.5/sdk/spring/azure-spring-boot-starter-active-directory
