### ISSUE TITLE
Multiple AAD support

### ISSUE THREAD

**Issue by xscript** [microsoft/azure-spring-boot#529]
When user have multiple AAD instances, they want to be able to authenticate against all of them in one application. Need investigation how to achieve this.
One possible solution is to use [AAD Connect](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/whatis-azure-ad-connect) to connect them together. Still we need to test and document how to use AAD Connect with our AAD starter.

**Comment by fkretzer** [comment]
We are currently testing the [aad-b2c-integration](https://github.com/Microsoft/azure-spring-boot/tree/aad-b2c-integration) branch and are having the same requirement: Using 2 B2C Tenants in the same application. Is this a planned feature or do you have a suggested solution for this case?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
