### ISSUE TITLE
Slow SpringBoot application startup.

### ISSUE THREAD

**Issue by isatishp** [microsoft/azure-spring-boot#538]
## Environment
- Spring boot starter:
  - key vault spring boot starter

- OS Type: Windows/Linux/MacOS
- Java version: 
  - 1.8

## Summary
Key-vault-secrets starter library loads all secret names, stores a  copy of it in HashMap replacing '-' in secret name with a '.' causing it to resolve a secret twice. Why is HashMap used when only its keys are required to be returned for getPropertyNames()? 
Also, when a keyvault is shared among several microservices, keyvault loads all secrets. There's no provision to specify secrets to be resolved for my application.
When resolving a secret, there's an unnecessary step for reloading all secrets after 30mins of first load. Why is this even necessary when environment once prepared can only be prepared on context refresh?
For fetching each secret, a token is fetched. This token has a validity of 8 hours. Can we not cache the token and reuse it?
So if there are 50 secrets in my keyvault, they are resolved 100 times and for resolving each secret a token is fetched. Also, EnvironmentPostProcessor gets called multiple times. causing the overall process to be much slower.
Since application take a lot of time to boot up, they never start on I1 service plans.

## Reproduce steps
Start the application in debug mode.

**Comment by Incarnation-p-lee** [comment]
@isatishp
Thanks for you issue there. In fact we may have 2 issues here.
* [ ] Store 2 instance for one secret instance.
* [ ] Load all secrets from the keyvault.

We may need time to investigate how to enhancement this.

**Comment by isatishp** [comment]
Thank You for your response.

My keyvault holds upto 60 plus secrets shared by several services. Each
service takes more than 250 seconds to bootup. Also, the point to be
considered here is that there are multiple auto configs in place in these
services. So 250 seconds isn't the time taken by keyvault resolution alone.
Although, I have written a wrapper over your existing code with following
changes which has reduced my startup time to about 70 seconds:

1. Enumerable PropertySource takes List of KeyVaultOperation to support
accessing secrets from multiple keyvaults.
2. Instead of a map to store secret names, I have used a Set without
replacing hyphens(-) with dots(.) . So that it is not resolved twice.
3. Cache the token for 15mins in AzureKeyVaultCredential as the token
itself is valid for 8 hours.
4. Pass secret names of my application as a Set to KeyVaultOperation so
that, it does not load all secrets from keyvault and loads only those I
have passed.

Making these changes alone has improved my start up time.
Please let me know if you need anything more.


Regards,
Satish

**Comment by Incarnation-p-lee** [comment]
@isatishp 
Thanks for you information.

I did some simple performance test over 1000 secrets under keyvault. It costing about 40s to boot up which has gaps from you data. Could you please make a test from our sample code with your 60+ secrets ? So that we can tell gap clearly. 

For first one, we can only extend PropertySource which do not have to implement method getPropertyNames.

For mapping twice, we have enhance the implementation for reducing this, see the PR in above.

For you last items, you mean that when create the keyvaultOperation(we may call it keyvaultSource later), we need to specific the property names list, right ? Please correct me if misunderstanding.

**Comment by Incarnation-p-lee** [comment]
@isatishp
I may close this issue for now as inactive. If you still meet similar issue, please feel free to reopen.

**Comment by neuqlz** [comment]
These problem has been fixed in 2.2.0
