### ISSUE TITLE
Doesnt work if properties are not in Application

### ISSUE THREAD

**Issue by jamie3** [Microsoft/azure-spring-boot#555]
## Environment

    compile 'com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter:2.1.2'
  
- OS Type: Windows/Linux/MacOS
  - 1.8
  

## Summary
Running this application works when the @Value is contained in the Application.class however if your @Value is located in a separate class then null is replaced in the property.

For example (groovy code):

```Groovy
@Component
@ConfigurationProperties
class MyProperties {

    @NotEmpty
    @Value("${myProperty}")
    String myProperty
}
```

In the above ode the property is not passed from AKV.

**Comment by jamie3** [comment]
After removing @NotEmpty annotation it works?

**Comment by sophiaso** [comment]
@jamie3 Thanks for reporting issue, could you provide a working simple sample to reproduce your issue?

**Comment by sophiaso** [comment]
Close due to no response, feel free to reopen with a working sample if the issue still exists.
