### ISSUE TITLE
client-secret is not getting url encoded on token request

### ISSUE THREAD

**Issue by tiltoam** [Microsoft/azure-spring-boot#559]
## Environment
- Spring boot starter:
  - active directory spring boot starter
  
- OS Type: MacOS
- Java version: 
  - 1.9
  

## Summary
When using a client secret that contains characters from the set of reserved characters for building a URI, the response from the oauth2/token endpoint returns with a status of 401 when the client-secret has not been url encoded before being Base64 encoded into the Authorization http header. I have experienced this behavior using v2.1.2 of azure-spring-boot and have also verified it using v2.1.0. I have not experienced this behavior in versions of azure-spring-boot earlier than v.2.1.0. Specifically, I have verified that v.2.0.8-2.0.12 works correctly by url encoding the client-secret prior to Base64 encoding the Authorization header.

## Reproduce steps
1. Follow the tutorial on [https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory?view=azure-java-stable](https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory?view=azure-java-stable).
2. Make sure that the application key generated in step 4 contains at least one character from the reserved character set for URI's. `!	*	'	(	)	;	:	@	&	=	+	$	,	/	?	#	[	]` [https://tools.ietf.org/html/rfc3986#section-2.2](https://tools.ietf.org/html/rfc3986#section-2.2)
3. Make sure to use v.2.1.2 of the azure-active-directory-spring-boot-starter and v.2.1.2 of spring-boot. 

## Expected Results
Successful log in to application registered on Azure.

## Actual Results
Received a 401 from the token endpoint.
`[invalid_token_response] An error occurred while attempting to retrieve the OAuth 2.0 Access Token Response: 401 Unauthorized`

**Comment by tiltoam** [comment]
As a workaround for now, in my WebSecurityConfigurerAdapter I've added:
```java
.tokenEndpoint()
.accessTokenResponseClient(new NimbusAuthorizationCodeTokenResponseClient())
.and()
```

prior to defining the oidcUserService in the Oauth2 login configuration.

The NimbusAuthorizationCodeTokenResponseClient was marked as deprecated in spring-security v5.1.1.RELEASE.

**Comment by Incarnation-p-lee** [comment]
@tiltoam 
Thanks for you effort and information. After some investigation, we think it is better to change to `client-authentication-method` to `post` for following reasons:
* No need for url encoding
* No limitation for url length and header buffer.
* Spring boot autoconfiguration take over the secret, we need to customize oauth2 `clientRegistration` for this.

**Comment by Incarnation-p-lee** [comment]
@tiltoam 
I may close this issue for now as the fix released already. If you still meet similar issue, please feel free to reopen.
