### ISSUE TITLE
KeyVault connection only runs on local machine

### ISSUE THREAD

**Issue by gabkol** [Microsoft/azure-spring-boot#560]
## Environment  
- OS Type: Windows
- Java version: 1.8

## Summary
I followed the MS tutorial for spring and keyvault, which is nearly the same like `azure-keyvault-secrets-spring-boot-sample` from this repo. Then I added my custom keyvault uri, client-id and client-key. For logging purpose I also added those two lines:

`logging.level.org.springframework=debug`
`logging.path=/home/LogFiles/springlog`

When I run the app local, it starts successful, logs my custom secret and writes logfile. Perfect!

But when I deploy the app to azure with same connection values, it doesn't start. I don't get a logfile after waiting hours. If I add the propertie `azure.keyvault.enabled=false`, app will start and write logfile -> so log and deployment proccess is well configured.

MS tutorial: https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault?view=azure-java-stable

**Comment by sophiaso** [comment]
@gabkol Thanks for reporting issue, could you give more details about your issue?

- Which version of azure-keyvault-secrets-spring-boot-starter did you use?
- Under which azure environment did you fail, i.e., windows or linux
- How did you run your Spring application? e.g., running barely with `java -jar` or whatever?
- How many secrets does your Key Vault store have?
- Could you run the application directly with `java -jar` and do not configure `logging.path`? To check what is the log printed on the console?

**Comment by gabkol** [comment]
I solved the issue.

Solution:

- 1. reason: My CI process builds the package with `mvn package` and in my local env I use `spring-boot:run`. Therefore I didn't get all dependencies loaded in azure environment. The curious thing is that only azure dependencies are missing in this different packages.
- 2. reason: azure keyvault dependencies seems to be incompatible with some spring-security-oauth2-client dependencies.

Anyway thanks for your answer.
