### ISSUE TITLE
Missing maven artifact for azure-sqlserver-spring-boot-starter but README doc is incorrect

### ISSUE THREAD

**Issue by iamlothian** [Microsoft/azure-spring-boot#582]
## Environment
- Spring boot starter:
[azure-sqlserver-spring-boot-starter](https://github.com/Microsoft/azure-spring-boot/tree/2.1.2/azure-spring-boot-starters/azure-sqlserver-spring-boot-starter)
  
- OS Type: MacOS
- Java version: 
  - 1.8
  

## Summary
As stated in the readme.md

> azure-sqlserver-spring-boot-starter is published on Maven Central Repository. If you are using Maven, add the following dependency.

azure-sqlserver-spring-boot-starter can't be found?
[maven search](https://search.maven.org/search?q=azure-sqlserver-spring-boot-starter)
[All com.microsoft.azure artifacts](https://search.maven.org/search?q=g:com.microsoft.azure)

## Reproduce steps
Add the dependency to a maven project
```
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-sqlserver-spring-boot-starter</artifactId>
</dependency>
```

## Expected Results
`mvn clean install` would find and load dependency

## Actual Results
```
[INFO] -----------------< com.project:merchants >------------------
[INFO] Building merchants 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.microsoft.azure:azure-sqlserver-spring-boot-starter:jar:2.1.2 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.988 s
[INFO] Finished at: 2019-02-18T11:24:53+11:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project merchants: Could not resolve dependencies for project com.project:merchants:jar:0.0.1-SNAPSHOT: Failure to find com.microsoft.azure:azure-sqlserver-spring-boot-starter:jar:2.1.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

**Comment by sophiaso** [comment]
@iamlothian Thanks for opening issue, the `azure-sqlserver-spring-boot-starter` is not released, as the feature is incomplete and not working as expected. We will update the doc accordingly to clarify this situation.

If possible, could you share your usage scenario about this feature? We will prioritize to update and release this starter if it helps a lot.

**Comment by iamlothian** [comment]
I found this spring boot starter after selecting Azure SQL as a database solution and wishing to use encryption at rest. 

https://docs.microsoft.com/en-us/azure/sql-database/sql-database-always-encrypted

For now, integrating azure SQL with JDBC and JPA is desired. Could I use the following to do so?
```
...
        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
         </dependency>
...
```

**Comment by sophiaso** [comment]
Hi @iamlothian, please check whether this [spring-data-jdbc-on-azure#azure-sql-database
](https://github.com/Azure-Samples/spring-data-jdbc-on-azure#azure-sql-database) sample works for you.

**Comment by Incarnation-p-lee** [comment]
@iamlothian will close it as inactive, please feel free to reopen if any related issues.
