### ISSUE TITLE
AADAuthenticationFilter.doFilterInternal treats an accessToken as an IdToken

### ISSUE THREAD

**Issue by cljung** [Microsoft/azure-spring-boot#585]
## Environment
- Spring boot starter:
   - active directory spring boot starter
  
- OS Type: all
- Java version: 11, 1.9, 1.8
  

## Summary
When calling a REST API with HTTP header Authentication Bearer xxxxxxx, the AADAuthenticationFilter.doFilterInternal treats the accessToken as an JWT idToken and the call on line 71 principalManager.buildUserPrincipal(idToken) throws an exception since it tries to parse it as JSON.

## Reproduce steps
1. Use the sample azure-active-directory-spring-boot-sample
2. Use Postman to get an OAuth2 access token to your registered app (do not use the UI login)
3. Call an API

## Expected Results
Authenticate using the accessToken passed in the HTTP Header Authirization Bearer xxxxxx

## Actual Results
You will get an exception

java.text.ParseException: Invalid serialized unsecured/JWS/JWE object: Missing part delimiters
        at com.nimbusds.jose.JOSEObject.split(JOSEObject.java:222) ~[nimbus-jose-jwt-6.7.jar!/:6.7]
        at com.nimbusds.jose.JWSObject.parse(JWSObject.java:414) ~[nimbus-jose-jwt-6.7.jar!/:6.7]
        at com.microsoft.azure.spring.autoconfigure.aad.UserPrincipalManager.buildUserPrincipal(UserPrincipalManager.java:63) ~[azure-spring-boot-2.1.3.jar!/:na]
        at com.microsoft.azure.spring.autoconfigure.aad.AADAuthenticationFilter.doFilterInternal(AADAuthenticationFilter.java:71) ~[azure-spring-boot-2.1.3.jar!/:n

**Comment by floriandorau** [comment]
Hi,

I'm facing a similar issue. Did you solved it or why was it closed?

Regards

**Comment by RaghavendraSingh** [comment]
Hi, 
I am facing the same issue as well.
did anyone find a solution for this?

Thanks

**Comment by desertTown** [comment]
Hi,
I am facing the same issue as well. Did anyone find a solution for this?

Thanks

**Comment by saragluna** [comment]
@desertTown 

The AADAuthenticationFilter is designed to accept ID token instead of the access token.

**Comment by pandajiangbao** [comment]
Hi,
I am facing the same issue as well. Why closed the issue, have any solution?

Thanks

**Comment by saragluna** [comment]
@pandajiangbao 

Could you share more details about your issue?
