### ISSUE TITLE
Why two micrometer starters?

### ISSUE THREAD

**Issue by mercer** [Microsoft/azure-spring-boot#587]
I'm curious what's the difference between azure-spring-boot-metrics-starter and applicationinsights-spring-boot-starter? Why two starters? Should I use both? When should I use each?

Thanks

**Comment by Incarnation-p-lee** [comment]
@dhaval24 
Could you please help to answer the question ?

**Comment by dhaval24** [comment]
@mercer yes you should use both. application insights springboot starter, helps you capture request, logs, dependencies (external calls like http, mysql) if used with Application Insights Java agent.

Azure-metrics-springboot-starter helps you get all the java metrics that micrometer provides.

We took this design to provide modularity and flexibility for users.

**Comment by dhaval24** [comment]
Closing this for now. Please reopen if you still have questions.
