### ISSUE TITLE
Packaged ApplicationInsights.xml contains hard coded instrumentationKey

### ISSUE THREAD

**Issue by LennartHaggkvistHM** [Microsoft/azure-spring-boot#592]
## Environment
- Spring boot starter:
azure-spring-boot-starter  2.1.3 (and from at least 2.0.8)  

## Summary
The packaged jar contains an ApplicationInsights.xml that with the following instrumentationKey:
```
    <InstrumentationKey>d3278c59-22d7-4697-af8c-ff0077e3b4e9</InstrumentationKey>
```

## Reproduce steps
When used together with the logback appender (from applicationinsights-logging-logback) that instrumentationKey was used instead of the one that we wanted.

## Expected Results
Should only use our instrumentationKey - not any hard coded ones.

## Actual Results
No logs arrived to our application insight - and after a long debugging session we found out that another instrumentationKey was actually being used.

**Comment by Incarnation-p-lee** [comment]
@LennartHaggkvistHM 
Thanks for your issue. It may related to ai sdk configuration mechanism. We are working on it.

**Comment by dhaval24** [comment]
@Incarnation-p-lee yes I think this is correct. It would be interesting to investigate how this behaves when customer's app has one of the azure starter, and the user himself also adds the Application Insights SpringBoot starter to configure their app. 
you should ensure that telemetry is not polluted. 

1. User telemetry goes to his or her ikey.
2. The usage telemetry goes to your ikey.

Also, it is very tricky to provide the hardcoded ikey inside the config file. This can cause potential security issues also.

**Comment by Incarnation-p-lee** [comment]
@dhaval24 @LennartHaggkvistHM 
Thanks for your issue here. We have hotfix for this issue and remove the `ApplicationInsights.xml` for now. Could you please help to try the `2.1.4` version.

To avoiding less impact to user, we would like to file another issue to track this.

**Comment by LennartHaggkvistHM** [comment]
@Incarnation-p-lee We are still on spring boot 2.0 and as far as I can see there has been no release for that branch?

**Comment by Incarnation-p-lee** [comment]
@LennartHaggkvistHM 
Yes, still under working. The release 2.1.x for spring 2.1.x may have higher priority.

**Comment by LennartHaggkvistHM** [comment]
The 2.0.12 release seems to fix the problem for us. Thanks!

**Comment by Incarnation-p-lee** [comment]
Thanks @LennartHaggkvistHM for issue this. Any other problem please feel free to contact us.
