### ISSUE TITLE
azure-spring-boot-metrics-starter Metrics Location in Azure Monitor

### ISSUE THREAD

**Issue by JRiggenbach** [Microsoft/azure-spring-boot#608]
## Environment
- Spring boot starter:
  - azure-spring-boot-metrics-starter 
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  - 1.8
  
## Summary
The MS documentation lead me to believe that all I had to do was add this dependency, add the instrumentation key and that would get me running with pre-aggregated metrics auto collected to Azure Monitor. I can't seem to find any JVM related info in Azure Monitor

## Reproduce steps
Add azure-spring-boot-metrics-starter to pom
Add instrumentation key

## Expected Results
A certain amount of metrics will be available in Azure Monitor
Default Metrics:
Automatically configured metrics for Tomcat, JVM, Logback Metrics, Log4J metrics, Uptime Metrics, Processor Metrics, FileDescriptorMetrics.

## Actual Results
I can't find any metrics available.

**Comment by dhaval24** [comment]
@JRiggenbach as per this documentation https://docs.microsoft.com/en-us/azure/azure-monitor/app/micrometer-java you need to add both Application Insights SpringBoot Starter and azure-spring-boot-metrics-starter to track requests, response and collect Java metrics and set the instrumentation key as `azure.application-insights.instrumentation-key`. Please ensure you followed both the steps.

After that you can see the metrics in https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-charts . Most likely it feels that you are looking at the incorrect location on the portal for these metrics.

**Comment by JRiggenbach** [comment]
I have added both the Application Insights SpringBoot Starter and azure-spring-boot-metrics-starter dependencies.

I have been browsing through the Metrics blade, but it's still clear as to where this data is made available.  Would it be under the application insights resource for the instrumentation key that I used?  If so, I still don't see any Tomcat or JVM metrics when I select that resource.

**Comment by JRiggenbach** [comment]
Ok, I was finally able to track down where these things can be found in Azure Monitor.  I had to start over with a simple application.  Next step is to figure out why these metrics are not showing for my original application.  Could be related to the issue were my live stream data is not coming through for this same application...

**Comment by JRiggenbach** [comment]
I have a aggregate Maven project so when I move some of these dependencies around higher in the chain, they start to work, also while breaking other things since they overwrite older dependencies. Either way, once I get my dependencies unwound, I think this will work.

Feel free to close this issue.

**Comment by Incarnation-p-lee** [comment]
Thanks @JRiggenbach and @dhaval24 , will close this issue for now.

**Comment by nitishsinghal29** [comment]
@JRiggenbach and @dhaval24 , Can you help me figure out what metrics would be available exactly in "Metrics Explorer" after adding the `azure-spring-boot-metrics-starter` dependency.

- Can you provide exact name of those? 

- Would these be available in existing Metric Namespaces "Log-based Metrics" and "Standard Metrics" or will there be a new Metric Namespace be available after adding the above dependency?

**Comment by konstantinblaesi** [comment]
Using spring boot 2.1.8 the azure metrics exporter autoconfiguration was not working for me.
Running with debug=true in application.properties showed

>    AzureMonitorMetricsExportAutoConfiguration:
>       Did not match:
>          - @ConditionalOnResource did not find resource 'classpath:metrics.enable.config' (OnResourceCondition)
>       Matched:
>          - @ConditionalOnClass found required class 'io.micrometer.azuremonitor.AzureMonitorMeterRegistry' (OnClassCondition)
> 

which is confusing because it should be present after [adding azure-spring-boot-metrics-starter](https://github.com/microsoft/azure-spring-boot/blob/master/azure-spring-boot-starters/azure-spring-boot-metrics-starter/src/main/resources/metrics.enable.config) right ?
After I creating _src/main/resources/metrics.enable.config_ it worked!

@nitishsinghal29 Afaik this would be the metrics exported to azure http://localhost:8080/actuator/metrics (metrics actuator needs to be enabled)
