### ISSUE TITLE
Telemetry not disabled by config

### ISSUE THREAD

**Issue by itchyknee** [Microsoft/azure-spring-boot#611]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  
- OS Type: MacOS
- Java version: 
  
  - 1.8
  
## Summary
Relating to [Issue #520](https://github.com/Microsoft/azure-spring-boot/issues/520) where documentation was fixed to show how to disable telemetry.

After setting `azure.activedirectory.allow-telemetry` to `false`, telemetry is still enabled with Azure AD starter.

Relevant classes:
* `com.microsoft.azure.spring.autoconfigure.aad.AADAuthenticationFilterAutoConfiguration`
* `com.microsoft.azure.spring.autoconfigure.aad.AADAuthenticationFilter`
* `com.microsoft.azure.telemetry.TelemetryProxy`
* `com.microsoft.applicationinsights.TelemetryClient`

## Reproduce steps

This is the flow I can see:
* `azure.activedirectory.allow-telemetry` is set to `false` per documentation
* `AADAuthenticationFilterAutoConfiguration` initialises a `TelemetryProxy` field on construction, passing `isAllowTelemetry` correctly based on config to control whether telemetry is sent.
* The `TelemetryProxy` constructor initialises a `TelemetryClient` field on construction. It does not disable the client based on `isAllowTelemetry`
* `AADAuthenticationFilterAutoConfiguration.azureADJwtTokenFilter()` creates an `AADAuthenticationFilter` but before returning `trackCustomEvent()` calls `TelemetryProxy.trackEvent()` which in turn calls `TelemetryClient.trackEvent()`
* `TelemetryClient.trackEvent()` sends telemetry data

## Expected Results

Telemetry should not be sent.

Either 
* `TelemetryProxy.trackEvent()` should check for `isAllowTelemetry` and shortcut return without sending or
* `TelemetryProxy`'s internal `TelemetryClient` should be constructed with tracking disabled

## Actual Results

Telemetry is sent.

## Workaround

I had to create my own `AADAuthenticationAutoConfig` which creates the AADAuthenticationFilter without telemetry.

**Comment by Incarnation-p-lee** [comment]
thanks for issue this，could u please share which version you are using?

**Comment by itchyknee** [comment]
Sorry for the delay - didn't get a notification...

We're using `com.microsoft.azure:azure-spring-boot-bom:2.0.5`

**Comment by itchyknee** [comment]
Fixed in `com.microsoft.azure:azure-spring-boot-bom:2.0.13`
Sorry for not realising.
