### ISSUE TITLE
Update to azure-storage-spring-boot-starter from 2.0.6 to 2.0.7+ breaks whole code

### ISSUE THREAD

**Issue by mariuszs** [Microsoft/azure-spring-boot#625]
What is the purpose of this MINOR update? Is this library PRODUCTION READY at all?

Some of the missing imports after the update:

```
import com.microsoft.azure.storage.CloudStorageAccount;
import com.microsoft.azure.storage.StorageException;
import com.microsoft.azure.storage.blob.BlobContainerPermissions;
import com.microsoft.azure.storage.blob.BlobContainerPublicAccessType;
import com.microsoft.azure.storage.blob.CloudBlobClient;
import com.microsoft.azure.storage.blob.CloudBlobContainer;
```

**Comment by mariuszs** [comment]
2.0.7 uses

```
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-storage-blob</artifactId>
    <version>10.1.0</version>
```
where 2.0.6 was using:


```
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-storage-blob</artifactId>
    <version>5.5.0</version>
```

**Comment by sophiaso** [comment]
Hi @mariuszs, basically this repo aligns version with Spring Boot versions, check [wiki](https://github.com/Microsoft/azure-spring-boot/wiki/Branch-and-release). The big version change for `azure-storage-blob` is because storage sdk has design change starting from v10, see [migration doc](https://github.com/Azure/azure-storage-java#migrating-to-v10). If you are only using storage auto configuration from azure-spring-boot, you may not need to upgrade your azure-spring-boot version, if you do not want break change.

**Comment by mariuszs** [comment]
> you may not need to upgrade your azure-spring-boot version, if you do not want break change.

Probably this method always works, but there is another method. Increment Major version number instead of Minor version if there is a big change in the library. This same applies to starters and bill-of-material projects.

There was nothing in Spring Boot 2.1 that requires such big change in my opinion, so this is unrelated.

**Comment by sophiaso** [comment]
The versions aligns with Spring Boot, i.e., if this repo uses Spring Boot 2.0.x, the version will be released as 2.0.x. Exactly, the change of azure storage sdk is not related with Spring Boot itself, they are independent of each other.

**Comment by Incarnation-p-lee** [comment]
@mariuszs 
Thanks for mention this. As I know, spring framework from 5.0.x to 5.1.x has breaking changes, as well as spring boot 2.0.x to 2.1.x and spring data 2.0.x to 2.1.x. That is why we have 2 release branch. 

In other handle, as sdk side updated. It can hardly always leverage old versions without new features, better performance(Such as if you want to leverage new instruction of CPU, you need to upgrade kernal version). I am a little curious that from what perspective for this issue, if you need help about how to leverage the starter, feel free to contact us. 

Thanks again for your issue.

**Comment by mariuszs** [comment]
@Incarnation-p-lee You have 2 broken branches, What is the point of this? Simply update SDK in newest branch and keep old branch stable. This allows people to migrate.

Your way of releasing azure artefacts is **useless** because Your recommendation is to not upgrade at all:

> you may not need to upgrade your azure-spring-boot version, if you do not want break change.

**Comment by mariuszs** [comment]
And another useless piece is this wiki -> https://github.com/Microsoft/azure-spring-boot/wiki/Branch-and-release

The missing part is about compatibility with Azure SDK. There is generally no need to perfect match spring version in a project, because Spring is generally backwards compatible but Azure SDK is not.

**Comment by Incarnation-p-lee** [comment]
@mariuszs 
Thanks for some many details. But the point of this issue you cannot make branches for each azure sdk. Azure sdk development is out of our control, they may got breaking changes for each release version. There are about 1000+ azure services with their sdks, and how many branches you need to take care of these potential breaking changes for one repo ?

From production perspective, you may always need trade-off for some scenario out of your control.
