### ISSUE TITLE
Spring caching the token

### ISSUE THREAD

**Issue by ateeqsayed** [Microsoft/azure-spring-boot#628]
I have sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)  in my code.
I make a REST call to the API with a valid token and then I modify the token yet spring treats it as a valid token and does not give an error  "message": "Signed JWT rejected: Invalid signature". But when I restart the server and use an invalid token it then gives me the error.

**Comment by Incarnation-p-lee** [comment]
@ateeqsayed 
Thanks for issue this, could you please help to provide more information about this, like version, spring boot version, or minimal reproduce code ?

**Comment by ateeqsayed** [comment]
@Incarnation-p-lee,
I was able to fix it by adding server.servlet.session.cookie.max-age=0

**Comment by Incarnation-p-lee** [comment]
@ateeqsayed 
Good to know that, thanks for you information.
