### ISSUE TITLE
Build fails Could not find artifact com.microsoft.azure:azure-active-directory-spring-boot-starter:jar:2.1.7-SNAPSHOT

### ISSUE THREAD

**Issue by mahoekst** [microsoft/azure-spring-boot#648]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
 
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  
  - 1.9

  

## Summary
Cannot compile the repository. Could not find artifact com.microsoft.azure:azure-active-directory-spring-boot-starter:jar:2.1.7-SNAPSHOT

## Reproduce steps
install Java (12), Maven. Check if all works. Check!
mvn install -DskipTests -X in the azure-active-directory-spring-backend-sample directory. Fails with Could not find artifact com.microsoft.azure:azure-active-directory-spring-boot-starter:jar:2.1.7-SNAPSHOT

## Expected Results

Compile would work

## Actual Results

Compile failes

**Comment by Incarnation-p-lee** [comment]
@mahoekst 
Thanks for issue this. Could you please share you minimal pom file to reproduce this ? From our env, I cannot reproduce you issue.

**Comment by mahoekst** [comment]
It's the file in the repo. I changed the file ot use com.microsoft.azure:azure-active-directory-spring-boot-starter:jar:2.1.6 and it started working (the compile piece)

**Comment by Incarnation-p-lee** [comment]
@mahoekst 
I see, for snaphot version you may need to add special configuration, see our doc here.
https://github.com/Microsoft/azure-spring-boot#snapshots
