### ISSUE TITLE
Any event to listen for the Azure key vault secret updates

### ISSUE THREAD

**Issue by sheekaat** [microsoft/azure-spring-boot#652]
## Environment
- Spring boot starter:
  
   - key vault spring boot starter
 
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  - 1.8
  

## Summary
We use Azure key vault to store cosmos db keys as secrets and used key vault starter to fetch those and established connection to cosmos db. Whenever we do the key vault updates for the secret, we need to call the actuator refresh to get the newly updated secret. For this, do we've any event to listen to the updates of key vault in the spring context?

**Comment by moarychan** [comment]
https://github.com/microsoft/azure-spring-boot/issues/840

**Comment by moarychan** [comment]
Hi @sheekaat , please check this issue https://github.com/microsoft/azure-spring-boot/issues/683 https://github.com/microsoft/azure-spring-boot/issues/840 to see if it helps, if yes you can follow it then close this issue.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
