### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by yossaa** [microsoft/azure-spring-boot#658]
azure-keyvault-spring-boot-starter 2.1.6 is using 2 years old azure-keyvault dependency, which causes conflict with azure-client-authentication:

![image](https://user-images.githubusercontent.com/14076521/56807156-45c78a00-682e-11e9-8bf9-1a45d580f0d0.png)

**Comment by saragluna** [comment]
Thanks for reporting this. We'll check it.

**Comment by saragluna** [comment]
azure-client-runtime has been upgraded in the new release so close this issue.
