### ISSUE TITLE
ADFS Support in addition of AAD

### ISSUE THREAD

**Issue by jbpaux** [microsoft/azure-spring-boot#670]
## Environment
- Spring boot starter:
  - active directory spring boot starter
  
- OS Type: Linux- Java version: 
  - 1.9

## Summary
We are deploying an app on both public Azure Cloud integrated with Azure AD and on Azure Stack wich leverage ADFS (disconnected env). Would it be possible to use this library with both as we can do using adal/msal standard library. Since MS Graph is not available this can be an issue.

## Reproduce steps
None

## Expected Results
Have an application that is able to authenticate to both Azure AD and ADFS.

## Actual Results
Doesn't seem possible

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
