### ISSUE TITLE
AADB2C support china cloud endpoint

### ISSUE THREAD

**Issue by xukai286** [microsoft/azure-spring-boot#672]
## Environment
- Spring boot starter:
  
  - azure-active-directory-b2c-spring-boot-starter 2.1.6.M2
- OS Type: Windows/Linux/MacOS
- Java version: 
  
  - 1.9
  - 1.8
  - 1.7
  

## Summary

all the url in b2c login has the fixed endpoint which is not for Azure China cloud
China cloud has a different endpoint which is end with:
partner.onmschina.cn

## Expected Results

https://xxx.b2clogin.cn/xxx.partner.onmschina.cn/oauth2/v2.0/authorize

## Actual Results

https://xx.b2clogin.com/xx.onmicrosoft.com/oauth2/v2.0/authorize

**Comment by Incarnation-p-lee** [comment]
thanks a lot for request china, will add to our plan.

**Comment by PengleiShi** [comment]
@xukai286 Is it possible to add some configuration to support china cloud endpoint?

**Comment by neuqlz** [comment]
Yep, we have added this feature to our plan, as soon as we have updates, we will reach you. @PengleiShi

**Comment by PengleiShi** [comment]
Thanks. I have modified the code of `azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/b2c/AADB2CURL.java` ,  replaced the global endpoints with China endpoints.

**Comment by neuqlz** [comment]
Hi @PengleiShi,
That is a workaround, sorry for the inconvenience.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
