### ISSUE TITLE
Spring vault key vault is not correctly mapping keys that contain '-' character

### ISSUE THREAD

**Issue by erviszyka** [microsoft/azure-spring-boot#673]
## Environment
- Spring boot starter:
  - key vault spring boot starter

- OS Type: Windows

- Java version: 
  - 1.8

## Summary
I have the key `azure.activedirectory.b2c.client-id` stored in the azure keyvault
as `azure-activedirectory-b2c-client-id`. I am trying to access this key in my code
using the `@Value` spring annotation and it fails to map the keyvault value
`azure-activedirectory-b2c-client-id` to the value `azure.activedirectory.b2c.client-id`.

The keyvault code replaces all the '.' characters with '-'
https://github.com/microsoft/azure-spring-boot/blob/master/azure-spring-boot/src/main/java/com/microsoft/azure/keyvault/spring/KeyVaultOperation.java#L117

For the moment I've managed to find a workaround and bypass this limitation by creating
a new property that doesn't contain the '-' character 

```
azure.activedirectory.b2c.client-id=${azure.activedirectory.b2c.client.id}
```

## Reproduce steps
1. Go to Azure Keyvault and create a value for the key `azure-activedirectory-b2c-client-id`
2. Configure vault in the application.properties

```
azure.keyvault.client-id=
azure.keyvault.client-key=
azure.keyvault.uri=
```
3. Run the following code:

```java
@SpringBootApplication
public class SampleApplication implements CommandLineRunner {
    private static final Logger LOGGER = LoggerFactory.getLogger(SampleApplication.class);

    @Value("${azure.activedirectory.b2c.client-id}")
    private String mySecretProperty;

    public static void main(String[] args) {
        SpringApplication.run(SampleApplication.class, args);
    }

    public void run(String... varl) throws Exception {
        LOGGER.info("property azure.activedirectory.b2c.client-id in Azure Key Vault: {}", mySecretProperty);

        System.out.println("property azure.activedirectory.b2c.client-id in Azure Key Vault: " + mySecretProperty);
    }
}
```

## Expected Results
I would expect the variable mySecretProperty to contain the value stored in the keyvault.

## Actual Results
Spring boot throws exception

```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'azure.activedirectory.b2c.client-id' in value "${azure.activedirectory.b2c.client-id}"
```

**Comment by Incarnation-p-lee** [comment]
@erviszyka
Thanks a lot, the implementation almost due to the restriction of keyvault secret name cannot contain '-', will sync with service team for this.

**Comment by nitishsinghal29** [comment]
Is there any update on this issue? 
I am using property `azure.storage.connection-string` in spring boot app, which is getting converted to `azure.storage.connection.string`

**Comment by saragluna** [comment]
@nitishsinghal29 
Since the Key Vault does have limitations on secrets' name, you could try [placeholders](https://github.com/microsoft/azure-spring-boot/tree/master/azure-spring-boot-starters/azure-keyvault-secrets-spring-boot-starter#placeholders-in-properties) in property files.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
