### ISSUE TITLE
Enable listing all groups a user is memberOf, including indirect membership 

### ISSUE THREAD

**Issue by blacelle** [microsoft/azure-spring-boot#675]
com.microsoft.azure.spring.autoconfigure.aad.AzureADGraphClient.loadUserGroups(String) relies on  https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=javascript

which returns the direct groups current user is memberOf

Should AzureADGraphClient also rely on
https://docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&tabs=cs
to return the groups in which the user is indirectly a member?

**Comment by blacelle** [comment]
It seems https://docs.microsoft.com/en-us/graph/api/group-getmembergroups?view=graph-rest-1.0&tabs=http is equivalent of memberOf but with thansitivity.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
