### ISSUE TITLE
There is not new version jar in maven centor repository for cosmos db starter

### ISSUE THREAD

**Issue by Simon-zhenfeng** [microsoft/azure-spring-boot#678]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  - documentdb spring boot starter
  - key vault spring boot starter
  - media services spring boot starter
  - service bus spring boot starter
  - storage spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  
  - 1.9
  - 1.8
  - 1.7

**Comment by Incarnation-p-lee** [comment]
@Simon-zhenfeng 
Thanks a lot for issue this, could you please provide more information about this, like version as well as spring boot version you are using ?

**Comment by Simon-zhenfeng** [comment]
Hi Pan,


I'm sorry I used the error pom dependency, I actually should use: azure-cosmosdb-spring-boot-starter. Now it is resolved.


I also have another problem that:
I want to log the used RU information in my log, howevery it is rellay difficult to log it when I choose use spring data cosmosdb. So, is there some method to implement it?




------------------ 原始邮件 ------------------
发件人: "Pan Li"<notifications@github.com>;
发送时间: 2019年6月10日(星期一) 中午12:42
收件人: "microsoft/azure-spring-boot"<azure-spring-boot@noreply.github.com>;
抄送: "Simon H"<412133775@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [microsoft/azure-spring-boot] There is not new version jar inmaven centor repository for cosmos db starter (#678)




@Simon-zhenfeng
 Thanks a lot for issue this, could you please provide more information about this, like version as well as spring boot version you are using ?

**Comment by Incarnation-p-lee** [comment]
That's OK. Could u please open one issue from spring data cosmosdb ?

**Comment by Incarnation-p-lee** [comment]
close it for now, and feel to reopen it if there is similar question.
