### ISSUE TITLE
AAD graph API upgrading.

### ISSUE THREAD

**Issue by Incarnation-p-lee** [microsoft/azure-spring-boot#679]
As there are some issues about AAD graph API upgrading, and I summarized some features and issues as below:

* [ ] Support new Graph API.
* [ ] Allow older user leverage old graph API (MS graph) with one EOL time.
* [ ] https://github.com/microsoft/azure-spring-boot/issues/675 
* [ ] https://github.com/microsoft/azure-spring-boot/issues/663
* [ ] https://github.com/microsoft/azure-spring-boot/issues/659
* [ ] https://github.com/microsoft/azure-spring-boot/issues/642

**Comment by neuqlz** [comment]
the v2 feature has merged into the master now.
