### ISSUE TITLE
login/oauth2/code/azure seems to be hardcoded path

### ISSUE THREAD

**Issue by hmallepally** [microsoft/azure-spring-boot#681]
login/oauth2/code/azure  seems to be hard coded path. can we configure it to a path of our preference?

**Comment by Incarnation-p-lee** [comment]
the path pattern should be `/login/oauth2/code/{provider}`, you reference the [doc](https://docs.spring.io/spring-security/site/docs/5.1.5.RELEASE/reference/htmlsingle/#oauth2login-sample-redirect-uri) from spring security.

**Comment by Incarnation-p-lee** [comment]
close it for now, and feel to reopen it if there is similar question.
