### ISSUE TITLE
How does "redirect_uri" gets its value?

### ISSUE THREAD

**Issue by hmallepally** [microsoft/azure-spring-boot#690]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  - documentdb spring boot starter
  - key vault spring boot starter
  - media services spring boot starter
  - service bus spring boot starter
  - storage spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  
 - 1.8
  - 1.7
  

## Summary
Always the IP address is resolved for redirect_uri instead of domain. we have been having issue with this for couple of weeks an not able to use azure support with spring boot.

## Reproduce steps

https://{domain}/api/oauth2/login

it redirects to 
https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id={clientID}&scope=openid%20https://graph.microsoft.com/user.read&state=yh7Qq2XBw_K9wK6LM7vBVok5TEIeW5cYPl-aK2chnzc%3D&redirect_uri=http://{{IP}}:8080/api/login/oauth2/code/azure

it fills in IP address for redirect_uri, how do I configure it?
## Expected Results
the redirect_uri should be configurable.

## Actual Results
It gets filled in with internal IP address, it won't work.

**Comment by Incarnation-p-lee** [comment]
could you please provide more information about this issue ? like which starter, version, spring boot version, as well as minimal code for reproducing ?

**Comment by kdhindsa** [comment]
You'd want to set this property in your application.properties or application.yml file:

spring.security.oauth2.client.registration.azure.redirect-uri=https://HOSTNAME/login/oauth2/code/azure

**Comment by saragluna** [comment]
Closing this issue.
