### ISSUE TITLE
Redirect to a translated B2C login page based on the user locale/language

### ISSUE THREAD

**Issue by erviszyka** [microsoft/azure-spring-boot#691]
## Environment
- Spring boot starter:
  - azure-active-directory-b2c-spring-boot-starter
- Java version: 
  - 1.8
  

## Summary
I use the `aad-b2c-integration` branch to integrate with Azure AD B2C. When I am redirected to the the B2C login page 

```
https://<tenant>.b2clogin.com/<tenant>.onmicrosoft.com/oauth2/v2.0/authorize?client_id=...
```

I am not able to display a translated login page to the user since I can't pass the language/locale in the query param. According to the [documentation](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-language-customization) if the request contains the query param `ui_locales`, the B2C will display the translated login page .

Any ideas when this feature will be supported or any alternatives to achieve the same result? 

I've checked the code  and I think the reason this happens is because of [AADB2CURL.java](https://github.com/microsoft/azure-spring-boot/blob/aad-b2c-integration/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/b2c/AADB2CURL.java#L42)

I would like to create a PR addressing this issue but I would like some guidance, to agree on the approach. I think that the `ui_locales` should be passed when [AADB2CEntryPoint.commence](https://github.com/microsoft/azure-spring-boot/blob/aad-b2c-integration/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/b2c/AADB2CEntryPoint.java#L34) is called. The locale can be retrieved using [RequestContextUtils](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/support/RequestContextUtils.html#getLocale-javax.servlet.http.HttpServletRequest-).

### Expected Results

I would expect to be able to redirect the user and display a translated login page.

### Actual Results

There isn't any way to redirect the user and display a translated login page.

**Comment by Incarnation-p-lee** [comment]
Could you please help to have a try on this (milestone version)[https://search.maven.org/artifact/com.microsoft.azure/azure-active-directory-b2c-spring-boot-starter/2.1.6.M2/jar], required spring boot 2.1.x.

**Comment by erviszyka** [comment]
Hi,
I used the milestone version and it worked. Had to provide my own version of `AADB2CAuthorizationRequestResolver`  and manually add the `ui_locale` query param in the redirect URL.  I am closing the issue if that's OK.
Thanks

**Comment by neuqlz** [comment]
What is your scenario? From my perspective, you don't need to set **ui_locales** by yourself. B2C will adjust its language according to the browser's language. Even if your browser doesn't have a language set, B2C will use the default language you set in the portal.

> ui-locales specified language: After you enable language customization, your user flow is translated to the language that's specified here.
Browser-requested language: If no ui_locales parameter was specified, your user flow is translated to the browser-requested language, if the language is supported.
Policy default language: If the browser doesn't specify a language, or it specifies one that is not supported, the user flow is translated to the user flow default language.

**Comment by gomathi-manakavalan** [comment]
> Hi, I used the milestone version and it worked. Had to provide my own version of `AADB2CAuthorizationRequestResolver` and manually add the `ui_locale` query param in the redirect URL. I am closing the issue if that's OK. Thanks

Will you please tell me how to enable this in springboot app. Because the url is constructed by the aad b2c jar file. Thanks.

**Comment by chenrujun** [comment]
Hi, @gomathi-manakavalan 

Which version of `spring-cloud-azure-starter-active-directory` are you using?

1. If your version >= 4.0, you can use property: `spring.cloud.azure.active-directory.b2c.authenticate-additional-parameters`. Refs: https://microsoft.github.io/spring-cloud-azure/current/reference/html/appendix.html#_azure_active_directory_b2c_properties.

2. If your version < 4.0, you can use property `azure.activedirectory.b2c.authenticate-additional-parameters`. Refs: https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter-active-directory-b2c_3.14.0/sdk/spring/azure-spring-boot-starter-active-directory-b2c#accessing-a-web-application

3. And if your version < 4.0, it's suggested to upgrade to 4.x. Refs: https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#migration-guide-for-4-0

**Comment by chenrujun** [comment]
Hi, @gomathi-manakavalan 

Please refer to this:
https://github.com/Azure/azure-sdk-for-java/issues/29645#issuecomment-1171239213

**Comment by gomathi-manakavalan** [comment]
@chenrujun  finally solved the mystery. 
for Azure ad b2c the implementation is different than you mentioned above. 

I wrote an custom CustomAADB2CAuthorizationRequestResolver extends AADB2CAuthorizationRequestResolver and override the method getB2CAuthorizationRequest. i got the currentlanguage from the http request

`  public OAuth2AuthorizationRequest resolve(@NonNull HttpServletRequest request, String registrationId) {
        if (request == null) {
            throw new NullPointerException("request is marked non-null but is null");
        } else if (StringUtils.hasText(this.passwordResetUserFlow) && this.isForgotPasswordAuthorizationRequest(request)) {
            OAuth2AuthorizationRequest authRequest = this.defaultResolver.resolve(request, this.passwordResetUserFlow);
            return this.getB2CAuthorizationRequest(authRequest, this.passwordResetUserFlow);
        } else {
            currentLanguage = getCurrentLanguage(request);
            return StringUtils.hasText(registrationId) && requestMatcher.matches(request) ? this.getB2CAuthorizationRequest(this.defaultResolver.resolve(request), registrationId) : null;
        }
    }

// To get the springboot current language.
    private String getCurrentLanguage(HttpServletRequest request) {
        Locale locale = null;

        WebApplicationContext wac = WebApplicationContextUtils.getRequiredWebApplicationContext(request.getServletContext());

        Map resolvers = wac.getBeansOfType(LocaleResolver.class);
        if (resolvers.size()==1) {
            localeResolver = (SessionLocaleResolver) resolvers.values().iterator().next();
        }
        if (localeResolver!=null) {
            locale = localeResolver.resolveLocale(request);
            logger.debug("Users current locale: "+locale);
            LocaleContextHolder.setLocale(locale);
        }
        return locale.getLanguage();
    }

    private OAuth2AuthorizationRequest getB2CAuthorizationRequest(@Nullable OAuth2AuthorizationRequest request, String userFlow) {
        Assert.hasText(userFlow, "User flow should contain text.");
        if (request == null) {
            return null;
        } else {
            this.cleanupSecurityContextAuthentication();
            Map<String, Object> parameters = new HashMap(request.getAdditionalParameters());
            parameters.put("p", userFlow);
            parameters.put("x-client-SKU", "spring-boot-starter");
            parameters.put("ui_locales", currentLanguage);
            parameters.put("domain_hint", "GCCF");

            return OAuth2AuthorizationRequest.from(request).additionalParameters(parameters).build();
        }
    }`

In My websecurity configuration i set the custom authorized request resolver. Now it appends the ui_locales property when it constructs the url and also passes the current language the user choose on spring.

`@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    private static final String SPRING = "spring";
    Logger logger = LoggerFactory.getLogger(WebSecurityConfig.class);

    public AADB2COidcLoginConfigurer configurer;

    @Autowired
    private ClientRegistrationRepository clientRegistrationRepository;

    @Value("${authorization.type}")
    private String authorizationType;


    public WebSecurityConfig(AADB2COidcLoginConfigurer configurer) {
        this.configurer = configurer;
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
                .authorizeRequests()
                .antMatchers("/", "/login", "/oauth/**", "/home", "/static/assets/**", "/assets/**", "/*.css", "/resources/**", "/h2/**").permitAll()
                .anyRequest()
                .authenticated()
                .and()
               // .apply(configurer)
               // .and()
                .oauth2Login()
                .authorizationEndpoint()
                .authorizationRequestResolver(new CustomAADB2CAuthorizationRequestResolver(clientRegistrationRepository))
                .and()
                .userInfoEndpoint()
                .oidcUserService(this.oidcUserService())
                .and()
                .successHandler(getAuthenticationSuccessHandler())
                //.defaultSuccessUrl("/list")
                .and()
                .logout().logoutSuccessUrl("/home").permitAll()
                .and()
                .exceptionHandling().accessDeniedPage("/403");
    }`

For springboot localization implementation follow this link.
https://www.baeldung.com/spring-boot-internationalization

Thank you very much for the support.
