### ISSUE TITLE
 storage spring boot starter

### ISSUE THREAD

**Issue by spoortijoshi** [microsoft/azure-spring-boot#695]
Environment: storage spring boot starter
OS Type: Windows
Java version: 11
  
The new azure-storage-spring-boot-starter version i.e 2.1.6 does not support File Storage Service. I wanted to know if it will added soon or is there another way to access it.

Thanks

**Comment by saragluna** [comment]
Thanks for reaching out to us. We'll evaluate this feature.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
