### ISSUE TITLE
Unresolvable Configurations in IntelliJ

### ISSUE THREAD

**Issue by florianrusch** [microsoft/azure-spring-boot#697]
## Environment
- Spring boot starter:
  - key vault spring boot starter
  
- OS Type: MacOS
- Java version: 
  
  - 11
  
## Summary

I've tested this guide to integrate the azure key vault in a spring boot application: https://docs.microsoft.com/en-gb/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault?view=azure-java-stable#sign-into-azure

Everything works as espected. Only IntelliJ is showing me the following message in the `application.yaml`:
![image](https://user-images.githubusercontent.com/1724759/62687792-c2d6d380-b9c7-11e9-97b9-f14020032d95.png)

Also the IntelliSense is not working for the key `azure.keyvault`. But I'm getting other stuff like this:
![image](https://user-images.githubusercontent.com/1724759/62688077-6b853300-b9c8-11e9-9f60-d14c8c758202.png)

## Reproduce steps

This is my `pom.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.6.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>de.fr.azure</groupId>
    <artifactId>keyvault</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>keyvault</name>
    <description>Demo project for Spring Boot</description>

    <properties>
        <java.version>11</java.version>
        <azure.version>2.1.6</azure.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-spring-boot-bom</artifactId>
                <version>${azure.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
```

## Expected Results

I would expect, that IntelliSense and also the resolving of the configuration works like for spring boot or other stuff.

**Comment by saragluna** [comment]
Thanks for reporting this, we'll look into it.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
