### ISSUE TITLE
ReadMe.md file is not insync with the code

### ISSUE THREAD

**Issue by zaabskr** [microsoft/azure-spring-boot#704]
## Environment
- Spring boot starter:
  - storage spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  - 1.8  

## Summary
The ReadMe.md file is not insync with the code. The code contains Upload, download, and list blobs by using the Java Storage SDK V10 version , while the read me contains  Java Storage SDK V7

## Reproduce steps
Java code & ReadMe.md

## Expected Results
Readme.md should be insync

**Comment by saragluna** [comment]
Thanks for reporting this issue, will keep them insync.

**Comment by saragluna** [comment]
We've deprecated the [storage starter](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-storage) in this project. We do also have another [starter](https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-starters/spring-starter-azure-storage) that implements the Spring Resource abstraction. 

Closing this issue.
