### ISSUE TITLE
MSI doesn't work with App Service

### ISSUE THREAD

**Issue by saragluna** [microsoft/azure-spring-boot#707]
## Environment
- Spring boot starter:
  
  - key vault spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  
  - 1.8

  

## Summary
MSI failes to work with App Service and server returns HTTP 400 response code

>Server returned HTTP response code: 400 for URL: http://172.19.0.2:8081/msi/token?resource=https://<keyvaultname>.vault.azure.net/&api-version=2017-09-01

**Comment by csellberg** [comment]
Just for reference. 

It seems that you have the exact same error when you try to authenticate against the Azure EventHub following the steps described here

https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples/eventhubs-binder-sample

then error received here is 

Server returned HTTP response code: 400 for URL: http://172.16.1.2:8081/msi/token?resource=https://management.core.windows.net/&api-version=2017-09-01

**Comment by saragluna** [comment]
@csellberg Thanks for your feedback. Could you please create an issue for it in `spring-cloud-azure` repo and kindly add more details like which version you're using, which kind of managed identity is being used?

**Comment by saragluna** [comment]
#718 has been merged, close the issue.

**Comment by Rakatashii** [comment]
any updates on solution?

**Comment by saragluna** [comment]
@Rakatashii this issue has been solved. Now MSI works with App Service.
