### ISSUE TITLE
Provide Webflux reference implementation as alternative

### ISSUE THREAD

**Issue by favetelinguis** [microsoft/azure-spring-boot#708]
Since Webflux is well supported in spring boot now but not supported by azure starter there should be an up to date reference implementation for integrating with Azure AD. Would it be possible to to make such an example in this repo or where should one turn to get help with this. Im stuck on getting it to work and the current documentation if fragmented and mostly focused on Spring MVC.

**Comment by neuqlz** [comment]
Hi favetelinguis,

Thanks for your feedback, we will consider it and give you a response later.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
