### ISSUE TITLE
Invalid Authorization Grant Type (client_credentials) for Client Registration with Id: azure

### ISSUE THREAD

**Issue by j-chao** [microsoft/azure-spring-boot#711]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter

  
- OS Type: Windows/Linux/MacOS
- Java version: 
  
  - 12 

## Summary
I am getting the following error in the logs when I try to configure the grant-type to client-credentials:

`Invalid Authorization Grant Type (client_credentials) for Client Registration with Id: azure
`

## Reproduce steps

The following configuration is specified in my application.properties file:

`spring.security.oauth2.client.registration.azure.authorization-grant-type=client_credentials
`

## Expected Results

Application should be able to authenticate with authorization to AzureAD, given the client-id and client-secret also specified in the application.properties file.  

## Actual Results

Application errors out with the following error:

`OAuth2AuthorizationRequestRedirectFilter : Authorization Request failed: java.lang.IllegalArgumentException: Invalid Authorization Grant Type (client_credentials) for Client Registration with Id: azure
`

**Comment by neuqlz** [comment]
Hi:
Thanks for your feedback, the AAD starter doesn't support this grant type now, your issue is similar to issue #549, you can view that issue's comment for more information.

**Comment by allan-xiazhan** [comment]
Looks you assigned to wrong people. 🙂


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
