### ISSUE TITLE
Use java-cfenv and create a cloudfoundry starter

### ISSUE THREAD

**Issue by eddumelendez** [microsoft/azure-spring-boot#712]
## Environment
- azure-spring-boot

## Summary

Currently, there is a [VCapProcessor.java](https://github.com/microsoft/azure-spring-boot/blob/master/azure-spring-boot/src/main/java/com/microsoft/azure/spring/cloundfoundry/environment/VcapProcessor.java) which allows to read `VCAP_SERVICES` environment variable. There is a lib [java-cfenv](https://github.com/pivotal-cf/java-cfenv) which make the code more readable. Also, this will bring another dependency to the classpath even when there is  no CloudFoundry, in order to fix that we can create a `azure-cloudfoundry-spring-boot-starter` which will offer this capability. 

If you agreed to do that, I am able to make that change.

WDYT?

**Comment by neuqlz** [comment]
So much thanks for your feedback, yeah sure, we are very glad you to contribute codes for us.
