### ISSUE TITLE
BOM has dependency management for Micrometer

### ISSUE THREAD

**Issue by snicoll** [microsoft/azure-spring-boot#716]
The `azures-spring-boot-bom` has [dependency management for Micrometer](https://github.com/microsoft/azure-spring-boot/blob/d2cf6c12afae92d88acb1953cbefc082ca1bbbb4/azure-spring-boot-bom/pom.xml#L50). When integrating an infrastructure such as Azure in a Spring Boot application, the project should align and reuse the dependencies managed by Spring Boot rather than having a dedicated opinion. 

I did create the issue here as I have no opinion how `azure-dependencies-bom` should behave so perhaps a fix is to import a different bom in this project.

**Comment by neuqlz** [comment]
Hi,
Thanks for your feedback, to be honest, I don't quite understand your ideas, can you give me more clarification? In this repo, BOM just used to manager all the jars related to Azure. And don't manage micrometer directly.

**Comment by snicoll** [comment]
Thanks for the quick reply. The link in my original description points to `azure-dependencies-bom` that this bom imports.

`azure-dependencies-bom` has [dependency management from Micrometer](https://search.maven.org/artifact/com.microsoft.azure/azure-dependencies-bom/2.1.0.M6/pom) so this one does as well.

**Comment by anumalasri** [comment]
MS Team,   
The latest version of Azure bom has incompatible micrometer version 
https://github.com/microsoft/azure-spring-boot/blob/v2.2.0/azure-spring-boot-parent/pom.xml

compared to 
https://github.com/spring-projects/spring-boot/blob/v2.2.0.RELEASE/spring-boot-project/spring-boot-dependencies/pom.xml

Appreciate your quick fix on this ..

Incorrect version is causing below error : 

```

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:
    org.springframework.boot.actuate.autoconfigure.metrics.orm.jpa.HibernateMetricsAutoConfiguration.bindEntityManagerFactoryToRegistry(HibernateMetricsAutoConfiguration.java:72)
The following method did not exist:
    io.micrometer.core.instrument.binder.jpa.HibernateMetrics.<init>(Lorg/hibernate/SessionFactory;Ljava/lang/String;Ljava/lang/Iterable;)V
The method's class, io.micrometer.core.instrument.binder.jpa.HibernateMetrics, is available from the following locations:
    jar:file:/C:/Users/.gradle/caches/modules-2/files-2.1/io.micrometer/micrometer-core/1.1.1/5f8063266f548b710ce06a090586a625f3d682b9/micrometer-core-1.1.1.jar!/io/micrometer/core/instrument/binder/jpa/HibernateMetrics.class
It was loaded from the following location:
    file:/C:/Users/.gradle/caches/modules-2/files-2.1/io.micrometer/micrometer-core/1.1.1/5f8063266f548b710ce06a090586a625f3d682b9/micrometer-core-1.1.1.jar
Action:
Correct the classpath of your application so that it contains a single, compatible version of io.micrometer.core.instrument.binder.jpa.HibernateMetrics
```

**Comment by snicoll** [comment]
Thanks for the nudge but that’s in the parent and the bom has been fixed (but this issue hasn’t been closed). There shouldn’t be any dependency management that is covered by the spring boot bom in there. Please remove micrometer, spring framework and the like please.

**Comment by anumalasri** [comment]
Thanks @snicoll ..  The issue got fixed with latest version 2.2.0.

**Comment by snicoll** [comment]
Thanks for the feedback. I still think the current build should be improved. I've created #757

**Comment by saragluna** [comment]
Since #757 has been closed, closing this now.
