### ISSUE TITLE
Please confirm compatibility with Spring Boot 2.2

### ISSUE THREAD

**Issue by snicoll** [microsoft/azure-spring-boot#719]
We're heading towards an RC1 of Spring Boot 2.2 soon, followed [by GA in Q4](https://github.com/spring-projects/spring-boot/milestones). Can you please confirm full compatibility of the starter with Spring Boot 2.2?

As soon as we hear from you, we can enable the starter again on start.spring.io, see https://github.com/spring-io/start.spring.io/issues/266

Thanks!

**Comment by neuqlz** [comment]
Thanks for your feedback. Don't worry about that, the confirmation work is on our schedule. We will get started after Spring Boot 2.2 has been released.

**Comment by neuqlz** [comment]
Thanks for your feedback. Don't worry about that, the confirmation work is on our schedule. We will get started after Spring Boot 2.2 RC1 has been released.

**Comment by snicoll** [comment]
I can see that you've release a milestone 1 on Maven Central. Can you share your plan for the `2.2` line and when the Azure integration is going to be GA?

**Comment by kushagraThapar** [comment]
> I can see that you've release a milestone 1 on Maven Central. Can you share your plan for the `2.2` line and when the Azure integration is going to be GA?

Hello @snicoll , the plan is on track. We will GA once spring-boot 2.2 is GA. 
Earlier this week, we have been working to catch up with spring-boot 2.2.0.M6, and 2.2.0.RC1. 

Next week, we will upgrade to 2.2.0.RC1, and then week after that, once 2.2.0 is out on October 16th, we will GA with 2.2.0

**Comment by snicoll** [comment]
So, closing this issue then I guess?

**Comment by kushagraThapar** [comment]
> So, closing this issue then I guess?

Let's keep this open for now. 
I will close this on October 7th will exact dates.

**Comment by jialindai** [comment]
Hi @snicoll, 
The azure-spring-boot 2.2.0.M1 has been tested based on spring boot 2.2.0.M6.
We will verify that this version also works with spring boot 2.2.0.RC1 starting from Oct 8, testing can be completed in 3 days.

Once spring boot 2.2.0.RELEASE is out (Oct 16 according to https://github.com/spring-projects/spring-boot/milestones), we will start release azure-spring-boot 2.2.0. The release can be complete in 1 week's time.

**Comment by kushagraThapar** [comment]
Plan for 2.2.0 has been shared, closing the issue now.
