### ISSUE TITLE
How to override or customize the login page for azure b2c

### ISSUE THREAD

**Issue by Xoryan** [microsoft/azure-spring-boot#720]
## Environment
- Spring boot starter:
  - azure-active-directory-b2c-spring-boot-starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  - 1.8

## Summary
The login page does not match the styling of the web application I am developing. I would like to override the login page with my own page so I can customize what shows on the page and the styles. 

## Reproduce steps
Run the azure-active-directory-b2c-oidc-spring-boot-sample and when you hit it you will see in-built login page. 

## Expected Results
I would like to change how the login page looks.

## Actual Results
I cannot find a way to change the login page.

**Comment by neuqlz** [comment]
Hi Xoryan, you can follow the docs of Spring-Security to customize your login page. I found some references in this link:https://docs.spring.io/spring-security/site/docs/current/guides/html5/form-javaconfig.html. You can also get more information by search it on google.

**Comment by Xoryan** [comment]
The documentation you sent, I had tried that yesterday before i submitted the ticket. I just tried it again. Did not have any affect. So I removed from the POM azure-active-directory-b2c-spring-boot-starter. I removed all references to azure-active-directory-b2c-spring-boot-starter in the security file and started the app. This time it redirected to my custom login page just fine. So I conclude the azure-active-directory-b2c-spring-boot-starter overrides the login page functionality. Please let me know if there is a way to customize the login page. What would make sense if there was a property in the application.yml file to specify a new login page.

**Comment by saragluna** [comment]
@Xoryan 
Take the sample project for example, according to the reference link @neuqlz provided, we could set the custom login page in `configure()` function:

``` java
// add to the end
.and().oauth2Login().loginPage("/login").permitAll();
```

**Comment by Xoryan** [comment]
It works with oath2Login(). All the tutorials I found had .formLogin. Thanks!

**Comment by Xoryan** [comment]
I tested this. 
* I was able to display a custom logn page. 
* I clicked on the link to the login workflow
* Brought me to the microsoft login. 
* I logged in and it redirected me back to the login page.
* I cleared cookies and restarted the browser
* I am still stuck in a loop on the login page.

I am thinkiing since I overrid the login page, there are now some other settings i need to specify in the Security config now. I found this link https://docs.spring.io/spring-security/site/docs/5.0.7.RELEASE/reference/html/oauth2login-advanced.html, but i am not sure the values i should put. Can either update the sample with a custom login page or jsut send me the custom settiings i need to make the custom login page work.

**Comment by saragluna** [comment]
Could you please provide more details about your AAD B2C configurations, your application properties, the version of the starter and your Spring Security config?

**Comment by Xoryan** [comment]
I used the azure B2C sample application as my base. This should be reproducable on your end with the sample application and add custom login. 

Starter version: 2.1.6.RELEASE

application.yml
azure:
  activedirectory:
    b2c:
      tenant: crscustomersdev
      oidc-enabled: true
      client-id: <removed>
      client-secret: <removed>
      reply-url: http://localhost:8080/ # should be absolute url.
      logout-success-url: http://localhost:8080/login
      user-flows:
        sign-up-or-sign-in: B2C_1A_signup_signin
        # profile-edit: B2C_1_profileediting1  # optional
        password-reset: B2C_1A_PasswordReset # optional

Spring Security Config:
        http
        	.authorizeRequests()
        		.antMatchers("/resources/**").permitAll() 
        		.anyRequest().authenticated()
        		.and()  
        	.oauth2Login().loginPage("/login").permitAll()
        	.and()
        		.apply(configurer)
        ;

Note: I also reproduced this behaviour with my copy of the sample of the application. Let me know if you need anything else.

**Comment by saragluna** [comment]
Have you also created the view controller, according to the [doc](https://docs.spring.io/spring-security/site/docs/current/guides/html5/form-javaconfig.html#configuring-a-login-view-controller)? And one more thing need to be taken care of is the reply url, make sure it is the same as configured in AAD B2C.

**Comment by Xoryan** [comment]
The default login page just has a link for the sign in workflow to bring them to the microsoft login page. I had wanted to customize the look of that page to make it match the application. But, i was reading about SSO with OAUTH 2.0 (https://spring.io/guides/tutorials/spring-boot-oauth2/#_social_login_simple) and see that it can be configured to automatically direct to the external login page using the @EnableOAuth2Sso annotation. That would be ideal if my application could do the same thing, then i wouldn't need a custom login as it would automatically redirect to the login page if not logged in. Is there functionality like this for Azure AD B2C?

https://spring.io/guides/tutorials/spring-boot-oauth2/#_social_login_simple

**Comment by saragluna** [comment]
I'm not sure whether @EnableOAuth2Sso will work with Azure AD B2C, need to look into it.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
