### ISSUE TITLE
Remove `repository` declarations from published pom

### ISSUE THREAD

**Issue by snicoll** [microsoft/azure-spring-boot#728]
Released artifacts have pom metadata with `repository` declaration. When that happens and such artifact is added as a dependency, Maven will use the declared repositories as a source to download all artifacts (not only the one related to the dependency). 

This is a major issue for users behind a corporate proxy as they don't want Maven to start hitting a service they don't have access to. I guess this would slow down things as I am expecting maven to reach out to get some metadata from each of them.

`asure-spring-boot-bom` currently has such declaration on the spring milestones repo and it should be removed. For the record, we use the `flatten-maven-plugin` to clean up poms before they are published. It allows us to remove build specific settings when publishing so that it doesn't pollute user's builds.

**Comment by saragluna** [comment]
Thanks for pointing it out and the setting will be removed.

**Comment by saragluna** [comment]
`repository` has been removed in 2.2.0 so close this issue.
