### ISSUE TITLE
Not considering azure.activedirectory.tenant-id

### ISSUE THREAD

**Issue by CatchSandeepVaid** [microsoft/azure-spring-boot#731]
I have multiple directories configured in my organization's azure  AD.
I have specified azure.activedirectory.tenant-id in my application.properties file but when i try to access my app, it takes other tenant-id instead of what is configured with azure.activedirectory.tenant-id

**Comment by neuqlz** [comment]
Thanks for your feedback, can you give particular steps to reproduce your problem? I  don't quite catch your meaning.

**Comment by jialindai** [comment]
@CatchSandeepVaid, could you also provide more details, like:

-  which starter are you using?
-  which version of spring and java?
-  what's your main scenario interact with Azure AD?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
