### ISSUE TITLE
Errors while upgrading azure-spring-boot-bom version

### ISSUE THREAD

**Issue by ravisgaur** [microsoft/azure-spring-boot#734]
## Environment
- Spring boot starter:
  - key vault spring boot starter
  
- OS Type: Windows
- Java version: 
  - 11
  

## Summary
Hi Team, I am trying to upgrade 'azure-spring-boot-bom' version from 2.1.6 to 2.2.0.M1
and getting the errors in the below imports as not found:

import org.apache.http.conn.ssl.SSLConnectionSocketFactory;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.ssl.TrustStrategy;

Below is my code of the bean:

@Bean
  @ConditionalOnMissingBean
  public RestTemplate restTemplate()
      throws KeyManagementException, NoSuchAlgorithmException, KeyStoreException {

    // Todo Change rest template when the certificate issue get resolved.

    /* Trust Strategy for X509Certificate. */
    TrustStrategy acceptingTrustStrategy =
        (X509Certificate[] chain, String authType) -> true;

    SSLContext sslContext = org.apache.http.ssl.SSLContexts.custom()
        .loadTrustMaterial(null, acceptingTrustStrategy)
        .build();

    SSLConnectionSocketFactory connectionSocketFactory =
        new SSLConnectionSocketFactory(sslContext);

    CloseableHttpClient httpClient = HttpClients.custom()
        .setSSLSocketFactory(connectionSocketFactory)
        .build();

    /* Creating HttpComponents Request factory. */
    HttpComponentsClientHttpRequestFactory requestFactory =
        new HttpComponentsClientHttpRequestFactory();

    /* Setting HttpClient in request Factory. */
    requestFactory.setHttpClient(httpClient);

    RestTemplate restTemplate = new RestTemplate(requestFactory);

    /* Setting request factory in rest template. */
    restTemplate.setRequestFactory(requestFactory);

    /* Setting interceptors in rest template. */
    restTemplate
        .setInterceptors(Collections.singletonList(new CorrelationIdInterceptor()));

    return restTemplate;
  }

## Reproduce steps
change the value of azure.version from 2.1.6 to 2.2.0.M1
`<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.microsoft.azure</groupId>
				<artifactId>azure-spring-boot-bom</artifactId>
				<version>${azure.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>`

## Expected Results
code to compile

## Actual Results
code in giving errors

**Comment by moarychan** [comment]
Hi @ravisgaur , is your problem solved? if not, could you replace with a higer version?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
