### ISSUE TITLE
how to validate access_token on the backend

### ISSUE THREAD

**Issue by hunao0221** [microsoft/azure-spring-boot#741]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  
- OS Type: Windows
- Java version: 
  
  - 1.8
  
## Summary

Hi, I request a access_token and refresh_token from https://login.microsoftonline.com/{tenant}/oauth2/token on the backend which base on SpringBoot and response to frontend.

and then frontend send a request to backend api with access_token, the question is how to validate access_token on the backend ? and we alse use Sring Security.

At the moment I did't found any suggestions.

I'm looking forward to your reply
## Reproduce steps

1. Configuration My Springboot application.
2. send a request to [https://login.microsoftonline.com/{tenant}/oauth2/token](https://login.microsoftonline.com/{tenant}/oauth2/token) and I can get access_token and refresh_token from the response.  and then return it to frontend
3. frontend send a request to my Springboot Application with access_token
4. I don't konw how to validate access_token or refresh_token, and we use Spring Security. The front end and the back end are completely separate

## Expected Results

Verify the token on success and, if successful, return the correct data

## Actual Results

I don't konw how to validate access_token or refresh_token,

**Comment by neuqlz** [comment]
Thanks for your feedback, we will inspect it later.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
