### ISSUE TITLE
Upgrade to Spring Boot 2.2.0.RELEASE

### ISSUE THREAD

**Issue by snicoll** [microsoft/azure-spring-boot#742]
Now that Spring Boot 2.2 is GA, we need a release that integrates with the GA as well. Right now, there is a release on Maven Central that relies on artifacts that depend on repo.spring.io/milestone. This arrangement is failing our verification tests so I've disabled Azure in 2.2 again.

We'll restore as soon there is a release with Maven Central only artifacts.

Please make sure to fix #728 before releasing. A fix for #716 would be appreciated as well.

**Comment by saragluna** [comment]
Sure, we're planning to do the 2.2 release in the coming days. #728 will be taken care of and I believe #716 has already been fixed.

**Comment by neuqlz** [comment]
thank you, we have fixed that issues in 2.2.0.
