### ISSUE TITLE
unable to use azure-active-directory-b2c-spring-boot-starter

### ISSUE THREAD

**Issue by jyotsnaravikumar** [microsoft/azure-spring-boot#750]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  
- OS Type: Windows/Linux/MacOS
 - macOS

- Java version: 
  - 1.8

  

## Reproduce steps
https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc?view=azure-java-stable
Hello I am working on getting a token from aadb2c using above docs
Followed steps on setting up maven project, code and pom has the same contents as in docs.
Upon running mvn clean install
Error is thrown as:
Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.microsoft.azure.spring.autoconfigure.b2c.AADB2COidcLoginConfigurer' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**Comment by neuqlz** [comment]
Thanks for your feedback, and could you provide the version of the starter you used?

**Comment by saragluna** [comment]
@jyotsnaravikumar Any updates on this issue?

**Comment by saragluna** [comment]
Close issue.
