### ISSUE TITLE
Possibility to specify multiple KeyVaults to connect to and mount all secrets as config props.

### ISSUE THREAD

**Issue by olialth** [microsoft/azure-spring-boot#759]
## Environment
- Spring boot starter:
  - key vault spring boot starter
  
- OS Type: Linux
- Java version: 
  - 1.8
  

## Summary
Possibility to specify multiple KeyVaults to connect to and mount all secrets as config props.

[On behalf of Daimler TSS GmbH](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

**Comment by olialth** [comment]
Is this a feature that makes sense? If yes, I could also implement an addition to the lib to provide that one...

**Comment by neuqlz** [comment]
Hi @olialth 
Sorry for the late reply, what you mentioned is a new feature indeed, we don't support this currently. And also, we very welcome you contribute to us, but we need some days to investigate the reasonability of the feature. We will give you a response in 1~2 days.

**Comment by neuqlz** [comment]
Hi @olialth 
After some discussion, we think that your proposal is reasonable, and very welcome you to contribute for us. But there are two points you need to pay attention to:
1. the usability of the keyvault-starter: make sure the starter is easy to use which means the configuration for keyvault-starter must be easy.
2. backward compatibility: make sure the new library is compatible with the old properties.

There are my suggestions of the properties or YAML file: 
`
# old
azure.keyvault.enabled=false
azure.keyvault.token-acquire-timeout-seconds=60
azure.keyvault.refresh-interval=1800000
azure.keyvault.client-id=put-your-azure-client-id-here
azure.keyvault.client-key=put-your-azure-client-key-here
azure.keyvault.uri=put-your-azure-keyvault-uri-here
azure.keyvault.secret.keys=key1,key2,key3

# new
# it must be compatible with the old configuration
azure.keyvault.enabled=true
azure.keyvault.token-acquire-timeout-seconds=60
azure.keyvault.refresh-interval=1800000
azure.keyvault.client-id= testid
azure.keyvault.client-key= testkey

# key: uri value: secret keys.
azure.keyvault.uris.uri1= key1,key2,key3
azure.keyvault.uris.uri2= key1,key2,key3
azure.keyvault.uris.uri3= key1,key2,key3
`
`
# old
azure:
    keyvault:
        client-id: put-your-azure-client-id-here
        client-key: put-your-azure-client-key-here
        enabled: true
        refresh-interval: 1800000
        secret:
            keys: key1,key2,key3
        token-acquire-timeout-seconds: 60
        uri: put-your-azure-keyvault-uri-here

# new
# it must be compatible with the old configuration
azure:
    keyvault:
        client-id: testid
        client-key: testkey
        enabled: true
        refresh-interval: 1800000
        token-acquire-timeout-seconds: 60
        uris:
            uri1: key1,key2,key3
            uri2: key1,key2,key3
            uri3: key1,key2,key3
`

**Comment by neuqlz** [comment]
Hi @olialth
After some discussion, we think that your proposal is reasonable, and very welcome you to contribute for us. But there are two points you need to pay attention to:

the usability of the keyvault-starter: make sure the starter is easy to use which means the configuration for keyvault-starter must be easy.
backward compatibility: make sure the new library is compatible with the old properties.
There are my suggestions of the properties or YAML file:
`# old
azure.keyvault.enabled=false
azure.keyvault.token-acquire-timeout-seconds=60
azure.keyvault.refresh-interval=1800000
azure.keyvault.client-id=put-your-azure-client-id-here
azure.keyvault.client-key=put-your-azure-client-key-here
azure.keyvault.uri=put-your-azure-keyvault-uri-here
azure.keyvault.secret.keys=key1,key2,key3

# new
# it must be compatible with the old configuration
azure.keyvault.enabled=true
azure.keyvault.token-acquire-timeout-seconds=60
azure.keyvault.refresh-interval=1800000
azure.keyvault.client-id= testid
azure.keyvault.client-key= testkey

# key: uri value: secret keys.
azure.keyvault.uris.uri1= key1,key2,key3
azure.keyvault.uris.uri2= key1,key2,key3
azure.keyvault.uris.uri3= key1,key2,key3`
`# old
azure:
    keyvault:
        client-id: put-your-azure-client-id-here
        client-key: put-your-azure-client-key-here
        enabled: true
        refresh-interval: 1800000
        secret:
            keys: key1,key2,key3
        token-acquire-timeout-seconds: 60
        uri: put-your-azure-keyvault-uri-here

# new
# it must be compatible with the old configuration
azure:
    keyvault:
        client-id: testid
        client-key: testkey
        enabled: true
        refresh-interval: 1800000
        token-acquire-timeout-seconds: 60
        uris:
            uri1: key1,key2,key3
            uri2: key1,key2,key3
            uri3: key1,key2,key3`

**Comment by neuqlz** [comment]
Hi @olialth
After some discussion, we think that your proposal is reasonable, and very welcome you to contribute for us. But there are two points you need to pay attention to:

the usability of the keyvault-starter: make sure the starter is easy to use which means the configuration for keyvault-starter must be easy.
backward compatibility: make sure the new library is compatible with the old properties.
There are my suggestions of the properties or YAML file:

`
//old
azure:
    keyvault:
        client-id: put-your-azure-client-id-here
        client-key: put-your-azure-client-key-here
        enabled: true
        refresh-interval: 1800000
        secret:
            keys: key1,key2,key3
        token-acquire-timeout-seconds: 60
        uri: put-your-azure-keyvault-uri-here
//new
//it must be compatible with the old configuration
azure:
    keyvault:
        client-id: testid
        client-key: testkey
        enabled: true
        refresh-interval: 1800000
        token-acquire-timeout-seconds: 60
        uris:
            uri1: key1,key2,key3
            uri2: key1,key2,key3
            uri3: key1,key2,key3
//old
azure.keyvault.enabled=false
azure.keyvault.token-acquire-timeout-seconds=60
azure.keyvault.refresh-interval=1800000
azure.keyvault.client-id=put-your-azure-client-id-here
azure.keyvault.client-key=put-your-azure-client-key-here
azure.keyvault.uri=put-your-azure-keyvault-uri-here
azure.keyvault.secret.keys=key1,key2,key3

//new
//it must be compatible with the old configuration
azure.keyvault.enabled=true
azure.keyvault.token-acquire-timeout-seconds=60
azure.keyvault.refresh-interval=1800000
azure.keyvault.client-id= testid
azure.keyvault.client-key= testkey

// key: uri value: secret keys.
azure.keyvault.uris.uri1= key1,key2,key3
azure.keyvault.uris.uri2= key1,key2,key3
azure.keyvault.uris.uri3= key1,key2,key3
`

**Comment by neuqlz** [comment]
Hi @olialth
After some discussion, we think that your proposal is reasonable, and we very welcome you to contribute for us. But there are two points you need to pay attention to:
1.  usability of the keyvault-starter: make sure the starter is easy to use which means the configuration for keyvault-starter must be easy.
2. backward compatibility: make sure the new library is compatible with the old properties.
There are my suggestions for the properties or YAML file:

`// old
azure:
  keyvault:
    client-id: put-your-azure-client-id-here
    client-key: put-your-azure-client-key-here
    enabled: true
    refresh-interval: 1800000
    token-acquire-timeout-seconds:60
    uri: put-your-azure-keyvault-uri-here
  secret:
    keys: key1,key2,key3`

**Comment by neuqlz** [comment]
Hi @olialth
After some discussion, we think that your proposal is reasonable, and we very welcome you to contribute for us. But there are two points you need to pay attention to:
1.  usability of the keyvault-starter: make sure the starter is easy to use which means the configuration for keyvault-starter must be easy.
2. backward compatibility: make sure the new library is compatible with the old properties.

There are my suggestions for the properties or YAML file:
``` 
# properties file
# old
azure.keyvault.enabled=false
azure.keyvault.token-acquire-timeout-seconds=60
azure.keyvault.refresh-interval=1800000
azure.keyvault.client-id=put-your-azure-client-id-here
azure.keyvault.client-key=put-your-azure-client-key-here
azure.keyvault.uri=put-your-azure-keyvault-uri-here
azure.keyvault.secret.keys=key1,key2,key3
# new
azure.keyvault.enabled=true
azure.keyvault.refresh-interval=1800000
azure.keyvault.token-acquire-timeout-seconds=60
azure.keyvault.client-id=testid
azure.keyvault.client-key=testkey
azure.keyvault.vaults=[{uri=my-uri-1,secret={keys=[key1,key2]}},{uri=my-uri-2,secret={keys=[key1,key2]}}]
```

```
# YAML file
# old
azure:
  keyvault:
    client-id: put-your-azure-client-id-here
    client-key: put-your-azure-client-key-here
    enabled: true
    refresh-interval: 1800000
    token-acquire-timeout-seconds:60
    uri: put-your-azure-keyvault-uri-here
  secret:
    keys: key1,key2,key3

# new
azure:
  keyvault:
    enabled:true
    refresh-interval:1800000
    token-acquire-timeout-seconds:60
    client-id:testid
    client-key:testkey
  vaults:
    - uri:my-uri-1
      secret:
        keys:
          - key1
          - key2
    - uri:my-uri-2
      secret:
        keys:
          -key1
          -key2
```

And, If the two properties come up together, we must make sure all keyvaults are mounted, for example:
>   azure.keyvault.uri=uri1
  azure.keyvault.secret.keys=key1,key2,key3
  azure.keyvault.vaults=[{uri=uri2,secret={keys=[key1,key2]}},{uri=uri3,secret={keys=[key1,key2]}}]

uri1 and uri2,3 should all be mounted.

**Comment by saragluna** [comment]
The feature of multiple key vaults is supported now. Check here: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-keyvault-secrets#multiple-key-vault-support. 

Closing this issue now.
