### ISSUE TITLE
ServiceBus starter IllegalArgumentException refers to wrong property

### ISSUE THREAD

**Issue by zoladkow** [microsoft/azure-spring-boot#765]
## Environment
- Spring boot starter:
  - service bus spring boot starter

  
- OS Type: Windows
- Java version: 
  - 1.8
  

## Summary
Switching from plain azure-servicebus to azure-servicebus-jms-spring-boot-starter results in following autoconfiguration exception: 
```
Error creating bean with name 'spring.jms.servicebus-com.microsoft.azure.spring.autoconfigure.jms.AzureServiceBusJMSProperties': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: 'azure.servicebus.jms.connection-string' should be provided
```

## Reproduce steps
Have a working azure-servicebus project, add azure-servicebus-jms-spring-boot-starter with a new `@JmsListener` annotated controller. Run the project.

## Expected Results
Should just run. OR better - report a CORRECT error message.

## Actual Results
Stands to reason that we should have updated the `application.yml` properties as shown in docs or in the tutorial, that's on us. **But** the message from the exception was misleading and sent us in a wrong direction. 

The message says `'azure.servicebus.jms.connection-string'` is missing, while the starter actually expects `'spring.jms.servicebus.connection-string'`.

**Comment by saragluna** [comment]
Thanks for your contribution.
