### ISSUE TITLE
Handle AdalClaimsChallengeException

### ISSUE THREAD

**Issue by jialindai** [microsoft/azure-spring-boot#767]
Handle AdalClaimsChallengeException and redirect the user to the authorization endpoint with the claims:

See: https://github.com/AzureAD/azure-activedirectory-library-for-java/blob/dev/src/samples/web-app-samples-for-adal4j/src/main/java/com/microsoft/aad/adal4jsample/AadController.java#L208

Some investigation is needed for this proposed solution:
- Confirm the situations the problem happen
- Ensure the user flow is reasonable

**Comment by chufgard** [comment]
This issue is based on this report: https://github.com/microsoft/azure-spring-boot/issues/722

**Comment by neuqlz** [comment]
Now this issue has been fixed in latest SNAPSHOT version.
