### ISSUE TITLE
Why LIST access is required along with GET access to read secret from key-vault when using Azure Spring Boot 

### ISSUE THREAD

**Issue by mhunter77** [microsoft/azure-spring-boot#784]
## Environment
- Spring boot starter:  - key vault spring boot starter
 - OS Type: MacOS          
- Java version:  - 1.8
  
  

## Summary
**QUESTION – RELATING TO ACCESSING THE SECRET FROM KEY VAULT USING SPRING_BOOT STARTER DEPENDENCY**
--------------------------------------------------
Why LIST access is required along with GET access to read secret from key-vault?

The customer is using the document https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault?view=azure-java-stable .
When accessing the secret from key-vault using the below spring-boot starter dependency and using it in spring boot program, I see that, the code is performing a “list” operation at first to fetch the secret from obtained list from key vault.
POM Dependency:

<dependency>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
                <version>2.1.7</version>
                 <scope>runtime</scope>
</dependency>

Could you please clarify if it by design or do we have another approach to resolve this?

**DETAILS**
-------------------
I looked at the step 4 of the article " https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault?view=azure-java-stable "  
     4. Set the access policy for the Azure service principal you created earlier; for example:
     az keyvault set-policy --name wingtiptoyskeyvault --secret-permission set get list delete --spn "iiiiiiii-iiii-iiii-iiii-iiiiiiiiiiii"
I see that list is required in the setup above in step 4.
It may be that at some point in the code it is performing a “Get-secrets” which requires the list command
-----------------------------------------
Get Secrets - Get Secrets
https://docs.microsoft.com/en-us/rest/api/keyvault/getsecrets/getsecrets 
Service: Key Vault 
API Version: 7.0 
List secrets in a specified key vault.
The Get Secrets operation is applicable to the entire vault. However, only the base secret identifier and its attributes are provided in the response. Individual secret versions are not listed in the response. This operation requires the secrets/list permission.

## Reproduce steps
See above

## Expected Results
When using the azure-spring-boot, the  LIST access is NOT required along with GET access to read secret from key-vault

## Actual Results
When using the azure-spring-boot, the  LIST access is required along with GET access to read secret from key-vault

**Comment by saragluna** [comment]
Thanks for reaching out to us. We'll investigate it.

**Comment by saragluna** [comment]
The **LIST** operation is needed when no secrets are specified in the application.properties, otherwise the application will have no idea which secrets to load except listing all of them. So the problem could be solved by adding `azure.keyvault.secret.keys=your-key1, your-key2, your-key3` to the application.properties.

But since version 2.1.7 keyvault-starter does not support this feature, so if you want to use this feature please try our 2.1.8-SNAPSHOT version with spring-boot 2.1.x and 2.2.0 version with spring-boot 2.2.x.
