### ISSUE TITLE
Message converter and JMS message acknowledge

### ISSUE THREAD

**Issue by carcaryn** [microsoft/azure-spring-boot#792]
Hi,
I ask you a question about spring azure service bus and jms configuration.
What is the best way to configure azure service bus and spring jms to apply a JSON conversion for messages? I've tried to configure a message converter and with this approch, I've overridden the default JmsTemplate bean config where I've put JacksonConverter in JmsTemplate's dependencies: in this way, I've been able to send a text message with json body correctly, but when I've tried to read the message in JMSListener the conversion failed. 

Also, It's possibile to configure manual acknowledge in JmsListener? 
Thanks in advance and I apologize for my awfull English.
Cristian

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
