### ISSUE TITLE
client-runtime dependency version mismatch 

### ISSUE THREAD

**Issue by anumalasri** [microsoft/azure-spring-boot#794]
## Environment
- Spring boot starter:
  
   - key vault spring boot starter
  - storage spring boot starter
  
- OS Type:  Linux - Java version: 
  
  - 1.8
 
  

## Summary

When we use both Key Valut and Storage dependencies are used in an Application,  two versions of  _client-runtime_ dependency has resolved..  Due to multiple versions and jars,  Application startup failed during Key Vault interaction.

## Reproduce steps

Use below dependencies and dependency management in build.gradle file ..
```
dependencies {
 
 	compile "com.microsoft.azure:azure-storage-spring-boot-starter"
 	compile 'com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter' 

	compile 'com.microsoft.azure:applicationinsights-logging-log4j2'
	runtime 'com.microsoft.azure:applicationinsights-spring-boot-starter'
	
}

dependencyManagement {
	imports {
		mavenBom "com.microsoft.azure:azure-spring-boot-bom:2.2.0"
	}
}
```

Gradle dependency insight will explain different versions 

 ```
> Task :dependencyInsight
 
**com.microsoft.azure:azure-client-runtime:1.6.13**
\--- com.microsoft.azure:azure-client-authentication:1.6.13
     \--- com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter:2.2.0
          \--- compileClasspath (requested com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter)

 
com.microsoft.rest:client-runtime:1.6.13
\--- com.microsoft.azure:azure-client-runtime:1.6.13
     \--- com.microsoft.azure:azure-client-authentication:1.6.13
          \--- com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter:2.2.0
               \--- compileClasspath (requested com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter)

com.microsoft.rest:client-runtime:1.6.12 -> 1.6.13
\--- com.microsoft.azure:azure-keyvault:1.2.2
     \--- com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter:2.2.0
          \--- compileClasspath (requested com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter)
 
**com.microsoft.rest.v2:client-runtime:2.0.2**
\--- com.microsoft.azure:azure-storage-blob:10.5.0
     \--- com.microsoft.azure:azure-storage-spring-boot-starter:2.2.0
          \--- compileClasspath (requested com.microsoft.azure:azure-storage-spring-boot-starter)

```

## Expected Results

Azure Spring Boot should able to resolve **same dependency version** for all of their spring starters. 

## Actual Results

Below dependency and their transitive dependencies are resolved and both versions are available in Spring Boot JAR
 com.microsoft.rest.v2:client-runtime:2.0.2  - client-runtime-2.0.2.jar
 com.microsoft.rest:client-runtime:1.6.13 -- client-runtime-1.6.13.jar

Hence, we are getting below error during KeyVault interaction..

```
Application run failed

java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl;
	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:458) ~[retrofit-2.5.0.jar:?]
	at com.microsoft.rest.RestClient$Builder.build(RestClient.java:544) ~[client-runtime-1.6.13.jar:?]
	at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessorHelper.addKeyVaultPropertySource(KeyVaultEnvironmentPostProcessorHelper.java:61) ~[azure-spring-boot-2.2.0.jar:?]
	at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessor.postProcessEnvironment(KeyVaultEnvironmentPostProcessor.java:26) ~[azure-spring-boot-2.2.0.jar:?]
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:177) ~[spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:165) ~[spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	 
```

**Comment by saragluna** [comment]
Thanks for reporting this issue and sorry for the inconvenience. We'll investigate this and try to fix it. Meanwhile, have you tried to specify the okhttp3 version explicitly in your project to circumvent this error temporarily?

**Comment by saragluna** [comment]
Hi, @anumalasri. After digging a little deeper I find that this problem is caused by wrong `okhttp` package in the classpath, and `com.microsoft.rest.v2:client-runtime` has no dependency on `okhttp`. So could you please check the versions of `okhttp` in your project? And one more thing I have to check with you is which version of azure-spring-boot do you use? Since the bom version is 2.1.7 while the starter version 2.2.0 in your description.

**Comment by anumalasri** [comment]
Hi @saragluna .. As per the Stacktrace,  `client-rutnime` has transitive dependency on `retrofit` and `okhttp` jars.  
Some reason, okhttp3 jar version got messedup and below versions got resolved in my project.. 

```
com.squareup.okhttp3:okhttp:3.12.0 -> 3.8.1
com.squareup.okhttp3:logging-interceptor:3.8.1
com.squareup.okhttp3:okhttp-urlconnection:3.12.2
```

I am working to find out how these version got resolved and how to override these versions

**Comment by saragluna** [comment]
Any update on this issue?

**Comment by anumalasri** [comment]
@saragluna  .. 

I have to override these dependencies and vesions, inorder to make my applicaton work.

```
implementation 'com.squareup.okhttp3:logging-interceptor:3.12.2' 
implementation 'com.squareup.okhttp3:okhttp:3.12.2'	
```

I could not able to figure out why wrong version was resolved. I am suspecting combination of all 3 boms ..

```
mavenBom "org.springframework.boot:spring-boot-dependencies:2.1.9.RELEASE"
mavenBom "org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR3"
mavenBom "com.microsoft.azure:azure-spring-boot-bom:2.2.0"
```

**Comment by anumalasri** [comment]
I tried to resolve versions with difference bom versions..  All of them resulted in version difference among http3 jars.. Here are the details and hope this helps you further.


```
mavenBom "org.springframework.boot:spring-boot-dependencies:2.1.9.RELEASE"
mavenBom "org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR3"
mavenBom "com.microsoft.azure:azure-spring-boot-bom:2.1.7

com.squareup.okhttp3:okhttp:3.11.0 -> 3.8.1
com.squareup.okhttp3:logging-interceptor:3.11.0 -> 3.8.1
com.squareup.okhttp3:okhttp-urlconnection:3.11.0

====

mavenBom "org.springframework.boot:spring-boot-dependencies:2.1.9.RELEASE"
mavenBom "org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR3"
mavenBom "com.microsoft.azure:azure-spring-boot-bom:2.2.0

com.squareup.okhttp3:okhttp:3.12.2 -> 3.8.1
com.squareup.okhttp3:logging-interceptor:3.12.2 -> 3.8.1
com.squareup.okhttp3:okhttp-urlconnection:3.12.2

====

mavenBom "org.springframework.boot:spring-boot-dependencies:2.2.1.RELEASE"
mavenBom "org.springframework.cloud:spring-cloud-dependencies:Hoxton.RELEASE"
mavenBom "com.microsoft.azure:azure-spring-boot-bom:2.2.1"

com.squareup.okhttp3:okhttp:3.14.4 -> 3.12.0
com.squareup.okhttp3:logging-interceptor:3.12.2 -> 3.12.0
com.squareup.okhttp3:okhttp-urlconnection:3.12.2 -> 3.14.4

```

BTW.. I am using Gradle 6.0.1 along with Spring Dependency management..

I have attached `build.gradle` here 
https://gist.github.com/anumalasri/9a1427a0565c68cc0d747c894620ca59

**Comment by saragluna** [comment]
Thanks for your thorough analysis. The problem could be introduced by incompatible versions between Spring Boot, Spring Cloud,  and Azure Spring Boot. 
Spring Cloud Greenwich builds on top of Spring Boot 2.1.x and Horton of 2.2.x. Azure Spring Boot's major version follows Spring Boot, 2.1.x aligns with Spring Boot 2.1.x, and so does 2.2.x. So the second combination is expected to encounter mismatch of dependencies.

**Comment by anumalasri** [comment]
> Thanks for your thorough analysis. The problem could be introduced by incompatible versions between Spring Boot, Spring Cloud, and Azure Spring Boot.
> Spring Cloud Greenwich builds on top of Spring Boot 2.1.x and Hoxton of 2.2.x. Azure Spring Boot's major version follows Spring Boot, 2.1.x aligns with Spring Boot 2.1.x, and so does 2.2.x. So the second combination is expected to encounter mismatch of dependencies.

@saragluna 

I believe these are correct version as per Spring Initializer..  If not, please correct bom versions .. 
```
mavenBom "org.springframework.boot:spring-boot-dependencies:2.2.1.RELEASE"
mavenBom "org.springframework.cloud:spring-cloud-dependencies:Hoxton.RELEASE"
mavenBom "com.microsoft.azure:azure-spring-boot-bom:2.2.1"
```
However, above BOM combination also resulting different versions among http3 dependencies. 

com.squareup.okhttp3:okhttp:3.14.4 -> _3.12.0_
com.squareup.okhttp3:logging-interceptor:3.12.2 -> _3.12.0_
com.squareup.okhttp3:okhttp-urlconnection:3.12.2 -> **3.14.4**

Do you think above versions will work without any compatibility issue ?

**Comment by saragluna** [comment]
Sorry for the late response. I am not sure whether there will be a compatibility issue in your runtime,  since there is indeed conflict between dependency versions, however it depends on whether that will be called. Here you could check okhttp’s changelog https://square.github.io/okhttp/changelog_3x/. 

Since 3.12.2 is introduced by azure-client-runtime so we will reach out to them to see what we could do. Have you encountered any runtime errors yet caused by this issue with 2.2.1 version? Sorry for the inconvenience.
