### ISSUE TITLE
Save "long" type, it automatically convert to "string" type

### ISSUE THREAD

**Issue by truyenbka** [microsoft/azure-spring-boot#798]
## Environment
- spring-boot-starter-parent:2.1.3.RELEASE
- spring-data-gremlin-boot-starter

  
- OS Type:MacOS
- Java version: 
  - 1.8
  

## Summary
Maven POM file:
https://mvnrepository.com/artifact/com.microsoft.azure/spring-data-gremlin-boot-starter/2.2.1
```
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>spring-data-gremlin-boot-starter</artifactId>
    <version>2.2.1</version>
</dependency>
```

## Reproduce steps

- I want to store unix time into cosmos DB. So the entity has a **long** type variable:
_private long createdDate;_
- Using repository to save the entity

## Expected Results
- Cosmos DB should store it with **long** value

## Actual Results
- Cosmos DB stores it with **string** value

**Comment by neuqlz** [comment]
@truyenbka Good suggestion, but in the short term, we will not consider adding this feature to spring-data-gremlin, and PR is welcome

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
