### ISSUE TITLE
azure.keyvault.secret.keys cannot have white space

### ISSUE THREAD

**Issue by jialindai** [microsoft/azure-spring-boot#800]
## Environment
- Spring boot starter:
  - key vault spring boot starter (version 2.1.7, 2.2.0, 2.2.1)
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  - 1.8

## Summary
If there is whitespace in keys, there is error.

## Expected Results
Data binding API should be used so the behavior is aligned with Spring framework.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
