### ISSUE TITLE
Getting Groups with AzureADGraphClient throws NullpointerException for azure.activedirectory.environment=global-v2-graph

### ISSUE THREAD

**Issue by Azer1652** [microsoft/azure-spring-boot#820]
## Environment
- Spring boot starter:
  - active directory spring boot starter

- Tested versions: 2.2.0 -> master
  
- OS Type: Windows
- Java version: 
  - 1.8

## Summary
`isMatchingUserGroupKey()` in AzureADGraphClient throws NullPointerException when the following configuration property is set
`azure.activedirectory.environment=global-v2-graph `

## Reproduce steps

- Setup Angular application that authenticates with AAD and Spring
[https://github.com/microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-active-directory-spring-boot-sample](https://github.com/microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-active-directory-spring-boot-sample)

- Set environment variable
`azure.activedirectory.environment=global-v2-graph`

## Expected Results
A list of groups is returned from `getGroups()` just as it is when not setting the environment variable.

## Actual Results
NullPointerExceptions are thrown from `isMatchingUserGroupKey()` because 
`node.get(aadAuthenticationProperties.getUserGroup().getKey())` is null.
`aadAuthenticationProperties.getUserGroup().getKey()` resolves to "objectType" which is not present in the returned JSON.

Returned JSON (removed sensitive data)

```
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#directoryObjects",
  "value": [
    {
      "@odata.type": "#microsoft.graph.group",
      "id": "foo",
      "deletedDateTime": null,
      "classification": null,
      "createdDateTime": "foo",
      "creationOptions": [],
      "description": "Site URL: foo",
      "displayName": "foo",
      "groupTypes": [],
      "isAssignableToRole": null,
      "mail": null,
      "mailEnabled": false,
      "mailNickname": "foo",
      "onPremisesDomainName": null,
      "onPremisesLastSyncDateTime": "foo",
      "onPremisesNetBiosName": null,
      "onPremisesSamAccountName": null,
      "onPremisesSecurityIdentifier": "foo",
      "onPremisesSyncEnabled": true,
      "preferredDataLocation": null,
      "proxyAddresses": [],
      "renewedDateTime": "foo",
      "resourceBehaviorOptions": [],
      "resourceProvisioningOptions": [],
      "securityEnabled": true,
      "securityIdentifier": "foo",
      "visibility": null,
      "onPremisesProvisioningErrors": []
    }
  ]
}
```

**Comment by neuqlz** [comment]
Hi @Azer1652,
Have you configured groups in your AAD? If not, you need to add groups in your AAD in the Azure portal.

**Comment by Azer1652** [comment]
Yes, I am using the AAD of my organization. The user with which I was testing has 50+ groups configured.

**Comment by neuqlz** [comment]
That's strange, could you provide me with the full exception stack Infos and the application.poperties? And when was the exception thrown out? Did it come when the application started?

**Comment by neuqlz** [comment]
Btw, if you set: azure.activedirectory.environment=global-v2-graph.
You must put these properties below in your application.properites.
azure.activedirectory.user-group.key=@odata.type
azure.activedirectory.user-group.value=#microsoft.graph.group
azure.activedirectory.user-group.object-id-key=id

**Comment by neuqlz** [comment]
> Btw, if you set: azure.activedirectory.environment=global-v2-graph.
> You must put these properties below in your application.properites.
> azure.activedirectory.user-group.key=@odata.type
> azure.activedirectory.user-group.value=#microsoft.graph.group
> azure.activedirectory.user-group.object-id-key=id

It is mentioned in this doc: https://github.com/microsoft/azure-spring-boot/tree/master/azure-spring-boot-starters/azure-active-directory-spring-boot-starter

**Comment by Azer1652** [comment]
Hi @neuqlz ,

Thanks for checking. I have not tried with all those properties enabled. I will try them and come back to you.

**Comment by Azer1652** [comment]
This fixes the issue. Thanks!
