### ISSUE TITLE
Support for Managed Identity

### ISSUE THREAD

**Issue by nmiodice** [microsoft/azure-spring-boot#823]
## Environment
This applies to all services that support Managed Identity in Azure.
  

## Summary
These starter kits do not allow you -- to my knowledge -- to leverage Manged Identity to authenticate to Azure services, which is a feature of https://github.com/Azure/azure-sdk-for-java that allows developers to **securely** connect to services like KeyVault, Service Bus, Blob Storage, etc., without having to supply secrets through environment variables.

It would be great if we could start to move away from the insecure practice of providing environment variables that contain sensitive information like connection strings and passwords, and towards the more secure approach of using Managed Identity.

Note: The https://github.com/Azure/azure-sdk-for-java libraries allow for the use of `DefaultAzureCredential` to authenticate to services, which will fall back to an environment based approach if not running within the context of Managed Identity.

## Reproduce steps
N/A

## Expected Results
N/A

## Actual Results
N/A

**Comment by neuqlz** [comment]
Thanks for your proposal, @saragluna Xiaolu is doing this feature now. Please stay tuned.

**Comment by saragluna** [comment]
Thanks for bringing this up. As far as I know, our KeyVault starter now supports Managed Identity.

**Comment by sitase** [comment]
When you're at it, please throw in support for AzureCliCredentials. (#846)

**Comment by saragluna** [comment]
As we're retiring some modules: 
- blob storage starter
- service bus starter
- media services starter

So currently the need to be supported starters are:
- [x] the Key Vault starter
- [ ] the Cosmos DB starter

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
