### ISSUE TITLE
Stateless authentication and Microsoft identity platform (v2.0)

### ISSUE THREAD

**Issue by fgoulet** [microsoft/azure-spring-boot#824]
## Environment
- Spring boot starter:
  - active directory spring boot starter

- OS Type: Windows
- Java version: 
  - 1.8

## Summary
It is possible to have a stateless authentication rest API that would accept v2.0 tokens ?
Then, I would like to use Microsoft Authentication Libraries (MSAL) to access to api.

**Comment by neuqlz** [comment]
Hi, thanks for the proposal, our team are working on it now, please stay tuned.

**Comment by saragluna** [comment]
Thanks for bringing this up. Just for clarification, I'd like to know what do you mean by 'rest API accepting v2.0 tokens'?

**Comment by fgoulet** [comment]
I mean a Spring Boot application with Rest controllers that would authenticate using the [Microsoft Identity Platform](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-overview). That would allow our Angular app to use the more modern MSAL javascript library to securely access the rest controllers.

**Comment by saragluna** [comment]
Sure. This PR #826 has migrated our ADAL usage to MSAL.
