### ISSUE TITLE
azure-active-directory-v2-spring-boot-backend-sample is dead on arrival

### ISSUE THREAD

**Issue by macfisher** [microsoft/azure-spring-boot#837]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  
  - 1.8+
  

## Summary
Instructions say to run `mvn clean install -DskipTests` from project root. Results in null pointer exception. Fails to build.

## Reproduce steps
Follow the instructions

## Expected Results
Project should build with mvn clean install

## Actual Results
NPE

**Comment by macfisher** [comment]
Project builds if you remove it from the larger project via the following pom file changes:
```
   <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.9.RELEASE</version>
        <relativePath/>  <!-- lookup parent from repository -->
    </parent>```

And define the starter version:
```
<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-active-directory-spring-boot-starter</artifactId>
            <version>2.2.3</version>
 </dependency>
```

Also removed the project.rootdir property.

**Comment by neuqlz** [comment]
Hi @macfisher, thanks for touch us.
I think you need to run **mvn clean install -DskipTests** from azure-spring-boot root rather than azure-active-directory-spring-boot-starter. Because there are some dependencies defined in the outside module like azure-spring-boot and azure-spring-boot-bom, so if you run that command only in  azure-active-directory-spring-boot-starter, it will fail.

**Comment by macfisher** [comment]
@neuqlz  Sorry, that's what I meant by project root. I was running from the root of the entire repository. Are you saying that running clean install works for you? It does not work for me:

`[INFO] Reactor Summary:
[INFO] 
[INFO] Azure Spring Boot BOM 2.2.4-SNAPSHOT ............... SUCCESS [  0.260 s]
[INFO] Azure Spring Boot Parent 2.2.4-SNAPSHOT ............ SUCCESS [  2.429 s]
[INFO] Azure Spring Boot AutoConfigure 2.2.4-SNAPSHOT ..... FAILURE [  5.203 s]
[INFO] Azure Spring Boot Starter 2.2.4-SNAPSHOT ........... SKIPPED
[INFO] Azure Metrics Spring Boot Starter 2.2.4-SNAPSHOT ... SKIPPED
[INFO] Azure AD B2C Spring Security Integration Spring Boot Starter 2.2.4-SNAPSHOT SKIPPED
[INFO] Azure AD Spring Security Integration Spring Boot Starter 2.2.4-SNAPSHOT SKIPPED
[INFO] Azure Cosmos DB Spring Boot Starter 2.2.4-SNAPSHOT . SKIPPED
[INFO] Azure Key Vault Secrets Spring Boot Starter 2.2.4-SNAPSHOT SKIPPED
[INFO] Azure Media Services Spring Boot Starter 2.2.4-SNAPSHOT SKIPPED
[INFO] Azure Service Bus Spring Boot Starter 2.2.4-SNAPSHOT SKIPPED
[INFO] Azure Storage Spring Boot Starter 2.2.4-SNAPSHOT ... SKIPPED
[INFO] Spring Data Gremlin Boot Starter 2.2.4-SNAPSHOT .... SKIPPED
[INFO] Azure Service Bus JMS Spring Boot Starter 2.2.4-SNAPSHOT SKIPPED
[INFO] Azure Spring Boot Starters 2.2.4-SNAPSHOT .......... SKIPPED
[INFO] Azure Spring Boot Samples 0.0.1-SNAPSHOT ........... SKIPPED
[INFO] Azure AD B2C Spring Security 5 OAuth2 Integration Spring Boot Sample 0.0.1-SNAPSHOT SKIPPED
[INFO] Azure AD Spring Security 5 OAuth2 Integration Spring Boot Sample 0.0.1-SNAPSHOT SKIPPED
[INFO] Azure AD Spring Security 5 OAuth2 V2 Integration Spring Boot Sample 0.0.1-SNAPSHOT SKIPPED
[INFO] Azure AD Spring Security Integration Spring Boot Sample 0.0.1-SNAPSHOT SKIPPED
[INFO] Azure AD Stateless Spring Security Integration Spring Boot Sample 0.0.1-SNAPSHOT SKIPPED
[INFO] Azure Cosmos DB Spring Boot Starter Sample 0.0.1-SNAPSHOT SKIPPED
[INFO] Azure Key Vault Secrets Spring Boot Starter Sample 0.0.1-SNAPSHOT SKIPPED
[INFO] Azure Media Services Spring Boot Starter Sample 0.0.1-SNAPSHOT SKIPPED
[INFO] Azure Service Bus Spring Boot Starter Sample 0.0.1-SNAPSHOT SKIPPED
[INFO] Azure Storage Spring Boot Starter Sample 0.0.1-SNAPSHOT SKIPPED
[INFO] Azure Cloud Foundry Service Sample 0.0.1-SNAPSHOT .. SKIPPED
[INFO] Spring Data Gremlin Boot Starter Sample 0.0.1-SNAPSHOT SKIPPED
[INFO] Azure Service Bus JMS Queue Spring Boot Starter Sample 0.0.1-SNAPSHOT SKIPPED
[INFO] Azure Service Bus JMS Topic Spring Boot Starter Sample 0.0.1-SNAPSHOT SKIPPED
[INFO] Azure Spring Boot Tests 2.2.4-SNAPSHOT ............. SKIPPED
[INFO] azure-spring-boot-test-core 2.2.4-SNAPSHOT ......... SKIPPED
[INFO] azure-spring-boot-test-application 0.0.1-SNAPSHOT .. SKIPPED
[INFO] azure-spring-boot-test-aad 2.2.4-SNAPSHOT .......... SKIPPED
[INFO] azure-spring-boot-test-keyvault 2.2.4-SNAPSHOT ..... SKIPPED
[INFO] azure-spring-boot-test-cosmosdb 2.2.4-SNAPSHOT ..... SKIPPED
[INFO] Azure Spring Boot Build 2.2.4-SNAPSHOT ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.280 s
[INFO] Finished at: 2020-03-06T08:03:24-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project azure-spring-boot: Fatal error compiling: CompilerException: NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :azure-spring-boot
`

**Comment by saragluna** [comment]
@macfisher 

This might be caused by the maven or maven plugin. Have you tried to upgrade your maven version?

**Comment by macfisher** [comment]
No I have not tried that. I just extracted the sample that I needed from the larger project and got that working without having to mess with my maven version. Feel free to close this if you want.

**Comment by neuqlz** [comment]
@macfisher okay, if you have any other questions, please feel free to ping me.
