### ISSUE TITLE
How is the library licensed ?

### ISSUE THREAD

**Issue by beowulf79** [microsoft/azure-spring-boot#838]
## Environment
- Spring boot starter:
  - active directory spring boot starter
  
- OS Type:
Linux

- Java version: 
  - 1.8
  

## Summary
Do I require a license to use the library in my Product ? My company has of course a valid Azure subscription; cannot find this information anywhere.

Thanks.

## Reproduce steps
.

## Expected Results
.

## Actual Results
.

**Comment by neuqlz** [comment]
Because this library is an open-source library licensed by MIT license. So you can use it in your product as you want and don't need to require a license.

**Comment by neuqlz** [comment]
Because this library is an open-source library licensed by MIT license. So you can use it in your product as you want and don't need to require a license. @beowulf79

**Comment by saragluna** [comment]
No update on this issue so close it for now.
