### ISSUE TITLE
azure.keyvault.refresh-interval is not working

### ISSUE THREAD

**Issue by venukbh** [microsoft/azure-spring-boot#839]
## Environment
- Spring boot starter:
  - key vault spring boot starter
  
- OS Type: Linux/MacOS
- Java version: 
  - 1.8
  

## Summary
Followed the steps mentioned on the page, and was able to read the keys from key-vault. 
Changed the refresh-interval to 2 minutes = 120000 milli seconds
After app started, changed the values in azure key vault, and for every 2 minutes thereafter, verified to see the new value reflected. But I do not see the value being reflected. It is still using the old value.

## Reproduce steps
Followed the steps mentioned on the page, and was able to read the keys from key-vault. 
Changed the refresh-interval to 2 minutes = 120000 milli seconds
After app started, changed the values in azure key vault, and for every 2 minutes thereafter, verified to see the new value reflected. But I do not see the value being reflected. It is still using the old value.

## Expected Results
Get the updated key value from key vault

## Actual Results
Always storing the initial loaded value and not refreshing the latest value.

**Comment by neuqlz** [comment]
please refer to this doc: https://github.com/microsoft/azure-spring-boot/tree/master/azure-spring-boot-starters/azure-keyvault-secrets-spring-boot-starter, in section: Custom settings. It mentioned that if you set specific keys by property: azure.keyvault.secret.keys=key1,key2,key3. the starter will not refresh the keys. If you want the starter to refresh the keys periodically, you can remove the property, but without that property, the starter will load all the keys in your keyvault. You can use whatever mode according to your scenario.

**Comment by venukbh** [comment]
@neuqlz I am not using that property.

These are the properties I am using

> 
> azure.keyvault.uri=https://test-myvault.vault.azure.net/
> azure.keyvault.client-id=my-client-id
> azure.keyvault.client-key=my-client-secret
> azure.keyvault.refresh-interval=120000

Here is the code
```

@Component
@Order(1)
public class AKVTest implements CommandLineRunner{
    @Value("${cdb-checkout-key}")
    private String connectionString;`

 @Override
    public void run(String... varl) throws Exception {
        System.out.println(String.format("\nConnection String stored in Azure Key Vault:\n%s\n",connectionString));
    }

    public void printValue() throws Exception {
        System.out.println(String.format("\nConnection String stored in Azure Key Vault with print method:\n%s\n",connectionString));
    }
}
```

**Comment by venukbh** [comment]
@neuqlz reopen the issue

**Comment by PoojaPaniker** [comment]
hi @venukbh ,
Was a solution provided for this issue ?
