### ISSUE TITLE
User flow is missing in the authorization request for B2C

### ISSUE THREAD

**Issue by tomatsue** [microsoft/azure-spring-boot#841]
## Environment
- Spring boot starter:
  - azure-active-directory-b2c-spring-boot-starter
- OS Type: Windows/Linux
- Java version: 
  - 1.8
  

## Summary
[The Docs tutorial](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc) ([in this repo](https://github.com/microsoft/azure-spring-boot/blob/2.2.3/azure-spring-boot-starters/azure-active-directory-b2c-spring-boot-starter/README.md)) results in 404 error. It seems to be because a user flow isn't specified in the authorization request. Like,
```
GET https://contosob2c.b2clogin.com/contosob2c.onmicrosoft.com/oauth2/v2.0/authorize
?response_type=code
&client_id=7a945e86-c12e-4f0c-b1a0-942f1857f953
&scope=7a945e86-c12e-4f0c-b1a0-942f1857f953%20openid
&state=2ada18rj8X9cXb6pTknrZe3_1pWOu1la8-ctjY-ZAZM%3D
&redirect_uri=http://localhost:8080/home
&nonce=hl3FFEoVEZraN6D1Fm0uwp5v8qnDWhlerN4rya4h5fM
```

The authorization request for B2C requires a user flow to run. It must be in the authority uri (`https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/{policy}/`) or with p parameter (`p={policy}`). 

* [OAuth 2.0 authorization code flow in Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/authorization-code-flow)

## Reproduce steps
The same steps in [the Docs tutorial](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc).

## Expected Results
The same result shown in [the Docs tutorial](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc).

## Actual Results
After the step 3 in the 'Build and test your app', the browser shows 404 error page instead of a login page.

**Comment by saragluna** [comment]
Thanks for reaching out. I've checked the tutorial you followed, there's some inaccuracy in it. This [one](https://github.com/microsoft/azure-spring-boot/tree/2.2.3/azure-spring-boot-samples/azure-active-directory-b2c-oidc-spring-boot-sample) is correct about the tenant name part. 

Take the domain name `contosob2c.onmicrosoft.com` for instance, the tenant name should be **contosob2c** not the domain name.

I'll create a PR to fix this and sorry for the inconvenience.

**Comment by tomatsue** [comment]
Thank you for checking.  However, I already tried the correct tenant name before posting this issue. So I think the error occurs because a user flow parameter is missing in the authentication request generated by [AADB2CAutoConfiguration](https://github.com/microsoft/azure-spring-boot/blob/2.2.3/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/b2c/AADB2CAutoConfiguration.java#L133).

**Comment by saragluna** [comment]
The application works on my side. Could you please provide the application.yml you configured, with no confidential info, to help check the issue?

**Comment by saragluna** [comment]
And for the policy parameter, it's added [here](https://github.com/microsoft/azure-spring-boot/blob/2.2.3/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/b2c/AADB2CAuthorizationRequestResolver.java#L91).

**Comment by tomatsue** [comment]
Thank you for clarification I tried the tutorial again in my new env and the sample worked well! I'll recheck my former env and will share the cause if I find it. Anyway I would be glad if you fix the Docs' known inaccuracy you mentioned.

**Comment by tomatsue** [comment]
I see the error happend just because of  my misconfiguration. I created *controller* and *security* folders under *src/main* instead of *src/main/java/com/example/demo*. 

By the way, there are still some inaccuracies in the tutorial. It would be helpful if you fix them even though they might be trivial.

* *HelloController.java* -> *WebController.java*
* *WebSecurityConfig.java* -> *WebSecurityConfiguration.java*
* `sample.aad` -> `com.example.demo`, if users follow the Spring Initializr's screen shot.

**Comment by saragluna** [comment]
Thanks for your suggestion. We'll fix them.

**Comment by saragluna** [comment]
Close this issue for now.
