### ISSUE TITLE
How can I use the secrets in my Test scope to read property from keyvault @Value("${property}") 

### ISSUE THREAD

**Issue by sudhakarbetha** [microsoft/azure-spring-boot#845]
## Environment
- Spring boot starter:
 - key vault spring boot starter
  
- OS Type: Windows
- Java version: 
  - 1.8
  

## Summary
I cannot use the KeyVault properties in my Tests, even if i define the <scope>test</scope> for the dependency in my pom.xml 

## Reproduce steps
Set <scope>test</scope>  for azure-keyvault-secrets-spring-boot-starter in pom.xml
I cannot read the KeyVault property in my tests as @Value("${property}")
I get them as ${property}

## Expected Results
I would need to retrieve the value from the keyvault

## Actual Results
$(property} is returned

**Comment by saragluna** [comment]
Thanks for reaching out. Could you help provide more info, such as how the tests are written or configuration are set?

**Comment by sudhakarbetha** [comment]
I was able to get this by getting the context to test by 
@SpringBootTest

**Comment by saragluna** [comment]
Close this issue for now.
