### ISSUE TITLE
Support Spring Boot Apps to run behind Network proxies for HTTP Client

### ISSUE THREAD

**Issue by sdandey** [microsoft/azure-spring-boot#850]
- Spring boot starter:
  - active directory spring boot starter
  - cosmosdb spring boot starter
  - key vault spring boot starter
  - media services spring boot starter
  - service bus spring boot starter
  - storage spring boot starter
  
- OS Type: Windows/Linux/MacOS
  - 1.8

  

## Summary
This is a feature request to support http proxy for all spring boot applications for HTTPClient.

for e.g., while use azure-java-sdk I can create HTTP Client using below code and run the request behind proxies.  I don't see this support with spring-boot-starter apps.
` HttpClient httpClient = new OkHttpAsyncHttpClientBuilder()
                .proxy(new ProxyOptions(ProxyOptions.Type.HTTP, new InetSocketAddress("<proxyHost>", <proxyPort>))
                        .setCredentials("<proxyUsername>", "<proxyPassword"))
                .build();`

**Comment by saragluna** [comment]
Thanks for reporting this. But I'm not sure which HttpClient you're referring to. Is it the one working underneath the SDKs, e.g. the CosmosDB SDK, or the one you want to use in your code?

**Comment by sdandey** [comment]
@saragluna,  i'm referring to one that's underneath the SDK.  there is not a good support for spring-boot-keyvault starter's to use the proxy.  So, I ended up using the SDK by creating our own HttpClient with proxy options.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
