### ISSUE TITLE
AAD multi-factor authentication(MFA), conditional access

### ISSUE THREAD

**Issue by stigmelling** [microsoft/azure-spring-boot#851]
Running azure-active-directory-spring-boot-backend-sample using mvn spring-boot:run

Get error message: 
AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000002-0000-0000-c000-000000000000'. Trace ID: 124cfcb0-3140-430c-b59c-68d160821c00 Correlation ID: 74178b2b-1281-4070-99b4-c6d748786c3c Timestamp: 2020-03-23 14:02:43Z

## Environment
- Spring boot starter: active directory spring boot starter

- OS Type: Linux
- Java version: 
  - 1.8
  - 1.11

  
## Summary
Not able to log in fore some useres on some locations

## Reproduce steps
git clone ...
mod applicaiton.properties

- spring.security.oauth2.client.registration.azure.client-id=
- spring.security.oauth2.client.registration.azure.client-secret=
- azure.activedirectory.tenant-id=

Start SpringBoot using mvn spring-boot:run 

Log in to http://localhost:8080/
Auto redir to https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=xx
Select user
Add password
Azrure callbacks to http://localhost:8080/login/oauth2/code/azure?code=0.AQwA8s9uVVLp....
SpringBoot redirects to http://localhost:8080/login?error

## Expected Results
Noe errors

## Actual Results
Azure responds with error:  AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000002-0000-0000-c000-000000000000'. Trace ID: 124cfcb0-3140-430c-b59c-68d160821c00 Correlation ID: 74178b2b-1281-4070-99b4-c6d748786c3c Timestamp: 2020-03-23 14:02:43Z

[azure-spring-boot.log](https://github.com/microsoft/azure-spring-boot/files/4370038/azure-spring-boot.log)

**Comment by saragluna** [comment]
Thanks for reaching out.  Which version of the aad starter are you using? We've fixed this MFA issue in #815 and #816, could you try with version 2.1.8 or 2.2.2?

**Comment by stigmelling** [comment]
I'm running version 2.2.4-SNAPSHOT
Will try with 2.2.2 and 2.1.8

**Comment by saragluna** [comment]
@stigmelling 

Any update on this issue?

**Comment by stigmelling** [comment]
Hi. 
I've tested the different versions. Same result. 
But I wonder if it is an Azure issue (?)
Two different scenarios: 
1. using my normal user - witch does not require MFA when logging in to https://outlook.office365.com/mail/
2. using my admin user - witch is set up to use MFA

Logging in to the sample app using scenario 1 - fails with  "...you must use multi-factor authentication"

Logging in to the sample app using scenario 2 works fine. 

Could this issue relate to a kind of misconfiguration in the Azure setup?

**Comment by saragluna** [comment]
@stigmelling 

Thanks for the update. I'm pretty sure that it's caused by enabling conditional policy in your tenant (or directory).
But I think we've handled this exception and redirect the user to do the MFA. Could you share more info about your AAD configuration?

**Comment by stigmelling** [comment]
Thanks @saragluna 
I dont have any insights into the AAD configuration. I'll ask for info about conditional policies set for our tenant. 

Is there a way I can redirect the user to a new MFA authentication login screen when these exceptions occur? The MFA authentication login should callback to my application on success.

**Comment by stigmelling** [comment]
I guess You can close this issue. 
I think it is related to AAD config(?)
