### ISSUE TITLE
Spring Boot application hangs without any error when azure-keyvault-secrets-spring-boot-starter version upgraded from 2.1.6 to 2.1.8

### ISSUE THREAD

**Issue by nandha2143** [microsoft/azure-spring-boot#853]
## Environment
- Spring boot starter:
  - key vault spring boot starter

  
- OS Type: Windows
- Java version: 
  - 1.8

  

## Summary
Spring Boot application hangs without any error when azure-keyvault-secrets-spring-boot-starter version upgraded from 2.1.6 to 2.1.8. Spring boot version is 2.1.10-RELEASE

## Reproduce steps
Spring 2.1.10-RELEASE. Upgraded  azure-keyvault-secrets-spring-boot-starter version upgraded from 2.1.6 to 2.1.8. Same application is working in 2.1.6

Application.yml

azure:
  keyvault:
    uri: 
    client-id: 
    client-key: 
    tenant-id: 
    allow:
      telemetry: false

## Expected Results
Spring boot application up and running and get all secrets from Azure key vault

## Actual Results
Spring boot app hangs

**Comment by saragluna** [comment]
Thanks for reaching out. Could you please try again with our latest release 2.1.9?

**Comment by nandha2143** [comment]
> Thanks for reaching out. Could you please try again with our latest release 2.1.9?

Hi Saragluna, Thank you for reply. Yes tried with 2.1.9  and same result

**Comment by saragluna** [comment]
Could you help provide some more details, like the pom file of your project, for me to reproduce the issue?

**Comment by jmax01** [comment]
I have the same issue appears to be in `KeyVaultOperation.fillSecretsList()`

``` java

    private void fillSecretsList() {
        try {
            this.rwLock.writeLock().lock();
            if (this.secretKeys == null || secretKeys.size() == 0) {
                this.propertyNames.clear();

                final PagedIterable<SecretProperties> secretProperties = keyVaultClient.listPropertiesOfSecrets();

               //Hangs here:
                secretProperties.forEach(s -> {
                    final String secretName = s.getName().replace(vaultUri + "/secrets/", "");
                    addSecretIfNotExist(secretName);
                });

                this.lastUpdateTime.set(System.currentTimeMillis());
            } else {
                for (final String secretKey : secretKeys) {
                    addSecretIfNotExist(secretKey);
                }
            }
            propertyNamesArr = propertyNames.toArray(new String[0]);
        } finally {
            this.rwLock.writeLock().unlock();
        }
    }
```

**Comment by saragluna** [comment]
@jmax01 

Thanks for your share. I will look into this.

**Comment by carlosraphael** [comment]
hi @saragluna I'm having the same issue using:

- Java -> 8
- Spring Boot -> 2.1.2.RELEASE
- Spring Azure Key Vault Secrets -> 2.1.10

**Comment by chenrujun** [comment]
I reported the issue [here](https://github.com/Azure/azure-sdk-for-java/issues/11808)

**Comment by chenrujun** [comment]
Hi, @nandha2143, please update version to 2.2.5 or 2.3.2.

**Comment by mosh2151984** [comment]
try 
```<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.7.RELEASE</version>
       <relativePath /> <!-- lookup parent from repository -->
</parent>

......

<properties>
        <java.version>1.8</java.version>
        <azure.version>2.1.6</azure.version>
 </properties>
```
