### ISSUE TITLE
azure-storage-spring-boot-starter refers to really old azure-storage-blob dependency

### ISSUE THREAD

**Issue by romlod** [microsoft/azure-spring-boot#854]
Hi,
We use the azure-storage-spring-boot-starter version 2.2.3. What we see is that this is still resolving to com.microsoft.azure:azure-storage-blob:10.5.0. This version however is from Feb 2019. 
If I look in mvnrepository, i see that there is already a 12.5.0 available which is updated in march 2020.
https://mvnrepository.com/artifact/com.azure/azure-storage-blob/12.5.0

Having this is key, because the old 11 version contains a lot of issues regarding 403 errors to blob and much more.

Thanks, Romario

**Comment by saragluna** [comment]
Thanks for reaching out. We're aware of this issue and planning to upgrade the dependency. Please stay in tune.

**Comment by romlod** [comment]
> Thanks for reaching out. We're aware of this issue and planning to upgrade the dependency. Please stay in tune.

That is great to hear! When can we expect this?

**Comment by saragluna** [comment]
We're still in the early planning stage now. And since the v12 storage library is not compatible with the version we're using now, we have to find a way to bring that out.

**Comment by anumalasri** [comment]
Any timeline or roadmap, you can share for this update ??

**Comment by yiliuTo** [comment]
Hi, currently we are migrating this repo to [https://github.com/Azure/azure-sdk-for-java](url), and for the mentioned consideration the storage starter will be deprecated. Then we will put it in a sample of how to use Azure storage.

**Comment by yiliuTo** [comment]
Hi, now we have updated the [sample project](https://github.com/microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-spring-boot-sample-storage-blob#sample-for-azure-blob-storage-spring-boot-client-library-for-java) about using Azure Blob storage with Spring Boot, you can refer to it.

**Comment by saragluna** [comment]
Closing this issue.
