### ISSUE TITLE
Key Vault Starter 2.1.8 has version conflict with Spring Cloud Greenwich.SR2

### ISSUE THREAD

**Issue by saragluna** [microsoft/azure-spring-boot#861]
## Environment
- Spring boot starter:
  
  - key vault spring boot starter

## Summary

This issue was reported by one customer.
>   I have tested azure-keyvault-secrets-spring-boot-starter with azure-spring-boot-bom version 2.1.8 in my demo application and that works well.  
>
> However, when I update this version in our real application (with a lot more dependencies in pom.xml), the application hangs during startup. There are no exceptions thrown in the console. So, it took me a while to figure out what causes the problem.
> 
> It seems there are some conflicts with this version and Spring cloud version Greenwich.SR2. In our pom.xml, we have the following dependencies which causes the problem.
·  spring-cloud-starter-sleuth
·  spring-boot-starter-data-jpa
> 
> Somehow when having these 2 dependencies in the pom and you upgrade azure-spring-boot-bom to version 2.1.8, Hibernate classes fail to instantiate. This is just my assumption because I don’t see any logging of Hibernate and the application just doesn’t write anymore log and isn’t completely started. It just hangs.
> 
> When I remove spring-cloud-starter-sleuth dependency, the application starts normally again.
> 
> So, to cut a long story short, I have to update the spring cloud version to Greenwich.SR5 and everything work fine again.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
