### ISSUE TITLE
Spring Boot starters are pulling in all Azure Spring Boot dependencies

### ISSUE THREAD

**Issue by burlesgonewild** [microsoft/azure-spring-boot#862]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  - cosmosdb spring boot starter
  - key vault spring boot starter
  - media services spring boot starter
  - service bus spring boot starter
  - storage spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  
  - 11 

## Summary
The Azure Spring Boot starters have a dependency on azure-spring-boot which contains the autoconfiguration for all Azure Spring Boot starters which have transitive dependencies on all 
 of the underlying Azure Spring libraries. For example, including just the Azure Spring Boot Cosmos starter I end up pulling the dependency tree for Key Vault along with all of Key Vaults transitive dependencies. This creates project bloat and makes it difficult to diagnose issues caused by those transitive dependencies. 

## Reproduce steps
Create a project that depends on any of the starters and view the dependency tree. The tree will include all dependencies of all Azure Spring Boot libraries instead of just the libraries related to the Azure component being used. 

## Expected Results
Only the dependencies related to the Azure component being used should be pulled into a project when using one of the Azure Spring Boot starters as a dependency.

## Actual Results
A bloated dependency tree full of unnecessary libraries that are not needed.

**Comment by saragluna** [comment]
Thanks for reaching out.

We're aware of this issue and are planning to refactor the current model.  Please stay in tune.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
