### ISSUE TITLE
KeyVaultEnvironmentPostProcessor.isKeyVaultEnabled should check the enabled flag before checking if AZURE_KEYVAULT_VAULT_URI is populated

### ISSUE THREAD

**Issue by jmax01** [microsoft/azure-spring-boot#867]
`KeyVaultEnvironmentPostProcessor.isKeyVaultEnabled` should check the enabled flag before checking if `AZURE_KEYVAULT_VAULT_URI` is populated.

URIs like `AZURE_KEYVAULT_VAULT_URI ` are often constructed from other properties and in many test scenarios resolution will fail due to those properties not being resolved.

Solution:

Reorder and simplify `isKeyVaultEnabled's` conditionals.

https://github.com/microsoft/azure-spring-boot/blob/4543480ed26976dfb9eec71375855da5ed24fdc6/azure-spring-boot/src/main/java/com/microsoft/azure/keyvault/spring/KeyVaultEnvironmentPostProcessor.java#L31-L38

Patch in PR: 
```java
    private boolean isKeyVaultEnabled(ConfigurableEnvironment environment) {
        return environment.getProperty(Constants.AZURE_KEYVAULT_ENABLED, Boolean.class, true)
                && environment.getProperty(Constants.AZURE_KEYVAULT_VAULT_URI) != null && isKeyVaultClientAvailable();
    }
```

**Comment by saragluna** [comment]
Thanks for bringing this up. Could you share more details about the test scenarios when resolution will fail due to the URI?

**Comment by jmax01** [comment]
Our default config defines the current pattern used for our keyvault instance,

We use profiles to set the referenced properties.

We were hoping to avoid having another profile to set the uri and we want to be able to test construction of the uri without having the KeyVaultEnvironmentPostProcessor start.

The patch fixes this issue.

```properties
#default config
#this currently fails
azure.keyvault.enabled=false
azure.keyvault.uri=https://${subscription.prefix}-${env.prefix}-${region.code}.vault.azure.net
```

**Comment by saragluna** [comment]
@jmax01 Thanks for your response and just for clarification:

When the user specifies `azure.keyvault.enabled` to `false`, the `KeyVaultEnvironmentPostProcessor` should not be started. In which case, the below code snippet does return false. 
 
https://github.com/microsoft/azure-spring-boot/blob/4543480ed26976dfb9eec71375855da5ed24fdc6/azure-spring-boot/src/main/java/com/microsoft/azure/keyvault/spring/KeyVaultEnvironmentPostProcessor.java#L31-L38

**Comment by jmax01** [comment]
> should not be started. In which case, the below code snippet does return false. Or do I miss something?

If `azure.keyvault.enabled` is false `KeyVaultEnvironmentPostProcessor` should *not* attempt to resolve `AZURE_KEYVAULT_VAULT_URI`.

Processing should cease immediately.

**Comment by jmax01** [comment]
The issue still exists in the new implementation. I will supply a new PR.

**Comment by chenrujun** [comment]
This problem already fixed in our [new repo](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot/src/main/java/com/microsoft/azure/keyvault/spring/KeyVaultEnvironmentPostProcessor.java#L59), so I'll close this issue.
