### ISSUE TITLE
Using deprecated active-directory-groups property doesn't appear to work and using new property fails to boot

### ISSUE THREAD

**Issue by juliovalcarcel** [microsoft/azure-spring-boot#869]
Because of [this](https://github.com/microsoft/azure-spring-boot/blob/v2.2.2/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/aad/AADOAuth2AutoConfiguration.java#L48]) conditional on property if you switch from using `azure.activedirectory.active-directory-groups` to `azure.activedirectory.user-group.allowed-groups=test` the autoconfigure fails to work.

**Comment by saragluna** [comment]
Thanks for reaching out. But I'm lost here, the switch is for?

**Comment by saragluna** [comment]
No updates on this issue, so close it for now.

**Comment by saragluna** [comment]
This issue has been fixed https://github.com/Azure/azure-sdk-for-java/issues/12986.
