### ISSUE TITLE
AppRole Example

### ISSUE THREAD

**Issue by FireDrunk** [microsoft/azure-spring-boot#874]
## Environment
- Spring boot starter:
  - active directory spring boot starter
  
- OS Type: Windows
- Java version: 
 - OpenJDK 11  

## Summary
All examples use the Graph API and leverage a secondary call to get the Groups from the user.
We want to use AppRoles instead.

https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps

## Reproduce steps
Several examples exist using different methods of authentication.
We want to support a simple user authentication flow (so stateful), and leveraging AppRoles configured in the Client ID to grant Spring Security Roles.
There are some issues regarding an SPA and using the AppRoles in a stateless backend, but none using a stateful approach.

## Expected Results
We want to use the approles as per Microsoft documentation mentioned above.

## Actual Results
Impossible to configure the library to use AppRoles.

**Comment by saragluna** [comment]
Thanks for reaching out but now we do not have such solutions. One possible solution is implementing such a filter in your code and plug it into the filter chain. We'll consider the idea to enhance our filters but that will take a while.

**Comment by mcarleio** [comment]
We are using the app roles approach with this library in version 2.2.1. Sadly, with the current version (maybe due to ADAL to MSAL change in 2.2.3 ?) this is no longer possible.

**Comment by saragluna** [comment]
@mcarleio we'll look into this issue ASAP. Close this issue since another one's created for your question.
