### ISSUE TITLE
AAD "Could not sign you in. please try again"

### ISSUE THREAD

**Issue by cccs-cat001** [microsoft/azure-spring-boot#877]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  
- OS Type: Linux
- Java version: 
  
  - 1.8
  

## Summary
Testing out the example code given tells me "could not sign you in please try again" when I hit it. 

## Reproduce steps
My application.properties is: 
```
spring.security.oauth2.client.registration.azure.client-id=
spring.security.oauth2.client.registration.azure.client-secret=

spring.security.oauth2.client.registration.azure.client-name=Azure
spring.security.oauth2.client.registration.azure.provider=azure-oauth-provider
spring.security.oauth2.client.registration.azure.scope=openid, user.read
spring.security.oauth2.client.registration.azure.client-authentication-method=basic
spring.security.oauth2.client.registration.azure.authorization-grant-type=authorization_code

spring.security.oauth2.client.provider.azure-oauth-provider.authorization-uri=https://login.microsoftonline.com/<tenantId>/oauth2/authorize
spring.security.oauth2.client.provider.azure-oauth-provider.token-uri=https://login.microsoftonline.com/<tenantId>/oauth2/token
spring.security.oauth2.client.provider.azure-oauth-provider.user-info-uri=https://login.microsoftonline.com<tenantId>/openid/userinfo
spring.security.oauth2.client.provider.azure-oauth-provider.jwk-set-uri=https://login.microsoftonline.com/<tenantId>/discovery/keys
spring.security.oauth2.client.provider.azure-oauth-provider.user-name-attribute=name

spring.security.oauth2.client.registration.azure.redirect-uri=http://localhost:8080
azure.activedirectory.tenant-id=<tenantId>
# It's suggested the logged in user should at least belong to one of the below groups
# If not, the logged in user will not be able to access any authorization controller rest APIs
azure.activedirectory.active-directory-groups=<group1 I'm a part of, group2 I am not>
```

The app registration has api permissions listed above (openid, user.read), it is set up with a redirect URI http://localhost:8080. 

After launching with `mvn spring-boot:run`, I browse to `http://localhost:8080`, and I get the login screen. It says "Could not sign you in please try again" but it will never log you in. 

## Expected Results
I'd want to be logged in. 

## Actual Results
It won't log me in.

**Comment by saragluna** [comment]
Thanks for reaching out. It seems like an issue reported by the login system. Have you tried again after that?

**Comment by cccs-cat001** [comment]
Yes it would always give me the same thing. I managed to get it working by setting the oauthimplicit flow to true, and playing around with the callback urls. For anyone also having this issue, I set my callback url to localhost:8080/login/oauth2/code/azure on both the app and on the app registration on azure

**Comment by saragluna** [comment]
Closing this issue.
