### ISSUE TITLE
azure-client-authentication v1.6 causes a build warning, should be fixed by upgrading to 1.7.0+

### ISSUE THREAD

**Issue by canburak** [microsoft/azure-spring-boot#878]
## Environment
- Spring boot starter:
  
  - key vault spring boot starter
  
- OS Type: MacOS
- Java version: 
  - 1.11

## Summary

I am depending on `azure-keyvault-secrets-spring-boot-starter:2.2.4`, which was the latest release while creating this ticket.

My build output has the following message:
```
Warning:java: Supported source version 'RELEASE_7' from annotation processor 'com.microsoft.azure.management.apigeneration.LangDefinitionProcessor' less than -source '11'
```
I am using maven, with a simple dependency definition:

```
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
            <version>2.2.4</version>
        </dependency>
```

When I tracked this issue and hunting for the solution, I've stumbled upon [v1.70 release of autorest-clientruntime-for-java](https://github.com/Azure/autorest-clientruntime-for-java/releases/tag/v1.7.0) which is supposed to fix that warning, based on the folowing note:

```
Update annotations to fix RELEASE_7 warning (#648)
```

You are recursively dependent to that library and you can bump it to `1.7.1`, which is the latest release.

https://github.com/microsoft/azure-spring-boot/blob/7a2cb9647fd2c5f3d45bee5faa55291a5231a066/azure-spring-boot-starters/azure-keyvault-secrets-spring-boot-starter/pom.xml#L37-L40

Here is the relevant section of my dependency tree:
```
[INFO] net.canb:fbackup:jar:0.0.1-SNAPSHOT
[INFO] +- com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter:jar:2.2.4:compile
[INFO] |  +- com.microsoft.azure:azure-spring-boot:jar:2.2.4:compile
[INFO] |  +- com.microsoft.azure:azure-client-authentication:jar:1.6.13:compile
[INFO] |  |  +- com.microsoft.azure:azure-client-runtime:jar:1.6.13:compile
[INFO] |  |  |  \- com.microsoft.rest:client-runtime:jar:1.6.13:compile
```

## Reproduce steps
* Depend on v2.2.4
* Build

## Expected Results
* No warning observed

## Actual Results
* Warning is observed

**Comment by saragluna** [comment]
Thanks for reporting this, we'll look into this soon.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
