### ISSUE TITLE
Azured Ad spring starter with Spring webflux

### ISSUE THREAD

**Issue by anandfmr** [microsoft/azure-spring-boot#879]
Hi,

Does Azure Ad starter support reactive spring. I see following error when trying to use it in my project. 

```
Caused by: java.lang.ClassNotFoundException: javax.servlet.Filter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	... 64 common frames omitted
```

**Comment by saragluna** [comment]
Thanks for reaching out, but the Azure AD starter does not support reactive stack for now.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues

**Comment by naridnevahgar** [comment]
I made a WebFlux resource server implementation with spring security and Azure AD [Here](https://github.com/naridnevahgar/spring-webflux-azuread-rbac) 
Works normally!

**Comment by chenrujun** [comment]
Hi, @naridnevahgar .
Thank you very much for your sharing.
We will continue the task in the new issue: https://github.com/Azure/azure-sdk-for-java/issues/21581

**Comment by letmagnau** [comment]
> Thanks for reaching out, but the Azure AD starter does not support reactive stack for now.

Hi @saragluna  , is webflux planned to be integrated in project? as authentication server ? usgin AADB2COidcLoginConfigurer??
it seems to be central for many project as Jhipster and we are using AADB2C for IAM and for now I don't see any solutions about

kind regards

Piero

**Comment by chenrujun** [comment]
@letmagnau

>  is webflux planned to be integrated in project? 

Yes.

> usgin AADB2COidcLoginConfigurer?

No.
We will not provide AbstractHttpConfigurer in 4.0 version. Further more, we will not provide b2c-starter since 4.0 version.

> it seems to be central for many project as Jhipster and we are using AADB2C for IAM and for now I don't see any solutions about

We will not provide b2c-starter since 4.0 version. Because after investifation, we found that all AAD B2C features can be accomplished by spring-security natively. We will provide sample  projects in this repo: https://github.com/Azure-Samples/azure-spring-boot-samples, but sample projects is not finished yet. @zhichengliu12581  is working on it.

You can refer to this PR to see how to let AAD B2C work with spring-security: https://github.com/spring-projects/spring-security-samples/pull/31

**Comment by letmagnau** [comment]
@saragluna @zhichengliu12581

it means that the azure configurations flows in application.yaml  wil be unused in the future?
How B2C will work as Auhtentication Server ed not only as resource server?

**Comment by chenrujun** [comment]
@letmagnau 

In this PR: https://github.com/Azure-Samples/azure-spring-boot-samples/pull/37
1. It only depends on spring-security related artifacts, not have aad-b2c starter.
2. It not only contain AAD B2C resource-server, it also contain using AAD B2C to login.

**Comment by letmagnau** [comment]
Hi @chenrujun 

nice to see it but it seems do not implement the WebFluxSecurity

in https://github.com/zhichengliu12581/azure-spring-boot-samples/blob/add-samples-for-aad-b2c-with-only-spring-security/aad/aad-b2c-with-spring-security/aad-b2c-web-application-1-simple-sample/src/main/java/com/spring/sample/b2c/security/WebSecurityConfiguration.java

you can see @EnableWebSecurity and not @EnableWebFluxSecurity
@EnableReactiveMethodSecurity

I am wrong ?

regards

Piero

**Comment by chenrujun** [comment]
Hi, @letmagnau 

Thank you for your check.
I will investigate @EnableWebFluxSecurity and @EnableReactiveMethodSecurity in this issue: #21581

And PR is welcome.

**Comment by letmagnau** [comment]
Hi @chenrujun 
i'm able to integrate WebFluxSecurity now but a question, 
in example editprofile and resetpassword are hardcoded , instead in loginControllere there is a configuraition that hide all the creation of it
With spring security 5 , only sign up sign in is configured and you have to be replicate 3 client provider with 3 different registration conf , it seems very DRY 

How can we manage it and write less configration?

**Comment by chenrujun** [comment]
Hi, @letmagnau.

> in example editprofile and resetpassword are hardcoded 

Could you please share related link?

> you have to be replicate 3 client provider with 3 different registration conf

In `spring-cloud-azure-oauth2-client:4.0.0` which is under developing ([PR 24280]), we will not provide client provider and registration by configuration item `azure.activedirectory.xxx`, we will use the clients provided by `spring-boot-starter-oauth2-client` by these configuration items:

```
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: github-client-id
            clientSecret: github-client-secret
# ...
```

So our clients can work with other clients with other providers like google.



[PR 24280]: https://github.com/Azure/azure-sdk-for-java/pull/24280

**Comment by thomas-worm-datev** [comment]
I managed to add WebFlux security support in the starter: https://github.com/Azure/azure-sdk-for-java/pull/30074
