### ISSUE TITLE
In the context of Key Vault, existing application properties that contain a mixture of dots and dashes don't map correctly

### ISSUE THREAD

**Issue by estaylorco** [microsoft/azure-spring-boot#887]
## Environment
- Spring boot starter: 
  - azure keyvault secrets spring boot starter
  
- OS Type: MacOS
- Java version: 
  - 11.0.2

## Summary
Existing application properties that contain a mixture of dots _and_ dashes do not map correctly from Key Vault.  By "existing" I mean properties that I, myself, did not create and, therefore, whose names I cannot control.

## Reproduce steps
Imagine working with an existing property named `server.ssl.key-store-password`.  I would have to store this in Key Vault as `server-ssl-key-store-password`.  However, the starter I reference above automatically converts the property name to `server.ssl.key.store.password`.  But of course, this is not correct.

## Expected Results
To be honest, knowing your substitution algorithm, I expected this wouldn’t work since there's no way, it seems, for the starter to know which dashes should be preserved and which should be converted to dots.

## Actual Results
Working within the logic of your design, to get the proper actual result, we would need to see one of the following:

- For Key Vault to allow key vault secret names to contain dots (".") (the best solution); or
- Provide a way to signal preservation (not too bad)

With respect to the latter, we could have something like this for a secret name: `server-ssl-key--store--password`, where the double dash indicates that the following dash should be preserved.  This might be the easiest to implement initially.

**Comment by saragluna** [comment]
Thanks for bringing this up and we'll consider this approach.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
