### ISSUE TITLE
[Feature Request] Key Vault Secrets only load on startup

### ISSUE THREAD

**Issue by mrm9084** [microsoft/azure-spring-boot#907]
## Environment
- Spring boot starter:
  
azure-keyvault-secrets-spring-boot-starter
  
- OS Type: Windows
- Java version: 

  - 1.8
  

## Summary
A feature should be added to the starter that allows secrets to be loaded only on startup. The not setting refreshing the refresh doesn't work when using another external configuration provider. i.e. spring-clould-azure's Azure App Configuration provider. When Azure App Configuration reloads configurations the Key Vault Secrets are also reloaded, which isn't desired.

Also mentioned here: https://github.com/Azure/AppConfiguration/issues/306#issuecomment-613217454

## Reproduce steps
Using both azure-keyvault-secrets-spring-boot-starter and spring-cloud-azure-appconfiguration-config-web results in unwanted key vault reloads.

## Expected Results
Be able to configure azure-keyvault-secrets-spring-boot-starter to only load on startup.

## Actual Results
azure-keyvault-secrets-spring-boot-starter is loaded every time App Configuration reloads.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
