### ISSUE TITLE
Apply all PRs created after migration began to azure-sdk-for-java repo

### ISSUE THREAD

**Issue by saragluna** [microsoft/azure-spring-boot#916]
This issue is used to track all PRs needed to be applied to azure-sdk-for-java repo. While this repo is still in service, we should keep track of the merged PRs here and apply them to the azure-sdk-for-java repo. 
- [x] #866  @saragluna 
- [x] #868  @chenrujun https://github.com/Azure/azure-sdk-for-java/pull/12134
- [x] #870  @saragluna 
- [x] #872  @saragluna 
- [x] #873  @saragluna 
- [x] #880  @saragluna 
- [x] #881  @saragluna 
- [x] #882  @chenrujun https://github.com/Azure/azure-sdk-for-java/pull/12079
- [x] #885  @saragluna 
- [x] #890 @chenrujun https://github.com/Azure/azure-sdk-for-java/pull/12186
- [x] #893  @saragluna 
- [x] #895  @chenrujun https://github.com/Azure/azure-sdk-for-java/pull/12189
- [x] #896  @chenrujun https://github.com/Azure/azure-sdk-for-java/pull/12318
- [x] #900  @chenrujun Not necessary in new repo.
- [x] #902  @chenrujun https://github.com/Azure/azure-sdk-for-java/pull/12189
- [x] #904  @chenrujun Not necessary any more.
- [x] #905   @chenrujun https://github.com/Azure/azure-sdk-for-java/pull/12318
- [x] #910  @chenrujun   https://github.com/Azure/azure-sdk-for-java/pull/12187
- [x] #912  @chenrujun https://github.com/Azure/azure-sdk-for-java/pull/11979
- [x] #915  @chenrujun https://github.com/Azure/azure-sdk-for-java/pull/12189
- [x] #919  @chenrujun https://github.com/Azure/azure-sdk-for-java/pull/12188

**Comment by chenrujun** [comment]
All PRs have merged to new repo. 
I'll close this issue.
