### ISSUE TITLE
[Bug] azure-active-directory-spring-boot-stateless-sample Project API endpoint call fail's with 403 Error

### ISSUE THREAD

**Issue by salujamanish** [microsoft/azure-spring-boot#918]
## Environment
- Spring boot starter:
  - active directory spring boot starter
  
- OS Type: Windows/Linux/MacOS 
- Java version: 
  - 1.8
 

## Summary
com.nimbusds.jwt.proc.BadJWTException: Invalid token audience. Provided value [api://XXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX]does not match neither client-id nor AppIdUri.

## Reproduce steps
Step 1: Clone the repo
Step 2: open project azure-spring-boot/azure-spring-boot-samples/azure-active-directory-spring-boot-stateless-sample/
Step 3 : Configure application.properties as per steps given in read me( https://github.com/microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-active-directory-spring-boot-stateless-sample#configure-applicationproperties ) 
Step 4: Build Project & Run the project.
Step 5: Generate the token from index.html (src/main/resources/static/index.html)
Step 6 : Invoke API end point(/public, /authorized, /admin/demo) with valid JWT token in header of the request.

## Expected Results

API endpoint(/public , /authorized, /admin/demo) should be accessible with valid JWT token with respective app roles.

## Actual Results

com.nimbusds.jwt.proc.BadJWTException: Invalid token audience. Provided value [api://XXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX]does not match neither client-id nor AppIdUri.
	at com.microsoft.azure.spring.autoconfigure.aad.UserPrincipalManager$1.verify(UserPrincipalManager.java:157) ~[azure-spring-boot-2.2.4.jar:na]
	at com.nimbusds.jwt.proc.DefaultJWTProcessor.verifyClaims(DefaultJWTProcessor.java:273) ~[nimbus-jose-jwt-7.9.jar:7.9]
	at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:366) ~[nimbus-jose-jwt-7.9.jar:7.9]
	at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:308) ~[nimbus-jose-jwt-7.9.jar:7.9]
	at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:299) ~[nimbus-jose-jwt-7.9.jar:7.9]

**Comment by sidyes** [comment]
Having the same issue now. How did you fix this @saragluna ?
Its working fine locally for me.

**Comment by saragluna** [comment]
@sidyes what do you mean by `working fine locally`? Could you describe the problem you're facing?

**Comment by sidyes** [comment]
It means that when I am running the server locally and run my REST calls from my (also) locally running frontend, the validation of the JWT token is working without any errors.

But when frontend and backend are deployed in our kubernetes cluster, the backend fails with the following error when validating the sent token:
```
com.nimbusds.jwt.proc.BadJWTException: Invalid token audience. Provided value [api://xxxxxx]does not match neither client-id nor AppIdUri.
```

The error message looks exactly the same. And by the way sorry! I accidently linked you instead of @salujamanish who created this issue!

**Comment by ThanhLongDoBK** [comment]
@saragluna how you fixed it? 

I'm facing the same problem.

**Comment by sidyes** [comment]
> @saragluna @salujamanish @sidyes how you fixed it?
> 
> I'm facing the same problem.

As I wrote before, I accidently used the wrong cliend id..
