### ISSUE TITLE
GoneException for all collections (HTTP StatusCode- 410)

### ISSUE THREAD

**Issue by linux-code** [microsoft/azure-spring-boot#932]
Getting GoneException for all collections (HTTP StatusCode- 410).
```
<dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-cosmosdb-spring-boot-starter</artifactId>
      <version>2.3.3</version>
</dependency>

```

consistencyLevel=**BOUNDED_STALENESS**
multi write location =true
preferred location South Central US, West US
connection mode=DIRECT

When I have tried with SESSION consistency with same configuration, things are working fine but same code is not working with bounded staleness. Please provide some information if i am missing something.

Error detail-
```Received gone exception, will retry, GoneException{error=null, resourceAddress='null', statusCode=410, message=The requested resource is no longer available at the server., causeInfo=null, responseHeaders={}, requestHeaders=null}```

ActivityId - ``` "activityId":"c003c09d-f9cb-11ea-8f9c-1b708d79119e" ```

**Comment by linux-code** [comment]
I have debugged this further. With same configuration but connectionMode is GATEWAY , things are working fine. 

Could you please confirm whether DIRECT mode is supported with BOUNDED_STALENESS or not ? There is no documentation I found which explains such details.

**Comment by zhoufenqin** [comment]
We have migrated this repo to azure-sdk-for-java repo, so I resubmit an issue there, see https://github.com/Azure/azure-sdk-for-java/issues/15393, closing this issue.

**Comment by linux-code** [comment]
Hi Team,
Is there any update on this. Please help me here to resolve this issue. Thank you.

**Comment by zhoufenqin** [comment]
hi @linux-code, could you follow the issue in https://github.com/Azure/azure-sdk-for-java/issues/15393, I think it's Cosmos SDK's problem, I'm asking them for help.
