### ISSUE TITLE
Keyvault stops working after adding a newer version of active-directory starter

### ISSUE THREAD

**Issue by mukeshgulia** [microsoft/azure-spring-boot#934]
# Environment

Spring boot starter:

key vault spring boot starter
active directory spring boot starter

OS Type: Linux

Java version: 1.8

# Summary
Keyvault is not called and properties are not loaded.

# Reproduce steps
Use these Versions

```
<dependency>
<groupId>com.microsoft.azure</groupId>
<artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
<version>2.1.8</version>
</dependency>

<dependency>
<groupId>com.microsoft.azure</groupId>
<artifactId>azure-active-directory-spring-boot-starter</artifactId>
<version>2.3.3</version>
</dependency>

```
# Expected Results
Spring should have loaded the keys from the key vault.

# Actual Results

**Comment by mukeshgulia** [comment]
Using the same version, 2.3.3, keyvault connects fine.

**Comment by zhoufenqin** [comment]
hi @mukeshgulia, we have migrated the repo to https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring, could you submit your issue there? it will ask you for more issue details. thanks

**Comment by ZhuXiaoBing-cn** [comment]
hi @mukeshgulia,azure-keyvault-secrets-spring-boot-starter:2.1.8 and azure-active-directory-spring-boot-starter:2.3.3 both refer to azure-spring-boot, but they refer to different versions of azure-spring-boot.This has led to dependency conflicts. It is suggested that you replace azure-keyvault-secrets-spring-boot-starter:2.1.8 with version 2.3.3 to resolve dependency conflicts.

**Comment by zhoufenqin** [comment]
closing the issue
