### ISSUE TITLE
AADB2COidcLoginConfigurer OAuth2 Additional Parameters

### ISSUE THREAD

**Issue by avadgama91** [microsoft/azure-spring-boot#938]
Hi,

While integrating spring boot application with Azure B2C, I need to pass an additional parameter as "domain_hint", and I am not able to find any way to add this in this class, if anyone have any idea for this please let me know.

**Comment by lu-cheng** [comment]
Hi @avadgama91 There is no support for passing additional parameters. Why do you need to pass additional parameters?

**Comment by avadgama91** [comment]
> Hi @avadgama91 There is no support for passing additional parameters. Why do you need to pass additional parameters?

I want to pass the Domain Hint while login link, I want to have to user flow integration with one of the link contains domain hint and another will be without domain hint, so if you have some idea let me know.

**Comment by LarsKemmann** [comment]
@lu-cheng This is also one of many custom parameters that we need to provide to B2C during login, to support our clients' different use cases. We can do this easily on other platforms, e.g. in ASP.NET Core we can add custom parameters to the B2C sign-in URL based on things like the individual user's request to the web API, but there is no documentation for how to achieve this with Microsoft's Spring Boot libraries for B2C.

**Comment by lu-cheng** [comment]
Thank you for your reply. I will investigate this issue.

**Comment by lu-cheng** [comment]
We have moved to another repository and I have moved this issue to the new repository.
https://github.com/Azure/azure-sdk-for-java/issues/17751

**Comment by avadgama91** [comment]
I have included the latest version of the SDK but and added additional parameters in the Application.yml but still additional parameters are not getting included auto URL generation, can you please check and update the document accordingly.

**Comment by saragluna** [comment]
@lu-cheng could you follow up on this?

**Comment by lu-cheng** [comment]
@avadgama91 Since the latest code has not yet been released, currently you can manually compile the master branch in the repository to use the latest code, or wait for the new version to be released next time.
If you manually compile the latest code, you can execute the following command:
> azure-sdk-for-java> mvn clean install -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true -Djacoco.skip=true​ -DskipTests -Dparallel-test -playback -am -pl sdk\spring\azure-spring-boot-starter-active-directory-b2c
