### ISSUE TITLE
Spring Boot B2C example redirects /home to /login on localhost; never goes anywhere on VM Tomcat9

### ISSUE THREAD

**Issue by gbsmith** [microsoft/azure-spring-boot#940]
Local OS: MacOS Catalina
VM OS: Ubuntu 20.04
VM app server: Tomcat9

Have already setup B2C tenant with JWT.ms and integrated Google Login.

Testing B2C with Spring as per https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.

When running directly from MacOS localhost command-line, B2C login works and I can see claim details on /home page (actually / loading /home). Then I can successfully click on to /greeting. But when I click back to /home, I get redirected to /login?error. A subsequent attempt to return to /greeting fails authn.

When I moved the WAR package to Tomcat9 running on an Azure VM in our VPN (https://10.40.0.5:8443/b2cdemo), the login page comes up, I am sent to AADB2C to login and then... right back to login, do not go to /home, do not collect $200. Attempts to go directly to /greeting also go nowhere. So what do I need to do to make this work in a real Tomcat deployment?

I am using all the versions cited in the Azure tutorial. The Tomcat is running under Azul OpenJDK 11.

Any ideas?

**Comment by gbsmith** [comment]
Log extracts attached:

[b2cdemo_logs.zip](https://github.com/microsoft/azure-spring-boot/files/5718565/b2cdemo_logs.zip)

**Comment by wujack778** [comment]
Hey , Maybe you can change `reply-url` from `http://localhost:8080/home` to `http://localhost:8080/Except-home` in **Azure** and **yml**.
But I don't clear  the environment of your tomcat , so try the solution above ?

**Comment by saragluna** [comment]
Since we've deprecated this repo, I'm recreating this issue in the new repo https://github.com/Azure/azure-sdk-for-java/issues/18350.

**Comment by saragluna** [comment]
Closing this issue now and we will keep supporting you in the new repo.
