### ISSUE TITLE
Spring boot reactive support

### ISSUE THREAD

**Issue by g-apparence** [microsoft/azure-spring-boot#942]
Hi,
as I cannot find any resources to connect using webflux I'm posting here. As reactive is now really used on spring with cassandra do you have any workaround to make it work? 
Would consider hosting our incoming project on azure cosmos DB with cassandra if this could work. 
Else is there any plan to support this? 

Thank you

**Comment by chenrujun** [comment]
@backwind1233 
FYI: https://github.com/microsoft/azure-spring-boot/issues/705#issuecomment-802384636

@g-apparence 

> do you have any workaround to make it work?

Currently, I don't have workaround.

>Else is there any plan to support this?

Yes, we have. But not sure when our starter can support reactive.

**Comment by g-apparence** [comment]
Yes, Thank you for your fast reply. 
Hope you plan this soon 👍

**Comment by chenrujun** [comment]
Closing this issue.
If you still have this problem, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
