### ISSUE TITLE
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-data-gremlin link is not valid

### ISSUE THREAD

**Issue by satyajitcet** [microsoft/azure-spring-boot#944]
i am searching any sample project for spring boot gremlin starter project. But given link is not valid(404). 
Which library is good to integrate java with cosmos gremlin api currently.

**Comment by chenrujun** [comment]
Hi, @satyajitcet

The spring-boot-starter-data-gremlin is deprecated and deleted from master branch.
If you want to check the legacy doc, please refer: 
1. https://github.com/Azure/azure-sdk-for-java/tree/azure-data-gremlin-spring-boot-starter_2.3.3/sdk/spring/azure-spring-boot-starter-data-gremlin
2. Samples: https://github.com/Azure/azure-sdk-for-java/tree/azure-data-gremlin-spring-boot-starter_2.3.3/sdk/spring/azure-spring-boot-samples
