### ISSUE TITLE
aud claim is not valid

### ISSUE THREAD

**Issue by ubik-valis** [microsoft/azure-spring-boot#946]
Hello there, I am facing some issues verifying my ID Token from the frontend in the backend. My application.yaml configuration is like this:

```
spring.security.oauth2.resourceserver.jwt.issuer-uri = https://login.microsoftonline.com/{tenant-id}/.well-known/openid-configuration
spring.security.oauth2.resourceserver.jwt.jwk-set-uri = https://login.microsoftonline.com/{tenant-id}/discovery/v2.0/key
```

I already set my app registration to v2 ID Tokens and the audience claims match when I receive the ID Token from the frontend. Yet I get the following error during the filtering process: `The aud claim is not valid`.

Is using `login.microsoftonline.com` the correct way, or should I use `sts.windows.net` endpoint? The problem with the later URI is that spring doesn't find it.

Thank you
Alex

**Comment by chenrujun** [comment]
Hi, @ubik-valis , did you use `azure-spring-boot-starter-active-directory`?

I think you should configure `azure.activedirectory.tenant-id`:

Example: https://github.com/Azure-Samples/azure-spring-boot-samples/blob/73e7cf7f36c37e0d1f35a0f4b3242d1515858a42/aad/azure-spring-boot-starter-active-directory/aad-resource-server/src/main/resources/application.yml#L10

**Comment by chenrujun** [comment]
Closing this issue because there is no response from the customer.
