### ISSUE TITLE
Sample for Daemon application that calls web APIs - Spring boot

### ISSUE THREAD

**Issue by RaghavThakkar** [microsoft/azure-spring-boot#950]
Hello,
I am looking for the sample in which my Deamon app calls web API.

https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-overview
My use case is very simple.

Deamon app acquire JWT token from the web API. 

Once a token has been acquired web API verify that token using roles. 

I could not find any sample of this flow.  

Could not any sample of the in spring-boot. 

Really appreciate it if you guide how to achieve the above solutions. 

Thanks.

**Comment by chenrujun** [comment]
Closing this issue in favor of https://github.com/Azure/azure-sdk-for-java/issues/27699
