### ISSUE TITLE
Signature validation fails on spring boot backend 

### ISSUE THREAD

**Issue by datasmithadvtech** [microsoft/azure-spring-boot#954]
I understand this occurs if access token associated with microsoft scope is used.

How do i request access token with another scope so that the signature will be successfully verified?

**Comment by chenrujun** [comment]
Hi, @datasmithadvtech 

Thanks for reaching out. 

Are you using `azure-spring-boot-starter-active-directory` or `spring-cloud-azure-starter-active-directory`? 

I'm not understand the problem. 
Could you please create a new issue in [azure-sdk-for-java repo](https://github.com/Azure/azure-sdk-for-java) and add more descriptions about the problem?

**Comment by saragluna** [comment]
@datasmithadvtech, I'm going to close this issue for no feedback provided. Please create a new issue in [azure-sdk-for-java](https://github.com/Azure/azure-sdk-for-java/issues) repo if you still have questions.
