### ISSUE TITLE
Possibility to specify multiple KeyVaults to connect to

### ISSUE THREAD

**Issue by DeSmetMaarten** [microsoft/azure-spring-boot#955]
in the issue "Possibility to specify multiple KeyVaults to connect to and mount all secrets as config props. #759" 
there is a link added to point to information on how to connect multiple keyvaults to a spring boot but the link(https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-keyvault-secrets#multiple-key-vault-support) does not work anymore #759

**Comment by chenrujun** [comment]
Hi, @DeSmetMaarten, thanks for reaching out.

Multiple KeyVaults is still supported.

Could you please try this sample?
https://github.com/Azure-Samples/azure-spring-boot-samples/blob/spring-cloud-azure_v4.4.0/keyvault/spring-cloud-azure-starter-keyvault-secrets/property-source/src/main/resources/application.yml

**Comment by chenrujun** [comment]
Closing this issue because there is no response for a long time.
