### ISSUE TITLE
Compatibility with Spring Security 6.0

### ISSUE THREAD

**Issue by Snyfir** [microsoft/azure-spring-boot#957]
The last release is not compatible with Sprint Security 6.0
Is there an update soon to fix this compatibility ?

**Comment by yiliuTo** [comment]
@Snyfir thanks for reaching out. This repository has been deprecated and migrated to https://github.com/Azure/azure-sdk-for-java. So could you close this one and raise your issue to https://github.com/Azure/azure-sdk-for-java/issues? Besides, please help to provide the information of the library and version you are using, thanks.

**Comment by Snyfir** [comment]
repository deprecated

**Comment by yiliuTo** [comment]
Hi@Snyfir , thanks for closing it, could you create another one in https://github.com/Azure/azure-sdk-for-java to track your issue? Also we need to know which library and version you are using to furthur invesitgate on it.
