### ISSUE TITLE
Common Gateway Interface issue on azure app service, spring cloud gateway 

### ISSUE THREAD

**Issue by Mohit00021** [microsoft/azure-spring-boot#959]
While performing load testing on a spring cloud gateway I am getting a request failure rate of about 30% - 40% and 0% on local and the error I get on each failed request is "The Specified CGI application encountered an error and the server terminated the process." 
Requests count 2500 
Ramp up period 5s
App service plan : P1V2
I have tried the following things:
- Increasing Heap Memory 
- By changing underlying web server to appache Tom cat instead of reactor netty  and changing max thread count.
- Increasing SSL handshake timeout 
- Upgrading Spring boot version to 3.0.2 & Spring cloud version to 2022.01.1
The services which are being called are working fine on the same plan and can handle the load

**Comment by chenrujun** [comment]
Hi, @Mohit00021 
Thanks for reaching out.

Here is my current understanding:
1. You are running your app in [Azure App Service](https://learn.microsoft.com/en-us/azure/app-service/).
2. Your system has a module develop by yourself with [spring-cloud-gateway](https://cloud.spring.io/spring-cloud-gateway/reference/html/).
3. Your system has no relationship with [Spring Cloud Azure](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/) and [Azure Spring Apps](https://learn.microsoft.com/en-us/azure/spring-apps/overview).

Correct me if my understanding is not right.

**Comment by Mohit00021** [comment]
Yes, @chenrujun your understanding is correct am I at the wrong place to ask this?

**Comment by chenrujun** [comment]
If the problem exists in your localhost, you can create an issue here: https://github.com/spring-cloud/spring-cloud-gateway

**Comment by chenrujun** [comment]
Closing this issue. Because there is no update for more than 2 weeks.
