### ISSUE TITLE
Documentation for Spring Stateless Minimal Example

### ISSUE THREAD

**Issue by deklaer** [microsoft/azure-spring-boot#966]
Please provide a documentation like how to create a simple stateless! spring boot application using your libary.
[This was a good start.](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory) But I've tried several mechanisms and always ended up using a stateful application with a session.
In spring 3.x I would add this line

`        http.sessionManagement { sessionManagement: SessionManagementConfigurer<HttpSecurity?> ->
            sessionManagement.sessionCreationPolicy(
                SessionCreationPolicy.STATELESS
            )
        }
`
And then set 'session-stateless: on' in my application.yml. But the system always tells me "too many redirects" even if the URL is correct. So I found it very hard without any nice examples of 'https://learn.microsoft.com' to understand what would be a minimal example. If I can run this example - I have a starting point.

**Comment by Netyyyy** [comment]
Hi @deklaer , could you try with this [sample](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/aad/spring-cloud-azure-starter-active-directory/aad-resource-server-by-filter-stateless)?

**Comment by Netyyyy** [comment]
Close the issue for long term inactivity
