### ISSUE TITLE
Hi @rohitmono57 , please help move this issue to this repo: https://github.com/Azure/azure-sdk-for-java

### ISSUE THREAD

**Issue by rohitvishal57** [Microsoft/azure-spring-boot#969]
Hi @rohitmono57 , please help move this issue to this repo: https://github.com/Azure/azure-sdk-for-java

_Originally posted by @Netyyyy in https://github.com/microsoft/azure-spring-boot/issues/968#issuecomment-1985155978_

**Comment by Netyyyy** [comment]
close for same as https://github.com/microsoft/azure-spring-boot/issues/968
